### ISSUE TITLE
Upgrade netty to 4.1.52.Final

### ISSUE THREAD

**Issue by shahmirn** [micronaut-projects/micronaut-core#3842] opened 2020-08-02 02:59 UTC
https://netty.io/news/2020/07/09/4-1-51-Final.html mentions some changes to accommodate openssl and GraalVM

**Comment by ilopmar** [comment] 2020-08-03 10:35
I've tested GraalVM integration with the `basic-app` and it works, but a few tests are failing due to this upgrade. See https://scans.gradle.com/s/xeosaepaf45dm

All of them are related to file uploads.

**Comment by shahmirn** [comment] 2020-08-03 11:55
@ilopmar Sorry, just realizing that I should add more context.

https://github.com/grpc/grpc-java/issues/7279 is a corresponding issue.

Essentially, I'm trying to use micronaut and Google Secret Manager, which internally uses grpc, which itself internally uses netty.

I was getting some issues related to grpc-netty-shaded in that library, so I requested an enhancement in grpc to use the latest netty.

In micronaut, it'd also be preferable to use the latest netty, so that two different versions aren't being used by different dependencies.

**Comment by ilopmar** [comment] 2020-08-03 13:07
We try to keep Micronaut up to date with new Netty versions. The reason we are not using 4.1.50 is because there was a regression in Netty: https://github.com/micronaut-projects/micronaut-core/pull/3278

At this moment we can't upgrade to 4.1.51 until we figure out why those tests are failing. I need to dig more into this but if it's a regression on Netty (which I don't know yet) we will need to postpone the upgrade at least until 4.1.52.

**Comment by croudet** [comment] 2020-08-03 13:51
Could be related to https://github.com/netty/netty/issues/10449

**Comment by ilopmar** [comment] 2020-08-03 13:57
Thanks @croudet. I'll keep an eye on that issue and I'll try the snapshot once it's fixed.

**Comment by croudet** [comment] 2020-08-07 12:35
Fix has been merged into netty. Just need to wait for netty 4.1.52.

**Closed** 2020-09-10 11:45 UTC
Labels: status: awaiting third-party
