### ISSUE TITLE
Wrong @Error handler is triggered for exceptions

### ISSUE THREAD

**Issue by euler1337** [micronaut-projects/micronaut-core#4062] opened 2020-09-09 15:45 UTC
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Run the `ControllerTest.testHandlerFirst` test, it works.
2. Run the `ControllerTest.testHandlerLast` test, which fails.

### Expected Behaviour

I expect the more specific error handler for (i.e. for the subtyped exception) to be triggered.

### Actual Behaviour

The less specific error handler (i.e. for  the parent exception`Throwable`) is triggered. I've noted that this only occur if the less specific error handler is defined ABOVE (on a lower line number) the more-specific error handler in the file. 

### Environment Information

- **Operating System**: MacOS
- **Micronaut Version:** 2.0.1
- **JDK Version:** 11 

### Example Application

https://github.com/euler1337/micronaut-error-handler

**Comment by jameskleeh** [comment] 2020-09-09 18:18
@euler1337 This was already resolved and is scheduled for 2.0.2. Please try the snapshot

Duplicate of #3834

**Closed as completed by jameskleeh** 2020-09-09 18:18 UTC
