### ISSUE TITLE
ExecptionHandler with <Exception> type parameter produces two responses instead of one

### ISSUE THREAD

**Issue by glockbender** [micronaut-projects/micronaut-core#6145] opened 2021-09-10 23:02 UTC
### Expected Behavior

Exception Handler:
```kotlin
@Produces
@Singleton
class CommonExceptionHandler(
    private val errProcessor: ErrorResponseProcessor<*>,
) : ExceptionHandler<Exception, HttpResponse<*>> {

    override fun handle(request: HttpRequest<*>, exception: Exception): HttpResponse<*> =
        errProcessor.processResponse(
            ErrorContext.builder(request)
                .cause(exception)
                .error(
                    ErrorHelper.createError(
                        exception = exception,
                        path = request.path,
                        title = "Something went wrong"
                    )
                )
                .build(),
            HttpResponse.serverError<Any>()
        )
}
```

Controller:
```kotlin
@Controller("/sys")
open class ReadinessProbeService {

    private var isReady = AtomicBoolean(true)

    @Get("/readinessProbe")
    suspend fun readinessProbe(): HttpResponse<Nothing?> {
        val response = if (isReady.get()) {
            HttpResponse.status<Nothing?>(HttpStatus.OK).body(null)
        } else {
            HttpResponse.status<Nothing?>(HttpStatus.SERVICE_UNAVAILABLE).body(null)
        }
        return response
    }
}
```

When I make a request to `/sys/readinessProbe`, I expect to get one response with this exception handler typing.

![Снимок экрана 2021-09-11 в 01 40 02](https://user-images.githubusercontent.com/16047417/132924885-78eba3d7-4d9a-474f-9494-e82b2f0f2ed5.png)

Yes, I can change the exception type to RuntimeException and it starts working fine. But I need to handle all these exceptions. And this behavior looks like an bug.

### Actual Behaviour

But also with the first response i received a java.net.SocketException into `CommonExceptionHandler`:
![Снимок экрана 2021-09-11 в 01 42 45](https://user-images.githubusercontent.com/16047417/132925175-dd2ddd5f-a6c6-4efb-91aa-79cc89b56527.png)

And this exception is handle via exception handler and then produces 2nd response:
1st in logs:
![Снимок экрана 2021-09-11 в 01 56 42](https://user-images.githubusercontent.com/16047417/132925878-5de0354b-6651-4988-8f9f-fb7bbea9606b.png)
2nd in logs:
![Снимок экрана 2021-09-11 в 01 57 13](https://user-images.githubusercontent.com/16047417/132925895-46fbc7f8-ac5e-4386-8b8f-b7c86fe19332.png)
Also there is an exception about 2nd response:
![Снимок экрана 2021-09-11 в 01 57 05](https://user-images.githubusercontent.com/16047417/132925921-09473e8e-11bf-4eb9-80ae-100b1333f206.png)

### Steps To Reproduce

Just run micronaut application and send a request

### Environment Information

osx catalina: 10.15.7
jdk azul-15.0.3

versions:
```
kotlinVersion=1.5.30
micronautPluginVersion=2.0.3
micronautVersion=3.0.1
```

dependencies:
```
    implementation(platform("org.jetbrains.kotlin:kotlin-bom"))
    implementation("org.jetbrains.kotlin:kotlin-reflect")
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")

    implementation(platform("org.jetbrains.kotlinx:kotlinx-coroutines-bom:$coroutinesVersion"))
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-jdk8")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-slf4j")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-reactor")
    implementation("io.projectreactor.kotlin:reactor-kotlin-extensions:1.1.4")

    kapt("io.micronaut.openapi:micronaut-openapi")
    kapt("io.micronaut:micronaut-validation")
    implementation("io.micronaut:micronaut-http-client")
    implementation("io.micronaut:micronaut-management")
    implementation("io.micronaut:micronaut-runtime")
    implementation("io.micronaut.discovery:micronaut-discovery-client")
    implementation("io.micronaut.kotlin:micronaut-kotlin-extension-functions")
    implementation("io.micronaut.kotlin:micronaut-kotlin-runtime")
    implementation("io.micronaut:micronaut-validation")
```

### Version

3.0.1

**Comment by jameskleeh** [comment] 2021-09-22 16:37
Please upload a sample application that reproduces the issue

**Comment by jameskleeh** [comment] 2021-10-12 13:44
Closing due to a lack of a response

**Closed as completed by jameskleeh** 2021-10-12 13:44 UTC
