### ISSUE TITLE
Client in the test package cannot perform a DELETE operation

### ISSUE THREAD

**Issue by Joxebus** [micronaut-projects/micronaut-core#872] opened 2018-11-08 04:50 UTC
I was creating an example using a Client created at `test` package and when trying to perform a delete operation a message is shown telling that the operation is not allowed.

### Task List

- [Y] Steps to reproduce provided
- [Y] Stacktrace (if present) provided
- [Y] Example that reproduces the problem uploaded to Github
- [Y] Full description of the issue provided (see below)

### Steps to Reproduce

1. Clone the project 
2. Checkout the branch `issue-client-at-test-dir`
3. Execute the command `gradle test`

### Expected Behavior

All the test pass as successful 

### Actual Behavior

The `delete` operation throws an exception

### Stacktrace

```
21:36:11.796 [nioEventLoopGroup-1-21] TRACE i.m.http.client.DefaultHttpClient - Response Body
21:36:11.796 [nioEventLoopGroup-1-21] TRACE i.m.http.client.DefaultHttpClient - ----
21:36:11.796 [nioEventLoopGroup-1-21] TRACE i.m.http.client.DefaultHttpClient - {"_links":{"self":{"href":"/people","templated":false}},"message":"Method [DELETE] not allowed. Allowed methods: [PUT, GET, POST]"}
21:36:11.796 [nioEventLoopGroup-1-21] TRACE i.m.http.client.DefaultHttpClient - ----
21:36:11.817 [Test worker] ERROR i.m.r.intercept.RecoveryInterceptor - Type [com.nearsoft.micronaut.client.PersonClient$Intercepted] executed with error: Method [DELETE] not allowed. Allowed methods: [PUT, GET, POST]
io.micronaut.http.client.exceptions.HttpClientResponseException: Method [DELETE] not allowed. Allowed methods: [PUT, GET, POST]
	at io.micronaut.http.client.DefaultHttpClient$9.channelRead0(DefaultHttpClient.java:1726)
	at io.micronaut.http.client.DefaultHttpClient$9.channelRead0(DefaultHttpClient.java:1679)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.micronaut.http.netty.stream.HttpStreamsHandler.channelRead(HttpStreamsHandler.java:189)
...
```

### Workaround 

There are 2 ways to solve this problem actually

- 1.- Move the client to `main` sources

```
src/main
├── groovy
   └── com
       └── nearsoft
            └── micronaut
                  ├── client
                  └──PersonClient.groovy

```

- 2.- Override the method on `PersonClient` interface

```
@Client("/people")
interface PersonClient extends PersonApi {

    @Delete("/{id}")
    HttpResponse delete(Long id)

}
``` 
### Environment Information

- **Operating System**: MacOS
- **Micronaut Version:** 1.0.0
- **JDK Version:** 1.8.0_74

### Example Application

- https://github.com/Joxebus/MicronautGroovy

**Comment by jameskleeh** [comment] 2018-11-08 13:43
The project's tests pass as is. It would be better if the tests failed

**Comment by jameskleeh** [comment] 2018-11-08 16:38
https://issues.apache.org/jira/browse/GROOVY-8872

**Comment by jameskleeh** [comment] 2018-11-08 16:39
The issue is that the parameter names are not available at compile time for classes compiled in another source set. It turns out that even with setting the flag to enable the parameters, the AST transformation doesn't read them properly from the byte code.

**Comment by Joxebus** [comment] 2018-11-08 17:43
Thanks for the clarification, also I've updated the code to fail by default.

**Comment by jameskleeh** [comment] 2018-11-09 05:20
Related https://github.com/micronaut-projects/micronaut-profiles/commit/235d3a9f75ea5e8d26cf8ff6278c68ecacabe6e2

**Comment by graemerocher** [comment] 2018-12-20 07:32
Groovy 2.5.5 will be released soon which will resolve this

**Closed** 2019-02-12 13:18 UTC
Labels: status: awaiting third-party, status: validated, type: bug

**Comment by Joxebus** [comment] 2019-04-03 05:46
Test project upgraded to micronaut 1.1.0.RC2 and seems like everything is working now.

https://github.com/Joxebus/MicronautGroovy/tree/issue-client-at-test-dir

Thanks.
