### ISSUE TITLE
Micronaut 2.x.x: Optional parameters are not validated when provided

### ISSUE THREAD

**Issue by AndrejMitrovic** [micronaut-projects/micronaut-core#7918] opened 2022-08-29 09:17 UTC
### Expected Behavior

Calling the endpoint should throw an exception if the optional parameter fails validation.

### Actual Behaviour

Parameter becomes empty (`Optional.isPresent() == false`).

### Steps To Reproduce

Example was taken from previous issue https://github.com/micronaut-projects/micronaut-core/issues/3953 but with the Micronaut version dependency updated to `2.5.13`.

Run `gradle test`, and observe that one of the endpoint tests fail.

The failing endpoint has an optional parameter. When this parameter is provided but is not well-formed (validation should fail), what happens instead is that the parameter becomes empty.

---

It's currently impossible to distinguish between when a parameter was not provided versus when it was provided but it was invalid. Both cases will make the optional parameter empty. 

In our use-case we want to be able to send some kind of error back to the consumer if the parameter was indeed provided but it was in an invalid format.

We don't see a way to do that currently.

### Environment Information

Operating System: Windows 10
Micronaut Version: 2.5.13
JDK Version: temurin-11.0.16.1

### Example Application

https://github.com/AndrejMitrovic/micronaut-optional-queryvalue-validation/tree/69e42ec28f7c7ef29152b81aa7bc8888efde23c2

### Version

2.5.13

**Comment by yawkat** [comment] 2022-08-29 10:37
looks like a duplicate of #5135

**Closed as not planned by yawkat** 2022-08-29 10:37 UTC
