### ISSUE TITLE
CircuitBreaker always opens on exception

### ISSUE THREAD

**Issue by jmongard** [micronaut-projects/micronaut-core#5031] opened 2021-03-02 22:04 UTC
It looks like the `excludes`/`include`/`predicate` option of the circuit breaker only applies to the `Retryable` functionality of the circuit breaker and does not prevent the circuit from opening.

This is related to #1920 and #1921

**Alternative 1**:
If this is by design it should be clearly stated in the javadoc for the `@CircuitBreaker` annotation parameters. Currently the options is described as:
* The exception types to include (defaults to all)
* The exception types to exclude (defaults to none)
* The retry predicate class to use instead of `Retryable.includes` and `Retryable.excludes` (defaults to none)

A more accurate text if the current behaviour is the correct behaviour could be:
* The exception types to include that can be retried (defaults to all). The circuit will always open if no retries are made or all retry attempts fail.
* The exception types to exclude from being retried (defaults to none). The circuit will always open if no retries are made or all retry attempts fail.
* The retry predicate class to use instead of CircuitBreaker.includes and CircuitBreaker.excludes (defaults to none). The circuit will always open if no retries are made or all retry attempts fail.

**Alternative 2**:
If this is the wrong beahvior the code changes suggested in the [last comment](https://github.com/micronaut-projects/micronaut-core/issues/1920#issuecomment-688895324) in #1920 probably fixes this issue.

Looking at the code the the cause for this issue can be found in `DefaultRetryInterceptor`:
```
if (retryState.canRetry(exception)) { //<-- canRetry returns false (as expected) because of the excludes/include/predicate
  ...
} else {
  retryState.close(exception); //<-- CircuitBreakerRetry.close(Exception) actually opens the circuit if exception != null
  return Flowable.error(exception);
}
```

### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a `@Client` with a `@CircuitBreaker(excludes = HttpClientResponseException.class)` and point the client some location that will yield a `HttpClientResponseException` eg. HttpStatus 404
2. Call this client multiple times from a unit test
3. Verify that all calls were made and the circuit remained closed.

### Expected Behaviour

The circuit should remain closed.

### Actual Behaviour

The circuit opens.

### Environment Information

- **Operating System**: Windows 10
- **Micronaut Version:** 2.3.4
- **JDK Version:** 11

**Comment by jameskleeh** [comment] 2021-03-04 19:06
I marked this as a duplicate even though the other issue was created after this but it came with a PR

**Comment by jameskleeh** [comment] 2021-03-04 19:06
Duplicate of https://github.com/micronaut-projects/micronaut-core/issues/5037

**Closed as completed by jameskleeh** 2021-03-04 19:06 UTC
Labels: closed: duplicate
