### ISSUE TITLE
Ability to nest @EachProperty

### ISSUE THREAD

**Issue by pollend** [micronaut-projects/micronaut-core#3938] opened 2020-08-20 14:58 UTC
EachProperty does not work in a nested configuration. 

```
@ConfigurationProperties("outer1")
class NestedOuterProperties {

    String name
    List<InnerEach> inner

    @EachProperty("inner")
    static class InnerEach {
        Integer age
        List<NestedInnerEach> names

        @EachProperty("names")
        static class NestedInnerEach {
            String name;
        }
    }
}

```

groovy:
```
Failed to inject value for parameter [names] of method [setNames] of class: io.micronaut.inject.foreach.NestedOuterProperties$InnerEach

Message: Error resolving property value [outer1.inner.joe.names]. Property doesn't exist
Path Taken: NestedOuterProperties.setInner([List inner]) --> InnerEach.setNames([List names])
io.micronaut.context.exceptions.DependencyInjectionException: Failed to inject value for parameter [names] of method [setNames] of class: io.micronaut.inject.foreach.NestedOuterProperties$InnerEach
```
java:
```

Failed to inject value for field [nested] of class: io.micronaut.inject.foreach.NestedFieldProperties$InnerEach

Message: Error resolving field value [outer-field-nested.inner.joe.nested]. Property doesn't exist or cannot be converted
Path Taken: NestedFieldProperties.inner --> InnerEach.nested
io.micronaut.context.exceptions.DependencyInjectionException: Failed to inject value for field [nested] of class: io.micronaut.inject.foreach.NestedFieldProperties$InnerEach

Message: Error resolving field value [outer-field-nested.inner.joe.nested]. Property doesn't exist or cannot be converted
Path Taken: NestedFieldProperties.inner --> InnerEach.nested
	at io.micronaut.context.AbstractBeanDefinition.getValueForField(AbstractBeanDefinition.java:1258)
	at io.micronaut.context.BeanDefinitionDelegate.build(BeanDefinitionDelegate.java:143)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1889)
	at io.micronaut.context.DefaultBeanContext.addCandidateToList(DefaultBeanContext.java:2964)
	at io.micronaut.context.DefaultBeanContext.getBeansOfTypeInternal(DefaultBeanContext.java:2875)
	at io.micronaut.context.DefaultBeanContext.getBeansOfType(DefaultBeanContext.java:1040)
	at io.micronaut.context.AbstractBeanDefinition.getValueForField(AbstractBeanDefinition.java:1240)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1889)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:2638)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2624)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2296)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2270)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:728)
	at io.micronaut.inject.foreach.EachPropertySpec.test field injection eachproperty nested inner class of config props(EachPropertySpec.groovy:484)
```

It can't resolve the properties when they are double nested: https://github.com/micronaut-projects/micronaut-core/blob/master/inject/src/main/java/io/micronaut/context/DefaultApplicationContext.java#L264-L278 the properties don't resolve to anything so it falls through. 

![image](https://user-images.githubusercontent.com/854359/90813939-2f73f600-e2dd-11ea-952e-35f5a9f3dbb7.png)

### Example Application

https://github.com/pollend/micronaut-core/commit/e3752a2d86747cab7f1b597f9fd29c17054a77c9

**Comment by dynaxis** [comment] 2021-07-27 06:28
My experience with configurations with nested structure (i.e. nested map and typed object) so far is not so smooth, and I hope to see the experience enhanced.

For instance, is there something wrong in expecting the following is filled correctly. If there are some reasons for not working so, please let me know too. I hope to understand what's the rationale behind.

Thanks.

```kotlin
@ConfigurationProperties("config")
interface Config {
  val map: Map<String, Inner>

  interface Inner {
    val a: Int
    val b: String
  }
} 
```

with the following config?

```hocon
config {
  map {
    a {
      a = 10
      b = hello
    }
    b {
      a = 11
      b = world
    }
  }
}
```

**Comment by jameskleeh** [comment] 2021-07-27 14:49
@dynaxis If you think you've found a bug the best thing is to create a new issue

**Comment by dynaxis** [comment] 2021-07-27 15:35
@jameskleeh Thank you for leaving the comment. The code above doesn't work (as you know) and I guess it's an intended behavior.

I got stuck with such cases where things are not working as "I" expected, searched for how the other users think, found a few questions and issues similar to mine in essence, and am thinking why this nested typed configuration object is so difficult to bend.

If I change `val map: Map<String, Inner>` to `val map: Map<String, Any>`, the map at least reflects all of the configuration. I know that I can write a `TypeConverter` to convert a map into an `Inner` instance to get the original code above working, but guess having a default `TypeConverter` or so for binding properties to the corresponding Java properties would serve majority of Micronaut users' need out of the box.

But I'm not sure if there has been any previous concern on implementing such behavior. If you think it's reasonable to make the above code work out of the box, please let me know. I'll create a seprate issue for discussion.

I think this issue is also in the same vein. That's why I originally chose to add a comment to this issue instead of creating a new one (sorry if it's inappropriate).

Thanks again.

**Comment by jameskleeh** [comment] 2021-07-27 16:14
@dynaxis I do think it should work. I'm not sure why it doesn't. Jackson is responsible for doing the binding in this case. See JacksonBeanPropertyBinder. For some reason `objectMapper.readValue` doesn't work as I would expect

**Comment by dynaxis** [comment] 2021-07-27 16:23
@jameskleeh Thanks a lot. I'll have a look at the relevant code and file an issue if required.

**Comment by graemerocher** [comment] 2022-11-15 11:22
Fixed by https://github.com/micronaut-projects/micronaut-core/commit/dd7f7ad4be51de420d7f795a8f7e2388918ce1f1

**Closed by graemerocher** 2022-11-15 11:22 UTC
Labels: type: improvement
