### ISSUE TITLE
[Feature] Support for new Kotlin inline classes as parameters and return values on @Transactional  

### ISSUE THREAD

**Issue by fromlabs** [micronaut-projects/micronaut-core#5290] opened 2021-04-22 06:55 UTC
Inline classes will become Stable in Kotlin 1.5.0, [docs](https://kotlinlang.org/docs/inline-classes.html) and [issue](https://youtrack.jetbrains.com/issue/KT-42434?_ga=2.60359598.242708355.1619072955-1227836125.1619072955), and they are very useful in domain modeling and DDD ([primitive obsession](https://www.jamesshore.com/v2/blog/2005/primitiveobsession)):
```kotlin
inline class CustomerId(val id: Long) {
    init {
        require(id > 0) { "Id should be positive" }
    }
}

inline class PersonName(val name: String) {
    init {
        require(name.isNotBlank()) { "Name should not be blank" }
    }
}

@Singleton
@Transactional
open class CustomerService {

    // intercepted
    open fun save(name: String): Long {
        TODO()
    }

    // not intercepted
    open fun saveWithInlineClassReturn(name: PersonName): CustomerId {
        TODO()
    }

    // not intercepted
    open fun saveWithInlineClassParameter(id: CustomerId, name: PersonName) {
        TODO()
    }
}
```

I found this [closed issue](https://github.com/micronaut-projects/micronaut-core/issues/1792#issuecomment-508764559), but I think inline classes implementation is changed a lot and maybe you might reconsider to support them.

**Comment by graemerocher** [comment] 2021-04-22 16:01
Probably would require a native Kotlin compiler or migration to KSP

**Comment by KarlHakanNordgren** [comment] 2022-04-26 18:23
I'm also interested in the above. Any updates @graemerocher / @jameskleeh ?

**Comment by jameskleeh** [comment] 2022-04-27 00:24
@KarlHakanNordgren No progress on this specific issue but I'm hoping for KSP support to be available as a preview feature in the not too distant future

**Comment by KarlHakanNordgren** [comment] 2022-04-27 10:13
@jameskleeh : Ok thanks!

**Comment by andydenk** [comment] 2022-11-29 16:46
Are there any updates on this issue?

I stumbled upon a seemingly similar issue using the `io.micronaut.tracing.annotation` `@NewSpan` and an inline class like the Kotlin `Result` as a return type:
```kotlin
@Singleton
open class NotificationService {

    @NewSpan // No Span is created
    open fun notify(): Result<Unit> {
        return Result.success(Unit)
    }
}
```
The annotation is ignored and the related Interceptor is never called.   
This issue appears for all inline classes.

As already pointed out in [this closed issue](https://github.com/micronaut-projects/micronaut-core/issues/1792#issuecomment-508764559), this is probably caused by [Mangling](https://github.com/Kotlin/KEEP/blob/master/proposals/inline-classes.md#mangling) and thus we can use  `@JvmName` for the annotated method as a workaround.
```kotlin
@Singleton
open class NotificationService {

    @Suppress("INAPPLICABLE_JVM_NAME")
    @JvmName("notify")
    @NewSpan // A new Span is created as expected
    open fun notify(): Result<Unit> {
        return Result.success(Unit)
    }
}
```
With the `@JvmName` specified, the snippet works like expected. 

Version:
Micronaut: 3.7.4
Kotlin: 1.7.21
Dependency: `io.micronaut.tracing:micronaut-tracing-opentelemetry-http`

Is there a Fix for this or a better Workaround that I am not aware of?

**Comment by graemerocher** [comment] 2022-11-29 21:53
until we implement the KSP compiler backend probably not

**Comment by andydenk** [comment] 2022-11-30 08:32
@graemerocher Ok thank you!

**Closed as completed** 2023-08-15 11:48 UTC
Labels: lang: kotlin, relates-to: native-kotlin
