### ISSUE TITLE
After upgrade to Mn 3.0.0-M1/2 -> NonUniqueBeanException

### ISSUE THREAD

**Issue by martisaw** [micronaut-projects/micronaut-core#5639] opened 2021-06-22 13:52 UTC
### Discussed in https://github.com/micronaut-projects/micronaut-core/discussions/5636

<div type='discussions-op-text'>

<sup>Originally posted by **martisaw** June 22, 2021</sup>
Hi,

we ([micronaut-camunda-bpm project](https://github.com/NovatecConsulting/micronaut-camunda-bpm)) want to upgrade to the newest Milestone-Release of Micronaut. However, we discovered that some tests are now throwing NonUniqueBeanExceptions. 

We want to retrieve Beans (where we don't know the type yet) from the applicationContext with `applicationContext.getBean(Object.class, Qualifiers.byName(".."));`
Using Micronaut 2.5.x, this worked fine. With 3.0.0-M1 and M2, we are getting the following error message: `Multiple possible bean candidates found: [com.example.SampleSingleton, io.micronaut.context.BeanProvider, jakarta.inject.Provider]`

From our point of view this is an unwanted change of behaviour. From an application developer point of view it is strange that the BeanProviders and Providers inherit the qualifier. What do you think?

See here for a sample project: https://github.com/martisaw/mn-nonUniqueBean</div>

### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create Sample Project with Micronaut Launch
2. Add an empty singleton and add `@Named("Sample")` 
3. Try to get the bean from the ApplicationContext e.g. within a test with `applicationContext.getBean(Object.class, Qualifiers.byName("Sample"));`

### Expected Behaviour

The bean should be found.

### Actual Behaviour

A NonUniqueBeanException is thrown.

### Environment Information

- **Operating System**: Windows 10
- **Micronaut Version:** 3.0.0-M2
- **JDK Version:** 16

### Example Application

- https://github.com/martisaw/mn-nonUniqueBean

**Comment by ilopmar** [comment] 2021-06-23 15:20
It seems this issue is fixed in #5646 which is already merged. I've tried that snapshot locally in micronaut-mqtt and it fails with the same error `NonUniqueBeanException: Multiple possible bean candidates found` error.

To reproduce it use the branch in this PR https://github.com/micronaut-projects/micronaut-mqtt/pull/84 (replace Micronaut 3.0.0-M2 version with snapshot) and run the tests.

The error:

```
  Message: Multiple possible bean candidates found: [io.micronaut.runtime.context.CompositeMessageSource, io.micronaut.discovery.config.DefaultCompositeConfigurationClient, io.micronaut.jackson.bind.JacksonBeanPropertyBinder, io.micronaut.http.ssl.DefaultSslConfiguration$DefaultKeyStoreConfiguration, com.fasterxml.jackson.databind.ObjectMapper, io.micronaut.runtime.ApplicationConfiguration, io.micronaut.http.ssl.DefaultSslConfiguration$DefaultKeyConfiguration, java.util.concurrent.ThreadFactory, io.micronaut.discovery.DefaultCompositeDiscoveryClient, io.micronaut.scheduling.DefaultTaskExceptionHandler, io.micronaut.context.DefaultApplicationContext$RuntimeConfiguredEnvironment, io.micronaut.http.codec.MediaTypeCodecRegistry, io.micronaut.mqtt.exception.DefaultMqttSubscriberExceptionHandler, io.micronaut.http.ssl.DefaultSslConfiguration, io.micronaut.scheduling.ScheduledExecutorTaskScheduler, io.micronaut.http.ssl.DefaultSslConfiguration$DefaultTrustStoreConfiguration]
  Path Taken: MqttAsyncClient.disconnect([Object userContext],MqttActionListener callback)
        at io.micronaut.context.AbstractBeanDefinition.getBeanForMethodArgument(AbstractBeanDefinition.java:1924)
        at io.micronaut.context.AbstractBeanDefinition.getBeanForMethodArgument(AbstractBeanDefinition.java:939)
        at io.micronaut.mqtt.v5.client.$MqttClientFactory$MqttClient0Definition.dispose(Unknown Source)
        at io.micronaut.inject.DisposableBeanDefinition.dispose(DisposableBeanDefinition.java:44)
        at io.micronaut.context.DefaultBeanContext$BeanDisposingRegistration.close(DefaultBeanContext.java:4272)
        at io.micronaut.context.DefaultBeanContext.disposeBean(DefaultBeanContext.java:1180)
        ... 115 common frames omitted
  Caused by: io.micronaut.context.exceptions.NonUniqueBeanException: Multiple possible bean candidates found: [io.micronaut.runtime.context.CompositeMessageSource, io.micronaut.discovery.config.DefaultCompositeConfigurationClient, io.micronaut.jackson.bind.JacksonBeanPropertyBinder, io.micronaut.http.ssl.DefaultSslConfiguration$DefaultKeyStoreConfiguration, com.fasterxml.jackson.databind.ObjectMapper, io.micronaut.runtime.ApplicationConfiguration, io.micronaut.http.ssl.DefaultSslConfiguration$DefaultKeyConfiguration, java.util.concurrent.ThreadFactory, io.micronaut.discovery.DefaultCompositeDiscoveryClient, io.micronaut.scheduling.DefaultTaskExceptionHandler, io.micronaut.context.DefaultApplicationContext$RuntimeConfiguredEnvironment, io.micronaut.http.codec.MediaTypeCodecRegistry, io.micronaut.mqtt.exception.DefaultMqttSubscriberExceptionHandler, io.micronaut.http.ssl.DefaultSslConfiguration, io.micronaut.scheduling.ScheduledExecutorTaskScheduler, io.micronaut.http.ssl.DefaultSslConfiguration$DefaultTrustStoreConfiguration]
        at io.micronaut.context.DefaultBeanContext.findConcreteCandidate(DefaultBeanContext.java:2389)
        at io.micronaut.context.DefaultApplicationContext.findConcreteCandidate(DefaultApplicationContext.java:451)
        at io.micronaut.context.DefaultBeanContext.lastChanceResolve(DefaultBeanContext.java:3215)
        at io.micronaut.context.DefaultBeanContext.findConcreteCandidateNoCache(DefaultBeanContext.java:3102)
        at io.micronaut.context.DefaultBeanContext.findConcreteCandidate(DefaultBeanContext.java:3016)
        at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2702)
        at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1562)
        at io.micronaut.context.AbstractBeanDefinition.getBeanForMethodArgument(AbstractBeanDefinition.java:1903)
        ... 120 common frames omitted
```

**Comment by graemerocher** [comment] 2021-06-23 15:30
This seems to be a different bug. It is trying to dependency inject the `disconnect` method. I am not convinced this is a bug in Micronaut 3.0 in fact and may have just worked in chance. Either way report a different issue.

**Closed as completed** 2021-06-23 15:30 UTC
Labels: type: bug, status: pr submitted

**Comment by tobiasschaefer** [comment] 2021-06-24 04:38
Thanks @graemerocher for that fast fix!

I'm working together with @martisaw on the same project and can confirm that updating to the current 3.0.0-SNAPSHOT fixes the issue he reported.

**Comment by jameskleeh** [comment] 2021-06-24 04:48
@tobiasschaefer Thanks for trying out the milestones! You have played a role in making the release better
