### ISSUE TITLE
Micronaut Controller not handling Type Erasure with Jackson

### ISSUE THREAD

**Issue by chantrybjss** [micronaut-projects/micronaut-core#510] opened 2018-08-20 08:47 UTC
Example

https://github.com/chantrybjss/testing/tree/master/starter/src/main/java/starter

### Steps to Reproduce

Run the above example.

It seems that the Micronaut controller is unable to deal with type erasure with Jackson. 

I am using a polymorphic deserialization on my Exercise object which works through metadata introduced in annotations. If I return an instance of Exercise, Micronaut will properly serialize with a type property in the resulting JSON. However, if I wrap my class with something like an Iterable, or an Optional, or a List, etc., then Micronaut loses the type information and the type field disappears. In my test directory, this causes the deserialization to fail as it is missing the type information that should have been produced during serialization.

If I were to use vanilla Jackson, the solution would be to do something like the following.
```
new ObjectMapper().writerFor(new TypeReference<Iterable<Exercise>>(){}).writeValueAsString(exercises);
```

### Expected Behaviour

Micronaut should handle the above for me or otherwise provide me with a mechanism to supply a TypeReference.

### Environment Information

- **Operating System**: Windows 10
- **Micronaut Version:** 1.0.0.M4
- **JDK Version:** 10

**Comment by chantrybjss** [comment] 2018-08-20 16:52
I have been playing with micronaut and RxJava a little bit more. It seems the Flowable type serves my purpose for this particular use case.

For example, I could simply change my method to the following.

```
@Override
public Flowable<Exercise> exercises()  {
    return Flowable.fromIterable(exerciseService.getAllExercises());
}
```
However, I still feel this is a significant limitation of the API. Ideally, users would be able to serialize objects of any generic type complexity. Spring for example would handle this without any trouble.

**Comment by graemerocher** [comment] 2018-08-29 13:44
Can you provide a simple example that reproduces this issue? The referenced example isn't clear to me

**Comment by chantrybjss** [comment] 2018-08-29 14:00
I can and will when I have some time.

For now, I will simply clarify my use case. There is something called polymorphic deserialization in Jackson, which allows you to declare a super type and then serialize subtypes with an included field which indicates which subtype produced the JSON. The serialized JSON can then be deserialized. 

```
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "type")
@JsonSubTypes({
    @JsonSubTypes.Type(value=SomeSubClass.class, name="SubClass")
})
public abstract class SomeSuperType {
....
}
```

```
public class SomeSubClass extends SomeSuperType { ... }```

If you setup any polymorphic class and return it from a controller in Micronaut, it will properly serialize and deserialize it. 

```
@Get("/something")
SomeSuperType getSomething() { ... }
```

However, if you were to wrap the above in say a List (or some other object), then due to type erasure the Micronaut controller will fail.

```
@Get("/something")
List<SomeSuperType> getSomething() { ... }
```
Micronaut will serialize the object, but it loses the metadata, so even though the former controller method would return JSON including a type property, the List controller method would not. Therefore, deserialization would fail, as Micronaut failed to include the meta field. 

I'm not exactly sure why this happens, but I feel that it may indicate a deeper issue beyond this particular use case.

**Comment by graemerocher** [comment] 2018-10-09 12:41
Closing due to lack of sample, if you come up with one let us know

**Closed by graemerocher** 2018-10-09 12:41 UTC
Labels: status: awaiting feedback

**Comment by bzolivereckle** [comment] 2020-07-09 15:51
i think i have a use case, cause i stuggle with something similar (micronaut 1.3.6)

```kotlin
@JsonTypeInfo(
        use = JsonTypeInfo.Id.NAME,
        include = JsonTypeInfo.As.PROPERTY,
        property = "type")
@JsonSubTypes(
        value = [
            JsonSubTypes.Type(value = PropertyDouble::class, name = "double"),
            JsonSubTypes.Type(value = PropertyText::class, name = "text")
        ]
)
abstract class Property<T>(
        val id: Long,
        val value: T
) : Serializable {}


@JsonTypeName("double")
class PropertyDouble(
        @JsonProperty("id")
        id: Long,
		@JsonProperty("value")
        value: Double
) : Property<Double>(id, value) {
}

@JsonTypeName("text")
class PropertyText(
        @JsonProperty("id")
        id: Long,
        @JsonProperty("value")
        value: String
) : Property<String>(id, value) {
}
```

Results in 
```json
[
	{
		"id": 18573007,
		"value": 31.0
	},
	{
		"id": 18573026,
		"value": 44.7
	},
	{
		"id": 18573038,
		"value": 51.7
	}
]
```
but i expect

```json
[
	{
		"id": 18573007,
		"value": 31.0,
		"type": "double"
	},
	{
		"id": 18573026,
		"value": 44.7,
		"type": "double"
	},
	{
		"id": 18573038,
		"value": 51.7,
		"type": "double"
	}
]
```

**Comment by autocast** [comment] 2023-02-06 14:48
I just tried this on 3.8.3 and polymorphic deserialisation in a List worked fine for me.
