### ISSUE TITLE
UndeliverableException in stderr

### ISSUE THREAD

**Issue by VojtechMucha** [micronaut-projects/micronaut-core#2971] opened 2020-03-24 14:33 UTC
### Steps to Reproduce

1. Download example application: `git clone https://github.com/VojtechMucha/micronaut-rxjava-stacktrace.git`
2. Execute test: `gw test`
3. Check console output for `io.reactivex.exceptions.UndeliverableException`

### Expected Behaviour

This (or very similar) issue was already reported as https://github.com/micronaut-projects/micronaut-core/issues/1799. As Graeme Rocher mentioned there: _It should never arrive to point of calling RxJavaPlugins.onError()_. But it currently happens.

### Actual Behaviour

Following exception is printed into stderr
```
    io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | io.micronaut.http.client.exceptions.HttpClientException: Connect Error: connection timed out: www.google.com/172.217.23.196:81
        at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
        at io.reactivex.internal.operators.flowable.FlowableCreate$BaseEmitter.onError(FlowableCreate.java:275)
        at io.micronaut.http.client.DefaultHttpClient.lambda$null$27(DefaultHttpClient.java:1056)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:570)
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:549)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
        at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
        at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:608)
        at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:263)
        at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
        at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.micronaut.scheduling.instrument.InvocationInstrumenterWrappedRunnable.run(InvocationInstrumenterWrappedRunnable.java:48)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)
    Caused by: io.micronaut.http.client.exceptions.HttpClientException: Connect Error: connection timed out: www.google.com/172.217.23.196:81
        at io.micronaut.http.client.DefaultHttpClient.lambda$null$27(DefaultHttpClient.java:1057)
        ... 18 more
    Caused by: io.netty.channel.ConnectTimeoutException: connection timed out: www.google.com/172.217.23.196:81
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:261)
        ... 10 more
    Exception in thread "nioEventLoopGroup-1-4" io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | io.micronaut.http.client.exceptions.HttpClientException: Connect Error: connection timed out: www.google.com/172.217.23.196:81
        at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
        at io.reactivex.internal.operators.flowable.FlowableCreate$BaseEmitter.onError(FlowableCreate.java:275)
        at io.micronaut.http.client.DefaultHttpClient.lambda$null$27(DefaultHttpClient.java:1056)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:570)
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:549)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
        at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
        at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:608)
        at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:263)
        at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
        at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.micronaut.scheduling.instrument.InvocationInstrumenterWrappedRunnable.run(InvocationInstrumenterWrappedRunnable.java:48)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)
    Caused by: io.micronaut.http.client.exceptions.HttpClientException: Connect Error: connection timed out: www.google.com/172.217.23.196:81
        at io.micronaut.http.client.DefaultHttpClient.lambda$null$27(DefaultHttpClient.java:1057)
        ... 18 more
    Caused by: io.netty.channel.ConnectTimeoutException: connection timed out: www.google.com/172.217.23.196:81
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:261)
        ... 10 more
```

### Environment Information

- **Operating System**: macOS 10.14.6
- **Micronaut Version:** 1.3.2
- **JDK Version:** openjdk version 11.0.2

### Example Application

https://github.com/VojtechMucha/micronaut-rxjava-stacktrace

**Comment by graemerocher** [comment] 2020-03-24 14:39
Think this is probably fixed in `2.0.0.M1`.. need to verify

**Comment by graemerocher** [comment] 2020-04-15 10:22
Not fixed in Micronaut 2.0... seems to be Reactor is cancelling the subscription which prevents reporting downstream errors. Unsure if the problem is in the Reactor library

**Comment by mutyasaisrikar** [comment] 2021-07-08 20:32
@graemerocher, We are also facing the same issue in production. Any update on this fix?

**Comment by mattmoss** [comment] 2021-08-04 01:58
When the timeout occurs, the `onErrorResumeNext` lambda first replaces the current subscription with `Flowable.error` at this line, cancelling the current subscription:
https://github.com/micronaut-projects/micronaut-core/blob/3bb62e3ea3e4ec18254d25d67b258fade511ee91/http-client/src/main/java/io/micronaut/http/client/netty/DefaultHttpClient.java#L1181

After that, the `ConnectionFuture` above calls `emitter.onError` here:
https://github.com/micronaut-projects/micronaut-core/blob/3bb62e3ea3e4ec18254d25d67b258fade511ee91/http-client/src/main/java/io/micronaut/http/client/netty/DefaultHttpClient.java#L1145

But that emitter is from the now-cancelled subscription... `emitter.onError` triggers the `UndeliverableException`.

Apologies if you've already analyzed beyond this, or if I'm incorrect here.

**Closed** 2021-08-17 16:57 UTC
Labels: status: awaiting validation, priority: high
