### ISSUE TITLE
Newly generated kotlin app with hibernate reactive crashes instantly

### ISSUE THREAD

**Issue by mengu** [micronaut-projects/micronaut-core#9706] opened 2023-08-13 11:33 UTC
### Expected Behavior

The generated app shouldn't crash. I've tried with generating the Java version and that one works perfectly fine.

### Actual Behaviour

Run `./gradlew run` for the first time and you get:

```
[test-resources-service] 13:28:10.786 [ForkJoinPool.commonPool-worker-9] INFO  i.m.t.e.TestResourcesResolverLoader - Loaded 3 test resources resolvers: io.micronaut.testresources.hibernate.reactive.postgresql.HibernateReactivePostgreSQLTestResourceProvider, io.micronaut.testresources.postgres.PostgreSQLTestResourceProvider, io.micronaut.testresources.testcontainers.GenericTestContainerProvider

> Task :kspKotlin FAILED
e: [ksp] java.lang.NullPointerException
        at io.micronaut.kotlin.processing.visitor.AbstractKotlinElement.newClassElement(AbstractKotlinElement.kt:527)
        at io.micronaut.kotlin.processing.visitor.AbstractKotlinElement.newClassElement$default(AbstractKotlinElement.kt:507)
        at io.micronaut.kotlin.processing.visitor.AbstractKotlinElement.newClassElement(AbstractKotlinElement.kt:483)
        at io.micronaut.kotlin.processing.visitor.KotlinPropertyElement$resolvedType$2.invoke(KotlinPropertyElement.kt:48)
        at io.micronaut.kotlin.processing.visitor.KotlinPropertyElement$resolvedType$2.invoke(KotlinPropertyElement.kt:47)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at io.micronaut.kotlin.processing.visitor.KotlinPropertyElement.getResolvedType(KotlinPropertyElement.kt:47)
        at io.micronaut.kotlin.processing.visitor.AbstractKotlinPropertyElement.getType(AbstractKotlinPropertyElement.kt:97)
        at io.micronaut.kotlin.processing.visitor.KotlinPropertyGetterMethodElement.<init>(KotlinPropertyGetterMethodElement.kt:56)
        at io.micronaut.kotlin.processing.visitor.KotlinPropertyGetterMethodElement.<init>(KotlinPropertyGetterMethodElement.kt:47)
        at io.micronaut.kotlin.processing.visitor.KotlinPropertyElement$getter$2$1.invoke(KotlinPropertyElement.kt:81)
        at io.micronaut.kotlin.processing.visitor.KotlinPropertyElement$getter$2$1.invoke(KotlinPropertyElement.kt:80)
        at io.micronaut.kotlin.processing.visitor.KotlinPropertyElement$getter$2.invoke$lambda$0(KotlinPropertyElement.kt:80)
        at java.base/java.util.Optional.map(Optional.java:260)
        at io.micronaut.kotlin.processing.visitor.KotlinPropertyElement$getter$2.invoke(KotlinPropertyElement.kt:80)
        at io.micronaut.kotlin.processing.visitor.KotlinPropertyElement$getter$2.invoke(KotlinPropertyElement.kt:78)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at io.micronaut.kotlin.processing.visitor.KotlinPropertyElement.getGetter(KotlinPropertyElement.kt:78)
        at io.micronaut.kotlin.processing.visitor.AbstractKotlinPropertyElement$internalAnnotationMetadata$2.invoke(AbstractKotlinPropertyElement.kt:57)
        at io.micronaut.kotlin.processing.visitor.AbstractKotlinPropertyElement$internalAnnotationMetadata$2.invoke(AbstractKotlinPropertyElement.kt:54)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at io.micronaut.kotlin.processing.visitor.AbstractKotlinPropertyElement.getInternalAnnotationMetadata(AbstractKotlinPropertyElement.kt:54)
        at io.micronaut.kotlin.processing.visitor.AbstractKotlinPropertyElement.getAnnotationMetadata(AbstractKotlinPropertyElement.kt:87)
        at io.micronaut.kotlin.processing.visitor.AbstractKotlinPropertyElement.getAnnotationMetadata(AbstractKotlinPropertyElement.kt:32)
        at io.micronaut.core.annotation.AnnotationMetadataDelegate.hasAnnotation(AnnotationMetadataDelegate.java:514)
        at io.micronaut.kotlin.processing.visitor.KotlinClassElement$declaredNativeProperties$2$3.invoke(KotlinClassElement.kt:132)
        at io.micronaut.kotlin.processing.visitor.KotlinClassElement$declaredNativeProperties$2$3.invoke(KotlinClassElement.kt:132)
        at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:171)
        at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
        at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:787)
        at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:817)
        at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:808)
        at io.micronaut.kotlin.processing.visitor.KotlinClassElement$declaredNativeProperties$2.invoke(KotlinClassElement.kt:133)
        at io.micronaut.kotlin.processing.visitor.KotlinClassElement$declaredNativeProperties$2.invoke(KotlinClassElement.kt:121)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at io.micronaut.kotlin.processing.visitor.KotlinClassElement.getDeclaredNativeProperties(KotlinClassElement.kt:121)
        at io.micronaut.kotlin.processing.visitor.KotlinClassElement.getDeclaredSyntheticBeanProperties(KotlinClassElement.kt:289)
        at io.micronaut.kotlin.processing.visitor.KotlinClassElement.access$getDeclaredSyntheticBeanProperties(KotlinClassElement.kt:38)
        at io.micronaut.kotlin.processing.visitor.KotlinClassElement$nativeProperties$2.invoke(KotlinClassElement.kt:115)
        at io.micronaut.kotlin.processing.visitor.KotlinClassElement$nativeProperties$2.invoke(KotlinClassElement.kt:109)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at io.micronaut.kotlin.processing.visitor.KotlinClassElement.getNativeProperties(KotlinClassElement.kt:109)
        at io.micronaut.kotlin.processing.visitor.KotlinClassElement.getSyntheticBeanProperties(KotlinClassElement.kt:287)
        at io.micronaut.kotlin.processing.visitor.TypeElementSymbolProcessor$ElementVisitor.visitMembers(TypeElementSymbolProcessor.kt:279)
        at io.micronaut.kotlin.processing.visitor.TypeElementSymbolProcessor$ElementVisitor.visitClassDeclaration(TypeElementSymbolProcessor.kt:261)
        at com.google.devtools.ksp.symbol.impl.kotlin.KSClassDeclarationImpl.accept(KSClassDeclarationImpl.kt:136)
        at io.micronaut.kotlin.processing.visitor.TypeElementSymbolProcessor.process(TypeElementSymbolProcessor.kt:124)
        at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$6$1.invoke(KotlinSymbolProcessingExtension.kt:291)
        at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$6$1.invoke(KotlinSymbolProcessingExtension.kt:289)
        at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.handleException(KotlinSymbolProcessingExtension.kt:394)
        at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.doAnalysis(KotlinSymbolProcessingExtension.kt:289)
        at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerFacadeForJVM.kt:123)
        at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration$default(TopDownAnalyzerFacadeForJVM.kt:99)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:257)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:42)
        at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:115)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:248)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:88)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli$default(KotlinToJVMBytecodeCompiler.kt:47)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:168)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:53)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:100)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:46)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:101)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1486)
        at jdk.internal.reflect.GeneratedMethodAccessor141.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:360)
        at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
        at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
        at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:587)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:828)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:705)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:704)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)

e: Error occurred in KSP, check log for detail
[test-resources-service] 13:28:11.160 [main] INFO  i.m.t.server.TestResourcesService - A Micronaut Test Resources server is listening on port 59040, started in 610ms

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':kspKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.2.1/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD FAILED in 3s
3 actionable tasks: 3 executed
```

### Steps To Reproduce

1. Create app with: `mn create-app --build=gradle --jdk=17 --lang=kotlin --test=junit --features=openapi,serialization-jackson,postgres,flyway,graalvm,jib,data-hibernate-reactive co.myapp.myapp`
2. Update application.properties for db connectivity
3. Create a basic model:
```
package co.hangman.domain

import jakarta.persistence.Column
import jakarta.persistence.Entity
import jakarta.persistence.Table


@Entity
@Table(name = "users")
data class User(
    @Id
    val id: UUID,

    @Column(unique = true)
    val username: String

)
```
4. Run `./gradlew run`

### Environment Information

- Operating System: macOS 13.5
- JDK: 17
- Kotlin: 1.8.22
- Micronaut: 4.0.3

### Version

4.0.3

**Comment by wetted** [comment] 2023-08-14 20:00
@mengu can you provide an example project that demonstrates this? I created an example app per your instructions, but it works without crashing.

What changes did you make for "Update application.properties for db connectivity"?

**Comment by sdelamo** [comment] 2023-08-24 10:21
I am closing this issue because I am unable to reproduce it. I followed your steps. I did not do anything in `Update application.properties for db connectivity` since I delegated to Micronaut Test Resources.

**Closed as completed by sdelamo** 2023-08-24 10:21 UTC
Labels: status: awaiting feedback
