### ISSUE TITLE
Project fails to compile with Java 11 module, micronaut 1.2.3 and gradle 5.6.2

### ISSUE THREAD

**Issue by chrispoulsen** [micronaut-projects/micronaut-core#2232] opened 2019-10-15 12:28 UTC
Hi, I'm trying to create a simple application with Java 11 and modules (module-info.java present). I'm having a hard time getting things to compile, as soon as I add:     

```
annotationProcessor(platform("io.micronaut:micronaut-bom:$micronautVersion"))
annotationProcessor("io.micronaut:micronaut-inject-java")
```

to my gradle project, then the build fails with:

```
> Task :app.runner:compileJava FAILED                              
                                                                   
FAILURE: Build failed with an exception.                           
                                                                   
* What went wrong:                                                 
Execution failed for task ':app.runner:compileJava'.               
> java.lang.IllegalArgumentException: Unexpected element app.runner
```

The environment is Java 11, Gradle 5.6.2 and Micronaut 1.2.3. The --stacktrace and --debug options does not tell me anything useful.

The module is named "app.runner" - and if I change the module name, the error changes accordingly. If I add the lombok annotation processor instead, the build also seems to work.

I asked on Gitter and Graeme Rocher pointed me to a working project (https://github.com/weiqigao/micronaut-test-modules-issue).

That sample project is running on my system after adding a gradle 5.6.2 wrapper and still using Java 11. 
However when I bump the micronaut version in the sample project from 1.1.0 to 1.2.3 the compileJava task fails again with the same "unexpected element <module-name>" error as I see in my project.

**Comment by graemerocher** [comment] 2019-10-16 10:40
This seems to be a Gradle bug to me. The stack trace is coming from Gradle's incremental compilation APIs

**Comment by graemerocher** [comment] 2019-10-16 10:45
Reported https://github.com/gradle/gradle/issues/11059

**Comment by graemerocher** [comment] 2019-10-16 10:45
I recommend using Maven until this is resolved in the Gradle side

**Comment by bademux** [comment] 2019-10-24 11:45
It is interesting that build works with micronaut 1.2.1, but broken with 1.2.2
tested with https://github.com/msgilligan/micronaut-examples/tree/msgilligan-cli-app-modular-java/cli-app-modular-java

**Comment by graemerocher** [comment] 2019-10-24 11:58
Yes the root cause is that we added support for Gradle incremental annotation processors in 1.2.2 to remove warnings that Kotlin emits when non-incremental annotation processors are present.

However Gradle's support for incremental annotation processors is broken with modules. Hence https://github.com/gradle/gradle/issues/11059

**Comment by bademux** [comment] 2019-10-24 12:11
Thanks for clarification!
 Will it help to disable incremental annotation processors and is there easy way to do it?

**Comment by graemerocher** [comment] 2019-10-24 12:23
not that I am aware, but we should probably make it possible. Dagger allows you to disable it.

**Comment by graemerocher** [comment] 2019-10-24 12:23
Alternative is to switch to Maven

**Comment by msgilligan** [comment] 2019-11-04 20:48
> Alternative is to switch to Maven

Or stick with earlier versions of Micronaut.

**Comment by msgilligan** [comment] 2019-11-04 21:21
I tried it with Gradle 6.0 RC2 and the same problem occurs.

**Comment by msgilligan** [comment] 2020-01-31 00:55
@graemerocher says the Gradle issue is fixed in Gradle 6.1: https://github.com/gradle/gradle/issues/11059#issuecomment-580358363

I just updated my project that was failing with Micronaut 1.2.2+ to Gradle 6.1.1 and Micronaut 1.2.10 and it builds and runs successfully.

**Closed** 2020-01-31 06:32 UTC
Labels: status: awaiting third-party, type: bug
