### ISSUE TITLE
Broken documentation in configuration reference to  DefaultTrustStoreConfiguration

### ISSUE THREAD

**Issue by pgressa** [micronaut-projects/micronaut-core#5793] opened 2021-07-20 15:17 UTC
in the reference doc https://docs.micronaut.io/latest/guide/configurationreference.html

**Comment by jameskleeh** [comment] 2021-08-19 14:36
@sdelamo Were you able to track this down?

**Comment by ilopmar** [comment] 2021-08-19 15:46
I think the problem is fixed in the build plugins 4.0.1 version.

**Closed as completed** 2021-08-19 19:25 UTC
Labels: type: docs

**Comment by sdelamo** [comment] 2021-08-20 05:54
I added this fix to 4.0.1 https://github.com/micronaut-projects/micronaut-build/pull/182
