### ISSUE TITLE
RequestBean support for declarative Client

### ISSUE THREAD

**Issue by dchuiko** [micronaut-projects/micronaut-core#3879] opened 2020-08-07 13:46 UTC
This improvement is about `@RequestBean` feature. It would be great if `@RequestBean` parameters like `@QueryParams`, `@Header`, `@PathVariables` would be handled for declarative `@Client`. This improvement supports а single interface for Controller and Client feature. 

Before writing an issue I've got a preliminary approve from @jameskleeh. See Gitter discussion here: [1](https://gitter.im/micronautfw/questions?at=5f2d5651e20413052e70cf9c), [2](https://gitter.im/micronautfw/questions?at=5f2d5614fe39ca5d658887f8), [3](https://gitter.im/micronautfw/questions?at=5f2d038eb103e45c83ff9cb4)

I will demonstrate the problem below.

### Steps to Reproduce
Create RequestBean class, Contoller operation interface, Controller, and declarative client like the following:

```
@Introspected
@Data
public class PetParams {
   @QueryValue String name;
   @QueryValue Integer age;
    // the rest of POJO ommited
}

public interface PetOperations {
    @Get
    Single<Pet> search(@RequestBean PetParams params);
}

@Controller("/pets")
public class PetController implements PetOperations {
    @Override
    public Single<Pet> seach(PetParams params) {
       …       
    }
}

@Client(“/pets”)
public interface PetsClient extends PetOperations
```

Create `@MicronautTest` and try to invoke `@Controller` using declarative `@Client`.

```
@Inject PetsClient petsClient;
…
petsClient.search(new PetParams(“Name”, 4)); // doesn’t not send query parameters
```

### Expected Behaviour

`@RequestBean` parameters like `@QueryParams`, `@Header`, `@PathVariables` are present in an HTTP request from `@Client`

### Actual Behaviour

Only URL is present in an HTTP request from `@Client`

### Environment Information

- **Operating System**: MacOS 10.15.6
- **Micronaut Version:** 2.0.1
- **JDK Version:** 11

**Comment by TorosyanV** [comment] 2020-12-04 13:40
I'm also trying to use @PathVariable with @RequestBean, but seems it's not supported. I don't have any errors, but from logs I can see that PathVariable has not been set in request url.

**Comment by jameskleeh** [comment] 2020-12-23 16:06
Duplicate of https://github.com/micronaut-projects/micronaut-core/issues/4666

**Closed by jameskleeh** 2020-12-23 16:06 UTC
