### ISSUE TITLE
Computed properties not working with Kotlin data class based @QueryValue

### ISSUE THREAD

**Issue by simondean** [micronaut-projects/micronaut-core#6575] opened 2021-11-26 12:11 UTC
## Expected Behavior

When creating a computed property on a Kotlin data class where the computed property uses a constructor property annotated with @QueryValue, the computed property should be computed correctly

## Actual Behaviour

The computed property sees an uninitialised value for the constructor property it depends on.  

## Steps To Reproduce

1. Create a Kotlin based Micronaut application
2. Add `@Get("/search{?query*}")` to a controller function
3. Add `@QueryValue("query") query: ExampleQuery` as an argument to the controller function
4. Create a Kotlin data class called `ExampleQuery`
5. Add the `@Introspected` to the data class
6. Add a `@field:QueryValue val propertyWithNullDefault: String? = null` constructor property to the data class
7. Add a `val computedProperty = propertyWithNullDefault?.toUpperCase()` computed property to the data class

## Environment Information

Micronaut 3.0.x, 3.1.x and 3.2.x with the default versions of Kotlin that come with those Micronaut versions

## Example Application

https://github.com/simondean/micronaut-kotlin-query-param-object-issue

The [IssueTest](https://github.com/simondean/micronaut-kotlin-query-param-object-issue/blob/main/src/test/kotlin/com/example/IssueTest.kt) test in that repo is designed to show the difference in behaviour between Micronaut 2.x and 3.x (the bug).  The test always passes, as it uses a `when` expression to vary the expected output based on whether it is being ran on Micronaut 2.x or 3.x.  See https://github.com/simondean/micronaut-kotlin-query-param-object-issue/actions for the green builds for the repo.  

## Version

3.0.x, 3.1.x and 3.2.x

**Comment by timyates** [comment] 2022-02-15 17:49
Hiya!

If you remove the default value from `propertyWithNullDefault`, I get the expected result.

This is a duplicate of https://github.com/micronaut-projects/micronaut-core/issues/6534

Due to a change in the behaviour of Kapt https://youtrack.jetbrains.com/issue/KT-47908

Not sure what we can do here, apart from wait until we have an alternative to Kapt

**Closed as completed by timyates** 2022-02-15 17:49 UTC
