### ISSUE TITLE
Multiple file uploads with more than one part

### ISSUE THREAD

**Issue by goeh** [micronaut-projects/micronaut-core#10578] opened 2024-03-06 08:33 UTC
### Expected Behavior

Uploading multiple files with different content types should work.

### Actual Behaviour

Trying to upload files in MultiPartBody results in errors.

### Steps To Reproduce

Create a controller with a method
```
@Post(value = "/{+path}", consumes = MediaType.MULTIPART_FORM_DATA, produces = MediaType.APPLICATION_JSON)
public Mono<List<String>> upload(@PathVariable String path,
                                     @Part("file") Publisher<CompletedFileUpload> file,
                                     @Nullable @Part("metadata") Metadata metadata)
return Flux.from(file)
                .subscribeOn(Schedulers.boundedElastic())
                .map(part -> { ... process part ...; return part.getFilename(); })
                .collectList();
```

Then try to upload one or more files:
`curl -vF 'file=@./image1.jpeg' -F 'file=@./image2.jpeg' http://localhost:8080/uploads`

{"_links":{"self":[{"href":"/uploads","templated":false}]},"_embedded":{"errors":[{"message":"Internal Server Error: refCnt: 0, decrement: 1"}]},"message":"Internal Server Error"}%

Uploading multiple files gives another error:

`curl -vF 'file=@./image1.jpeg' -F 'file=@./image2.jpeg' -F 'metadata=@./metadata.json' http://localhost:8080/uploads`

{"_links":{"self":[{"href":"/uploads","templated":false}]},"_embedded":{"errors":[{"message":"Internal Server Error: The mapper [io.micronaut.http.server.netty.binders.NettyPartUploadAnnotationBinder$$Lambda/0x00000008015b9fd0] returned a null value."}]},"message":"Internal Server Error"}%   

### Environment Information

- Operating System: MacOS 14.3.1
- JDK Version: 21.0.2

### Example Application

https://github.com/goeh/micronaut-multiple-file-upload-issue

### Version

4.3.4

**Comment by goeh** [comment] 2024-03-06 08:37
This controller works well with Micronaut 3.10.2 and is currently a blocker for our upgrade to Micronaut 4.x

**Comment by goeh** [comment] 2024-03-06 09:10
If I change the method signature to `Flux<String>` and remove `.collectList()` I get another error.
From the logging I can see that the parts are actually uploaded, but then `IllegalReferenceCountException` is thrown.
```
10:05:56.081 [boundedElastic-1] INFO  micronaut.issue.UploadController - IMG_0726.jpeg uploaded to uploads
10:05:56.082 [boundedElastic-1] INFO  micronaut.issue.UploadController - IMG_0726.jpeg uploaded to uploads
10:05:56.083 [default-nioEventLoopGroup-1-3] WARN  i.m.h.s.n.h.PipeliningServerHandler - Reactive response received an error after some data has already been written. This error cannot be forwarded to the client.
io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
	at io.netty.util.internal.ReferenceCountUpdater.toLiveRealRefCnt(ReferenceCountUpdater.java:83)
	at io.netty.util.internal.ReferenceCountUpdater.release(ReferenceCountUpdater.java:148)
	at io.netty.util.AbstractReferenceCounted.release(AbstractReferenceCounted.java:76)
	at io.micronaut.http.server.netty.multipart.NettyCompletedFileUpload.getInputStream(NettyCompletedFileUpload.java:89)
	at micronaut.issue.UploadController.lambda$upload$0(UploadController.java:32)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:106)
	at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.onNext(FluxSubscribeOn.java:151)
	at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onNext(FluxHandleFuseable.java:194)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableConditionalSubscriber.onNext(FluxPeekFuseable.java:503)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableConditionalSubscriber.onNext(FluxPeekFuseable.java:503)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableConditionalSubscriber.onNext(FluxPeekFuseable.java:503)
	at reactor.core.publisher.FluxContextWriteRestoringThreadLocals$ContextWriteRestoringThreadLocalsSubscriber.onNext(FluxContextWriteRestoringThreadLocals.java:118)
	at reactor.core.publisher.FluxContextWriteRestoringThreadLocals$FuseableContextWriteRestoringThreadLocalsSubscriber.onNext(FluxContextWriteRestoringThreadLocals.java:190)
	at reactor.core.publisher.SinkManyUnicast.drainRegular(SinkManyUnicast.java:284)
	at reactor.core.publisher.SinkManyUnicast.drain(SinkManyUnicast.java:365)
	at reactor.core.publisher.SinkManyUnicast.request(SinkManyUnicast.java:434)
	at reactor.core.publisher.FluxContextWriteRestoringThreadLocals$ContextWriteRestoringThreadLocalsSubscriber.request(FluxContextWriteRestoringThreadLocals.java:163)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableConditionalSubscriber.request(FluxPeekFuseable.java:437)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableConditionalSubscriber.request(FluxPeekFuseable.java:437)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableConditionalSubscriber.request(FluxPeekFuseable.java:437)
	at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.request(FluxHandleFuseable.java:260)
	at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.lambda$requestUpstream$0(FluxSubscribeOn.java:135)
	at io.micrometer.context.ContextSnapshot.lambda$wrap$0(ContextSnapshot.java:91)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
10:05:56.083 [default-nioEventLoopGroup-1-3] WARN  i.n.u.c.AbstractEventExecutor - A task raised an exception. Task: io.micronaut.http.server.netty.handler.PipeliningServerHandler$StreamingOutboundHandler$$Lambda/0x00000070015c9880@450aa085
io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
	at io.netty.util.internal.ReferenceCountUpdater.toLiveRealRefCnt(ReferenceCountUpdater.java:83)
	at io.netty.util.internal.ReferenceCountUpdater.release(ReferenceCountUpdater.java:148)
	at io.netty.util.AbstractReferenceCounted.release(AbstractReferenceCounted.java:76)
	at io.micronaut.http.server.netty.FormRouteCompleter.release(FormRouteCompleter.java:234)
	at io.micronaut.http.server.netty.body.ManagedBody.release(ManagedBody.java:102)
	at io.micronaut.http.server.netty.body.ManagedBody.release(ManagedBody.java:102)
	at io.micronaut.http.server.netty.NettyHttpRequest.release(NettyHttpRequest.java:439)
	at io.micronaut.http.server.netty.RoutingInBoundHandler.cleanupRequest(RoutingInBoundHandler.java:153)
	at io.micronaut.http.server.netty.RoutingInBoundHandler.responseWritten(RoutingInBoundHandler.java:170)
	at io.micronaut.http.server.netty.websocket.NettyServerWebSocketUpgradeHandler.responseWritten(NettyServerWebSocketUpgradeHandler.java:167)
	at io.micronaut.http.server.netty.handler.PipeliningServerHandler$StreamingOutboundHandler.onError(PipeliningServerHandler.java:1131)
	at io.micronaut.http.server.netty.handler.PipeliningServerHandler$StreamingOutboundHandler.lambda$onError$1(PipeliningServerHandler.java:1121)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)
10:05:56.083 [default-nioEventLoopGroup-1-3] WARN  i.n.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.channel.ChannelPipelineException: io.micronaut.http.server.netty.handler.PipeliningServerHandler.handlerRemoved() has thrown an exception.
	at io.netty.channel.DefaultChannelPipeline.callHandlerRemoved0(DefaultChannelPipeline.java:640)
	at io.netty.channel.DefaultChannelPipeline.destroyDown(DefaultChannelPipeline.java:876)
	at io.netty.channel.DefaultChannelPipeline.destroyUp(DefaultChannelPipeline.java:844)
	at io.netty.channel.DefaultChannelPipeline.destroy(DefaultChannelPipeline.java:836)
	at io.netty.channel.DefaultChannelPipeline.access$700(DefaultChannelPipeline.java:46)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelUnregistered(DefaultChannelPipeline.java:1392)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:215)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:195)
	at io.netty.channel.DefaultChannelPipeline.fireChannelUnregistered(DefaultChannelPipeline.java:821)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:821)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
	at io.netty.util.internal.ReferenceCountUpdater.toLiveRealRefCnt(ReferenceCountUpdater.java:83)
	at io.netty.util.internal.ReferenceCountUpdater.release(ReferenceCountUpdater.java:148)
	at io.netty.util.AbstractReferenceCounted.release(AbstractReferenceCounted.java:76)
	at io.micronaut.http.server.netty.FormRouteCompleter.release(FormRouteCompleter.java:234)
	at io.micronaut.http.server.netty.body.ManagedBody.release(ManagedBody.java:102)
	at io.micronaut.http.server.netty.body.ManagedBody.release(ManagedBody.java:102)
	at io.micronaut.http.server.netty.NettyHttpRequest.release(NettyHttpRequest.java:439)
	at io.micronaut.http.server.netty.RoutingInBoundHandler.cleanupRequest(RoutingInBoundHandler.java:153)
	at io.micronaut.http.server.netty.RoutingInBoundHandler.responseWritten(RoutingInBoundHandler.java:170)
	at io.micronaut.http.server.netty.websocket.NettyServerWebSocketUpgradeHandler.responseWritten(NettyServerWebSocketUpgradeHandler.java:167)
	at io.micronaut.http.server.netty.handler.PipeliningServerHandler$StreamingOutboundHandler.discard(PipeliningServerHandler.java:1172)
	at io.micronaut.http.server.netty.handler.PipeliningServerHandler.handlerRemoved(PipeliningServerHandler.java:199)
	at io.netty.channel.AbstractChannelHandlerContext.callHandlerRemoved(AbstractChannelHandlerContext.java:1138)
	at io.netty.channel.DefaultChannelPipeline.callHandlerRemoved0(DefaultChannelPipeline.java:637)
	... 17 common frames omitted
```

**Comment by arenick001** [comment] 2024-04-10 11:04
@goeh Hi,goeh.I've got the same problem,have you solve it now? I'll appreciate it if there is a solution.

**Comment by goeh** [comment] 2024-04-10 11:09
No, it's not solved yet. It's still a blocker for our upgrade to Micronaut 4.x and I'm hoping for some comments from the core team.

**Comment by yawkat** [comment] 2024-04-15 05:45
Thanks for the report and reproducer @goeh. I was not able to reproduce the ref count issue. It just succeeds without error. Can you maybe provide the files that cause it? Maybe they affect the outcome, I had to use my own files.

The NPE is fixed in #10712. However it only happens because you do not set a content type on the metadata part (conversion fails without content type, produces null, NPE). You can set it like this and the upload succeeds (after making Metadata `@Serdeable`): 

```
curl -vF 'file=@./image1.jpeg' -F 'file=@./image2.jpeg' -F 'metadata=@./metadata.json;type=application/json' http://localhost:8080/uploads
```

**Comment by yawkat** [comment] 2024-04-15 05:46
ahhh i can reproduce the ref count thing by increasing file size.

**Comment by goeh** [comment] 2024-04-15 05:57
The content-type was missing from my curl example, sorry for that. I checked that the real application do have content-type (application/json) set for the metadata part. In our application users typically upload jpegs 0.5-1.0 mb and the metadata include some facts about the images.

**Closed as completed** 2024-04-17 06:43 UTC

**Comment by yawkat** [comment] 2024-04-17 06:44
thanks for the report!
