### ISSUE TITLE
Fired events are not consumed asynchronous in Micronaut 2.x

### ISSUE THREAD

**Issue by iBernd81** [micronaut-projects/micronaut-core#5019] opened 2021-03-01 07:44 UTC
My application in stable version uses Micronaut in latest old 1.3.7.

Within an injected `ApplicationEventPublisher` publishes events to one consumer. There one method is annotated with `@Async` and `@EventListener`. Everything is working fine in this constellation.

Now I am heavy working on upgrading to Micronaut 2.1.4...

Everything is working fine, too, except one customer service. Tracing the logs I can see that the event is fired but the consumer is never running after event publishing. If I downgrade here to stable version everything is running fine again.

Are there any operating system (Debian Linux in different versions) requirements with local IP adresses or DNS?

Things I have done and tested so for but without success:
- using Micronaut 2.3.3
- the consumer is implemeting `ApplicationEventListener` instead of `@EventListener` annotation
- setting `micronaut.server.thread-selection` to `auto` in configuration
- chaging the Java runtime to a newer one
- playing around with executors
-- increase the core size
-- creating a new thread pool

**Comment by graemerocher** [comment] 2021-03-01 08:03
Please provide an example that reproduces the issue

**Comment by iBernd81** [comment] 2021-03-01 10:51
Thank you @graemerocher for your seeing.

To share a running example is not as easy as expected. But I can provide some sources with two more comments and log information so far.

Perhaps you can explain me some details or where I can start further debugging or what do you think / guess about this issue.

### NotificationPublisher.groovy
```
@CompileStatic
@Singleton
@Slf4j
class NotificationPublisher {

    @Inject
    ApplicationEventPublisher applicationEventPublisher

    @Inject
    PgPool client

    /**
     * Fire out this combination of sql and params
     * @param sql The defined query
     * @param parameter The {{@link Tuple}} of parameter
     */
    @SuppressWarnings(['InvertedIfElse'])
    void publishNotification(String sql, Tuple parameter) {
        client.preparedQuery(sql).execute parameter, { ar ->
            if (ar.succeeded()) {
                RowSet<Row> rowSet = ar.result()
                if (!rowSet.empty) {
                    rowSet.each { row ->
                        int cclId = row.getInteger('ccl_id')
                        log.info('Got value "{}" for column "ccl_id" to work on', cclId)
                        block(cclId)
                        // this is very publishing takes place
                        applicationEventPublisher.publishEvent(new PostgresNotificationEvent(cclId:cclId))
                    }
                }
                else {
                    log.info('Nothing to do this time')
                }
            }
            else {
                log.error(ar.cause().message)
            }
        }
    }

    ...
}
```

### NotificationProcessService.groovy
```
@CompileStatic
@Singleton
@Slf4j
class NotificationProcessService {

    @Inject
    PgPool client

    @Inject
    HandlerFactory handlerFactory

    /**
     * Work on deeper in processing this notification asynchronous
     * @param postgresNotificationEvent The event packed with id for column ccl_id
     */
    @Async
    @EventListener
    void onPostgresNotification(PostgresNotificationEvent postgresNotificationEvent) {
        final String sql = '''
            SELECT ...
            WHERE ccl_id = $1
        '''
        // this is where app never comes over
        int id = postgresNotificationEvent.cclId
        Row row = client.preparedQuery(sql).rxExecute(Tuple.of(id)).map { rowSet ->
            if (!rowSet.empty) {
                return rowSet.first()
            }
            return null
        }.blockingGet() as Row
    }

    ...
}
```

[log.txt](https://github.com/micronaut-projects/micronaut-core/files/6060936/log.txt)

**Comment by jameskleeh** [comment] 2021-05-19 13:26
Closing this due to lack of an example app

**Closed as completed by jameskleeh** 2021-05-19 13:26 UTC
Labels: status: awaiting feedback
