### ISSUE TITLE
Micronaut Validator @Valid with Map<String, List<T>> failed

### ISSUE THREAD

**Issue by tchiotludo** [micronaut-projects/micronaut-core#4590] opened 2020-11-23 08:10 UTC
from `MapValidatorSpec.groovy`, I've added this test :

```java

    void "test cascade validate to list map"() {
        given:
        Authors a = new Authors(
                name: "Stephen King",
                books: [it:[new Book(title: "")]]
        )

        when:
        def constraintViolations = validator.validate(a)

        then:
        constraintViolations.size() == 1
        constraintViolations.first().propertyPath.toString() == 'books[it].title'
    }

@Introspected
class Authors {
    String name

    @Valid
    Map<String, List<Book>> books
}
```

With : 
-  micronaut branch v2.2, I've this error  `Cannot validate java.util.ArrayList. No bean introspection present. Please add @Introspected to the class and ensure Micronaut annotation processing is enabled`
-  micronaut master, I've `constraintViolations.size() == 0`

**Comment by jameskleeh** [comment] 2020-11-23 16:06
@tchiotludo In your example you have `Authors`, but the class is `Author`. The test you're showing there is exactly the same as the one already in the class, but without the `s` and the `Author` class already exists. Can you show the full code of a test that is failing?

**Comment by tchiotludo** [comment] 2020-11-23 16:16
oups sorry monday morning ... 
here is the Authors with a `Map<String, List<T>>` : 
```java 
@Introspected
class Authors {
    String name

    @Valid
    Map<String, List<Book>> books
}
```
[MapValidatorSpec.groovy.txt](https://github.com/micronaut-projects/micronaut-core/files/5584251/MapValidatorSpec.groovy.txt)

**Comment by jameskleeh** [comment] 2020-11-23 18:24
This one I'm not so sure about. Technically I don't know if we should be treating the list as a collection or value here. I can see what makes sense from a human perspective, but I don't know how it should behave according to the spec. Do you have any insights @graemerocher @wetted ?

**Comment by wetted** [comment] 2020-11-23 19:00
I can have a look and see what it's doing in the debugger. It _might_ be possible to support `@Valid Map<String, List<Book>> books` in a patch/minor release, but I have a feeling it might need support for the syntax `Map<String, List<@Valid Book>> books` on https://github.com/micronaut-projects/micronaut-core/issues/4457. However I don't believe the first form should be supported as per the spec. I'll see if the spec or TCK has something like that explicitly.

**Comment by wetted** [comment] 2020-11-24 17:00
I meant to say _I don't believe the first form should be supported_ and confirmed it. The second form I suggested is correct, but it's part of the Bean Validation 2.0 spec, and you can see the example at https://jakarta.ee/specifications/bean-validation/2.0/bean-validation_2.0.html#constraintdeclarationvalidationprocess-requirements-graphvalidation-examples, _Example 5.4: Making elements of a nested list subject to graph validation_ demonstrates this:

```
public class User {
    private Map<String, List<@Valid Address>> addressesByType;
}
```
However, Micronaut doesn't currently support this. See:
https://github.com/micronaut-projects/micronaut-core/issues/4457
https://github.com/micronaut-projects/micronaut-core/issues/4458

**Comment by tchiotludo** [comment] 2020-11-24 17:43
@wetted, thanks for the detailed explanation. 
I understand all the point about bean 2.0. 

My concern is about this, You mean that the first form : 
```
    @Valid
    Map<String, List<Book>> books
```
should not be supported ? 

In the link you share, the first form is here and still supported on 2.0 : 
```
    // traditional style; continues to be supported
    @Valid
    private Map<AddressType, Address> addressesByType;
````

I've also found this : https://github.com/hibernate/hibernate-validator/blob/1d74c294a3d3f2c638d7053610cb021497c63d10/engine/src/test/java/org/hibernate/validator/test/internal/xml/containerelementtype/ContainerElementTypeConstraintsForGetterXmlMappingTest.java

Seems to be supported by hibernate as I quickly understand. 

Or I misunderstood your response ?

**Comment by wetted** [comment] 2020-11-24 18:03
Yes, this is supported, and should work correctly in Micronaut to cascade validate `Address` values of the map.
```
// traditional style; continues to be supported
    @Valid
    private Map<AddressType, Address> addressesByType;
```

However, this is not an example of nested cascade validation, for which you opened this issue. In other words, you conflated the Map value type parameters between simple Object types (above) and nested containers of Object (below).
```
// this doesn't work, and requires @Valid on the List type parameter
    @Valid
    private Map<AddressType, List<Address>> addressListsByType;
```

I tried the latter both ways using the Hibernate validator in Spring, and it confirms what I say about the valid and invalid syntax for nested cascade validation. Nested cascade validation requires the `@Valid` annotation on the Map nested value (i.e. List) type parameter, rather than on the Map container itself.

**Comment by tchiotludo** [comment] 2020-11-24 20:51
Ok thanks for clarification ! 
I didn't do all the work to try with Hibernate, thanks. 

So my understand is that issue is duplicate from: #4457 & #4458 and will need work and will not be at best for 2.3 I guess ?

**Comment by jameskleeh** [comment] 2020-11-24 21:24
@tchiotludo We could make this work. It's important to note that prior to 2.2 the `@Valid` annotation just did nothing for this specific use case so at least now people will know. We will discuss what the best course of action is

**Comment by wetted** [comment] 2020-11-24 21:30
@tchiotludo it's a pretty safe assumption that Bean Validation 2.0 support (issue 4458) won't happen before 3.x. As for the specific use case you reported here, I'll leave it to @jameskleeh to determine next steps.

**Comment by tchiotludo** [comment] 2020-11-24 22:04
@jameskleeh, @wetted: first all, thanks for the response and your time on these issues, really appreciate !  

Just to temper, @jameskleeh,: 
* in micronaut 1.3.7, the `@Valid` don't raise any exception (and don't do [any validation](https://github.com/kestra-io/kestra/issues/169))
* in micronaut 2.x.x, the same `@Valid` raise an exception that will failed application. 

It changed the behavior of my app, so I need to adapt it.

I really understand your concern about that, I think I will keep that https://github.com/kestra-io/kestra/pull/222 like that and remove `@Valid` for [now](https://github.com/kestra-io/kestra/pull/222/files#diff-04248b1f2145b1c61fba9b785c34a53d88a394e2a5f89d7f008cf5be6cf576d0R96), just need to know the deadlline to know if I move to micronaut 2.x or wait or remove the `@Valid`

**Comment by wetted** [comment] 2020-11-24 22:15
@tchiotludo the reason it raises an error now (starting with 2.1.x), is that we fixed an issue that fails validation if the cascade object isn't `@Introspected` (see https://github.com/micronaut-projects/micronaut-core/pull/4411). So what is happening now is that it applies that specific validation to the nested `List<Book>` instead of cascading to the `Book` element type of the list, and fails because `List` isn't Introspected. I agree this is an unintended consequence and needs to be addressed in some way. Thanks for pointing that out.

**Comment by pontello** [comment] 2020-12-02 12:20
O believe I am facing a similar issue. For my case, a POJO similar to bellow used to work fine:

````java
@Introspected
public class QuoteFieldsRequestBody  {
  @Nullable @Valid
  private List<String> fields = new ArrayList<>();
}
````

But after upgrading to micronaut 2.1.x validation started crashing with:

> body: Cannot validate java.lang.String. No bean introspection present. Please add @Introspected to the class and ensure Micronaut annotation processing is enabled

If you look carefully, my code does't make much sense because I am saying that **fields** must be `@Valid` but I haven't provided any validation rules. If I add `@Size(max=3)` to make sense of it, I stop getting the introspection error.

Based on above experiment:

- What should be the error message when a developer uses `@Valid` annotation without proper validation rules? The "_No bean introspection present_" error is deftly not intuitive and it took me a while to understand what was going on. It is important to mention that versions prior to **2.1.x** didn't crash at all. I believe this situation used to be ignored.

- After adding `@Size(max=3)` code started working like a charm even though **String** is still not Introspected. So, while using containers (map, list, set) on what use cases the values must be be Introspected or not? do we have exceptions for the rule?

BTW: As as workaround to keep my existing codebase working with micronaut 2.1.x I was forced to annotate my controllers with `@Introspected(classes = String.class)` but I am not very comfortable with this solution.

Thanks

**Comment by jameskleeh** [comment] 2020-12-02 18:59
> The "No bean introspection present" error is deftly not intuitive and it took me a while to understand what was going on.

If you have any ideas for improvement, please present them here. PRs welcome

> on what use cases the values must be be Introspected or not

It must be introspected if validation is cascading to the objects properties. In the original code having `@Valid` had no effect. You can simply remove the annotation if there is nothing to validate. If there is another constraint annotation other than `@Valid` then we assume the validation is happening on things like strings. If there is no other constraint annotation present then we assume the validation is happening within the object and then introspection is required.

**Comment by rsalbergaria** [comment] 2024-06-24 21:06
Have you found a solution to the issue where attempting to validate a `List<Book>` within the `@Introspected class Authors` results in the error "Cannot validate java.util.List. No bean introspection present"? This suggests adding `@Introspected` to the class and ensuring Micronaut annotation processing is enabled. I'm facing a similar problem and would appreciate any advice or solutions.

**Comment by wetted** [comment] 2024-06-24 21:28
@rsalbergaria Hi, I'm retired and no longer working on Micronaut Framework. Maybe @graemerocher can be of assistance.

**Comment by graemerocher** [comment] 2024-06-25 08:47
This is corrected in Micronaut 4. The correct syntax is to apply `@Valid` to the generic not to the Map/List:

```
@Introspected
class Authors {
    String name

    Map<String, List<@Valid Book>> books
}
```

**Closed as completed by graemerocher** 2024-06-25 08:47 UTC
Labels: status: next major version

**Comment by rsalbergaria** [comment] 2024-06-25 15:50
My class is a DTO generated by Swagger Codegen, and the field in question is a list of strings. It's annotated with @Nullable @Valid @Parameter(name = "filters", in = ParameterIn.HEADER, description = "List of filters separated by ',' "). I'm encountering an issue where I receive an error stating "No bean introspection present. Please add @Introspected to the class and ensure Micronaut annotation processing is enabled." This occurs when I attempt to use validator.validate`. Can you help me please? @graemerocher

**Comment by graemerocher** [comment] 2024-06-25 15:53
Please report an issue here https://github.com/micronaut-projects/micronaut-openapi/issues

Since the generated code is incorrect
