### ISSUE TITLE
MediaType application/x-json-stream doesn't handle multiple JSON objects

### ISSUE THREAD

**Issue by make** [micronaut-projects/micronaut-core#1001] opened 2018-12-04 09:11 UTC
### Steps to Reproduce

I have following Controller:
```
package org.example.test.micronaut.jsonstream

import io.micronaut.http.HttpResponse
import io.micronaut.http.MediaType
import io.micronaut.http.annotation.Body
import io.micronaut.http.annotation.Controller
import io.micronaut.http.annotation.Post
import io.reactivex.Flowable
import io.reactivex.Single
import io.reactivex.schedulers.Schedulers
import org.slf4j.LoggerFactory

@Controller("/jsonStream")
class JsonStreamController {

    private val log = LoggerFactory.getLogger(javaClass)!!

    @Post("/", consumes = [MediaType.APPLICATION_JSON_STREAM])
    fun load(@Body data: Flowable<Map<Any,Any>>): Single<HttpResponse<Map<String, Boolean>>> {
        return data.subscribeOn(Schedulers.io())
                .map { map: Map<Any, Any> ->
                    log.info("$map")
                    1L
                }
                .count()
                .map {
                    log.info("Handled $it json objects successfully.")
                    HttpResponse.ok(mapOf("success" to true, "handled" to it))
                }
    }

}
```
But it takes only the first json object from POST body:
```
curl -s -H"Content-Type: application/x-json-stream" -XPOST "localhost:8080/jsonStream" --data-binary '{"foo":"bar"}
{"foo2":"bar2"}' | jq .
```
Returns `{"success": true,"handled": 1}`

But
```
curl -s -H"Content-Type: application/x-json-stream" -XPOST "localhost:8080/jsonStream" --data-binary '[{"foo":"bar"},{"foo2":"bar2"}]' | jq .
```
Returns `{"success": true,"handled": 2}`
So it seems that instead of handling stream of JSON objects it is handling objects wrapped in JSON array.

### Expected Behaviour

MediaType application/x-json-stream should handle all passed JSON objects separated by newline.
At least that is what the other projects like Rucio and .NET do. See e.g. https://rucio.readthedocs.io/en/latest/rest.html and https://github.com/Microsoft/ApplicationInsights-dotnet/blob/master/src/Microsoft.ApplicationInsights/Extensibility/Implementation/JsonSerializer.cs

### Actual Behaviour

It is handling only the first JSON object of body.

### Environment Information

- **Operating System**: Ubuntu 16.04.5 LTS
- **Micronaut Version:** 1.0.1
- **JDK Version:** 1.8.0_191

### Example Application

https://github.com/make/micronaut-test-json-stream

**Comment by vnesek** [comment] 2018-12-11 15:53
AFAIK  you are posting just a single object instead of JSON stream. JSON objects should be separated by newlines. Something like:

```
--data-binary '{"foo":"bar"}\n{"foo2":"bar2"}'
```

**Comment by make** [comment] 2018-12-12 14:09
@vnesek `'\n'` is not a line break in bash. If you look carefully you can see that I am using a line break (as it is) to separate json objects. My code works well if I change the MediaType to `text/plain` and split the stream by line breaks. So I have a workaround for now but it would be nice to have this as a built in feature in Micronaut core.

**Comment by jespersm** [comment] 2019-05-17 15:01
This bug is caused by interaction between HTTP chunking and `JacksonProcessor`.

Basically, if the JacksonProcessor gets this call sequence:
```
    processor.onNext('{"foo":"bar"}'.getBytes())
    processor.onNext('{"foo2":"bar2"}'.getBytes())
```
Then it will correctly see that there are two objects, streamed one after the other. This is the case if Micronaut is used as a client using a 

But if it gets the JSON text in one chunk (as in the `curl` example by the OP), then it will cease parsing after `{"foo":"bar"}`, and drop the rest of the buffer.

```
    processor.onNext('{"foo":"bar"}{"foo2":"bar2"}'.getBytes())
```

I can probably produce a patch soonish.

**Comment by graemerocher** [comment] 2019-05-17 15:13
Contributions welcome!

**Comment by jameskleeh** [comment] 2019-08-01 18:38
This was fixed via this issue https://github.com/micronaut-projects/micronaut-core/issues/1864

**Closed by jameskleeh** 2019-08-01 18:38 UTC
Labels: help wanted, type: enhancement
