### ISSUE TITLE
CodecException: Jackson deserializer has no default (no arg) constructor

### ISSUE THREAD

**Issue by glats** [micronaut-projects/micronaut-core#5234] opened 2021-04-12 05:15 UTC
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a new app with: `mn create-app me.jics.backend -b maven -f graalvm,lombok,openapi,redis-lettuce,cache-ehcache -t spock`
2. Create a POJO for the http client and use `com.fasterxml.jackson.datatype.jsr310.deser.LocalDateDeserializer` to deserialize a field `String` to `LocalDate`
3. Run `./mvnw package -Dpackaging=native-image`

### Expected Behaviour

The api must response a list of objects.

### Actual Behaviour

Show a runtime error:
```
 ERROR i.m.h.n.stream.HttpStreamsHandler - Error occurred writing stream response: io.micronaut.http.codec.CodecException: Error decoding JSON stream for type [T]: Class com.fasterxml.jackson.datatype.jsr310.deser.LocalDateDeserializer has no default (no arg) constructor at [Source: UNKNOWN; line: -1, column: -1]
 java.util.concurrent.CompletionException: io.micronaut.http.codec.CodecException: Error decoding JSON stream for type [T]: Class com.fasterxml.jackson.datatype.jsr310.deser.LocalDateDeserializer has no default (no arg) constructor at [Source: UNKNOWN; line: -1, column: -1]
```

### Environment Information

- **Operating System**: Arch Linux
- **Micronaut Version:** 2.4.2
- **JDK Version:**
      
       $ native-image --version
       GraalVM Version 21.0.0.2 (Java Version 11.0.10+8-jvmci-21.0-b06)

       $ java -version
       openjdk version "11.0.10" 2021-01-19
       OpenJDK Runtime Environment GraalVM CE 21.0.0.2 (build 11.0.10+8-jvmci-21.0-b06)
       OpenJDK 64-Bit Server VM GraalVM CE 21.0.0.2 (build 11.0.10+8-jvmci-21.0-b06, mixed mode, sharing)

### Example Application

- https://github.com/j1cs/drugstore-demo/tree/master/backend

###  Stacktrace
```
04:55:24.275 [default-nioEventLoopGroup-1-14] ERROR me.jics.StoreService - Error decoding JSON stream for type [T]: Class com.fasterxml.jackson.datatype.jsr310.deser.LocalDateDeserializer has no default (no arg) constructor
 at [Source: UNKNOWN; line: -1, column: -1]
04:55:24.275 [default-nioEventLoopGroup-1-14] ERROR i.m.h.n.stream.HttpStreamsHandler - Error occurred writing stream response: io.micronaut.http.codec.CodecException: Error decoding JSON stream for type [T]: Class com.fasterxml.jackson.datatype.jsr310.deser.LocalDateDeserializer has no default (no arg) constructor
 at [Source: UNKNOWN; line: -1, column: -1]
java.util.concurrent.CompletionException: io.micronaut.http.codec.CodecException: Error decoding JSON stream for type [T]: Class com.fasterxml.jackson.datatype.jsr310.deser.LocalDateDeserializer has no default (no arg) constructor
 at [Source: UNKNOWN; line: -1, column: -1]
 at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
 ...
```

**Comment by yawkat** [comment] 2022-03-25 19:02
This is a duplicate of #6452 (or rather the other way around). 

That issue mentions a pending feature:

> A class passed to @JsonSerialize should automatically get the constructor included in graal reflective access

However I think implementing this is unnecessary since the best way is to use `@Introspected` on the serializer class anyway.

**Closed as completed by yawkat** 2022-03-25 19:02 UTC
Labels: relates-to: graal
