### ISSUE TITLE
Controller Inheritance: Path Parameters for generic types are interpreted as Strings

### ISSUE THREAD

**Issue by juliuskrah** [micronaut-projects/micronaut-core#1848] opened 2019-06-29 16:24 UTC
I have a parent controller with 2 type Parameters `T` and `ID`. Sub-controllers inherit from the parent with `Status` and `UUID` for the types.

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

I created a controller class `GenericController`

```java
@RequiredArgsConstructor
public abstract class GenericController<T, ID extends Serializable> {
    private final StatusService<T, ID> service;

    @Get("/{id}")
    public Mono<HttpResponse<T>> find (ID id) {
        return //...;
    }
}
```

and another controller extending this one:

```java
@Controller(StatusController.PATH)
public class StatusController extends GenericController<Status, UUID> {
    static final String PATH = "/statuses";
    public StatusController(StatusService<Status, UUID> service) {
        super(service);
    }
}
```

Now when I make a request 
```posh
GET http://localhost:8080/statuses/f1f654fd-ba75-4d2c-a98a-084fd1865b59
```

### Expected Behaviour

The API route `/statuses/f1f654fd-ba75-4d2c-a98a-084fd1865b59` should respond without error

### Actual Behaviour

I get the following output

```json
Status: 500 Internal Server Error
{
    "message": "Internal Server Error: class java.lang.String cannot be cast to class java.util.UUID (java.lang.String and java.util.UUID are in module java.base of loader 'bootstrap')"
}
```

### Stacktrace

```
16:20:53.414 [nioEventLoopGroup-1-3] ERROR i.m.h.s.netty.RoutingInBoundHandler - Unexpected error occurred: class java.lang.String cannot be cast to class java.util.UUID (java.lang.String and java.util.UUID are in module java.base of loader 'bootstrap')
java.lang.ClassCastException: class java.lang.String cannot be cast to class java.util.UUID (java.lang.String and java.util.UUID are in module java.base of loader 'bootstrap')
        at com.juliuskrah.StatusServiceImpl.find(StatusServiceImpl.java:9)
        at com.juliuskrah.GenericController.find(GenericController.java:32)
        at com.juliuskrah.$StatusControllerDefinition$Intercepted.$$access1(Unknown Source)
        at com.juliuskrah.$StatusControllerDefinition$Intercepted$$proxy1.invokeInternal(Unknown Source)
        at io.micronaut.context.AbstractExecutableMethod.invoke(AbstractExecutableMethod.java:144)
        at io.micronaut.aop.chain.InterceptorChain.lambda$new$1(InterceptorChain.java:89)
        at io.micronaut.aop.chain.InterceptorChain.proceed(InterceptorChain.java:146)
        at com.juliuskrah.$StatusControllerDefinition$Intercepted.find(Unknown Source)
        at com.juliuskrah.$$StatusControllerDefinition$InterceptedDefinition$$exec2.invokeInternal(Unknown Source)
        at io.micronaut.context.AbstractExecutableMethod.invoke(AbstractExecutableMethod.java:144)
        at io.micronaut.context.DefaultBeanContext$BeanExecutionHandle.invoke(DefaultBeanContext.java:2711)
        at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:295)
        at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:122)
        at io.micronaut.http.server.netty.RoutingInBoundHandler.lambda$buildResultEmitter$15(RoutingInBoundHandler.java:1330)
        at io.reactivex.internal.operators.flowable.FlowableDefer.subscribeActual(FlowableDefer.java:35)
        at io.reactivex.Flowable.subscribe(Flowable.java:14805)
        at io.reactivex.Flowable.subscribe(Flowable.java:14752)
        at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:68)
        at io.reactivex.Flowable.subscribe(Flowable.java:14805)
        at io.reactivex.internal.operators.flowable.FlowableMap.subscribeActual(FlowableMap.java:37)
        at io.reactivex.Flowable.subscribe(Flowable.java:14805)
        at io.reactivex.Flowable.subscribe(Flowable.java:14752)
        at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:68)
        at io.reactivex.Flowable.subscribe(Flowable.java:14805)
        at io.reactivex.internal.operators.flowable.FlowableSwitchIfEmpty.subscribeActual(FlowableSwitchIfEmpty.java:32)
        at io.reactivex.Flowable.subscribe(Flowable.java:14805)
        at io.reactivex.Flowable.subscribe(Flowable.java:14752)
        at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:68)
        at io.reactivex.Flowable.subscribe(Flowable.java:14805)
        at io.reactivex.Flowable.subscribe(Flowable.java:14755)
        at io.micronaut.http.context.ServerRequestTracingPublisher.lambda$subscribe$0(ServerRequestTracingPublisher.java:52)
        at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:52)
        at io.micronaut.http.context.ServerRequestTracingPublisher.subscribe(ServerRequestTracingPublisher.java:52)
        at io.reactivex.internal.operators.flowable.FlowableFromPublisher.subscribeActual(FlowableFromPublisher.java:29)
        at io.reactivex.Flowable.subscribe(Flowable.java:14805)
        at io.reactivex.Flowable.subscribe(Flowable.java:14752)
        at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:68)
        at io.reactivex.Flowable.subscribe(Flowable.java:14805)
        at io.reactivex.Flowable.subscribe(Flowable.java:14752)
        at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82)
        at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:288)
        at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:253)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

### Environment Information

- **Operating System**: Windows 10
- **Micronaut Version:** 1.2.0.RC2
- **JDK Version:** 11

**Comment by jameskleeh** [comment] 2019-07-03 16:20
I can't reproduce the issue on the 1.1.4 snapshot

**Comment by juliuskrah** [comment] 2019-07-23 16:03
This issue is re-occurring with 1.2.0.RC2

**Comment by jameskleeh** [comment] 2019-07-23 16:06
Same repo, branch, and steps to reproduce?

**Comment by juliuskrah** [comment] 2019-07-23 16:11
> Same repo, branch, and steps to reproduce?

Branch has been removed. I will recreate the branch with a sample code

**Comment by juliuskrah** [comment] 2019-07-23 17:08
> Same repo, branch, and steps to reproduce?

Branch has been recreated here: https://github.com/jaesoft/resk/tree/micronaut-1848

**Comment by jameskleeh** [comment] 2019-07-23 20:45
Duplicate of https://github.com/micronaut-projects/micronaut-core/issues/1769

**Comment by jameskleeh** [comment] 2019-07-23 20:46
This is exhibiting the same problem as the other issue. Already fixed

**Closed by jameskleeh** 2019-07-23 20:46 UTC
Labels: closed: duplicate
