### ISSUE TITLE
@Requires on static @Factory class does not seem to work

### ISSUE THREAD

**Issue by marceloverdijk** [micronaut-projects/micronaut-core#1053] opened 2018-12-23 13:27 UTC
When I have static factory class in a Spock test like below, a @Requires on the static @Factory does not seem to work.
I have to add it explicitly to the @Bean method.

```
    @Factory
    @Requires(property = "spec.name", value = "GraphQLControllerSpec") // doesn't work
    static class GraphQLFactory {

        @Bean
        @Singleton
        @Requires(property = "spec.name", value = "GraphQLControllerSpec") // does work, if omitted bean is created despite having the requires on the factory class
        GraphQL graphQL() {
            graphQL
        }
    }
```

**Comment by jameskleeh** [comment] 2019-01-03 15:47
@marceloverdijk I can't reproduce. Please upload an example app

**Comment by graemerocher** [comment] 2019-01-03 15:48
maybe it is a difference between Groovy/Java?

**Comment by marceloverdijk** [comment] 2019-01-03 19:35
I don't know if it is related to Groovy but I encountered this issue in the `micronaut-graphql` module.

If you move the `@Requires` from the bean method here https://github.com/micronaut-projects/micronaut-graphql/blob/master/graphql/src/test/groovy/io/micronaut/graphql/GraphQLControllerSpec.groovy#L274 to the class then the other test here fails: https://github.com/micronaut-projects/micronaut-graphql/blob/master/graphql/src/test/groovy/io/micronaut/graphql/GraphQLConfigurationSpec.groovy#L33

**Comment by jameskleeh** [comment] 2019-01-03 21:01
@graemerocher Apparently this is by design? Both Java and Groovy call `buildForMethod` which sets `inheritTypeAnnotations` to false

**Comment by graemerocher** [comment] 2019-01-03 22:05
Yeah this is by design. For example you can have a factory that is a `@Singleton` but a method that is annotated `@Protoype`, so you don't want to inherit the annotations for the declaring bean

**Comment by graemerocher** [comment] 2019-01-03 22:06
We could maybe consider adding an exception to inheritance for `@Requires` but it complicates the implementation quite a bit

**Comment by marceloverdijk** [comment] 2019-01-03 22:38
For me this is not a big issue, so if it complicates the impl to much I can understand it is not worth it.
I just bumped against it in my tests and moved the `@Requires` to the method instead.

**Comment by jameskleeh** [comment] 2019-01-28 03:53
Closing this due to it working as designed

**Closed by jameskleeh** 2019-01-28 03:53 UTC
Labels: status: under consideration

**Comment by l0co** [comment] 2020-07-22 09:46
@jameskleeh It is very inconvenient that with single `@Replaces` on factory class, you cannot replace all introduced beans:

```
class AbstractFactory {
  
  @Singleton Object myBean() { return new Object(); }  
  // and a hundred of other beans

}

@Factory @Requires(SOME_CONDITION) class RealFactory1 extends AbstractFactory {}

@Factory @Requires(SOME_OTHER_CONDITION) class RealFactory2 extends AbstractFactory  {}
```

For the above example in both `RealFactory`-s you have now to override hundred of bean definitions with the same `@Requires` condition as for the `@Factory` class to make it working.

I don't understand why `@Required` on the `@Factory` cannot exclude the whole factory at all.
