### ISSUE TITLE
Resend headers on redirects

### ISSUE THREAD

**Issue by ikovalyov** [micronaut-projects/micronaut-core#2086] opened 2019-09-06 08:15 UTC
Imaging this workflow:

1. We use high-level http client with custom headers being send (including Authorisation header)
2. Request is sent to the external service
3. Service is using 301 to redirect us to the exact node which will process our request
4. Node returns 401 as no Authorisation header present

Is it possible to add possibility to mark headers to be resend on redirects?

Thanks.

**Comment by jameskleeh** [comment] 2020-12-28 21:40
Duplicate of https://github.com/micronaut-projects/micronaut-core/issues/2258

**Closed by jameskleeh** 2020-12-28 21:40 UTC
Labels: type: enhancement
