### ISSUE TITLE
Inconsistent error handling of empty & invalid http headers

### ISSUE THREAD

**Issue by fabienrenaud** [micronaut-projects/micronaut-core#2251] opened 2019-10-20 21:44 UTC
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Write a `@Get` and `@Post` endpoint both requiring a `@Header` of `long` type.
2. Send a request to the GET endpoint with the header specified but set to an empty string. The empty header results in a `UnsatisfiedRouteException` which is handled by the `UnsatisfiedRouteHandler`.
3. Send a request to the POST endpoint with the header specified but set to an empty string. The empty header results in a `ConversionErrorException` which is handled by the `ConversionErrorHandler`.

### Expected Behaviour

Sending an invalid/missing header to any request method (get, post, put, delete, patch, etc.) should be handled consistently regardless of the request method used. i.e either always throw a `UnsatisfiedRouteException` or always throw a `ConversionErrorException`

### Actual Behaviour

The empty header for GET and DELETE routes is handled by the `UnsatisfiedRouteHandler`.  

The empty header for POST and PUT routes is handled by the `ConversionErrorHandler`.  

### Environment Information

- **Operating System**: Mac OS Mojave 10.14.6
- **Micronaut Version:** 1.2.3
- **JDK Version:** 11

### Example Application

https://github.com/fabienrenaud/micronaut-bug-inconsistent-header-error-handling
 - App: https://github.com/fabienrenaud/micronaut-bug-inconsistent-header-error-handling/blob/master/src/main/java/bug/micronaut/App.java
 - AppTest: https://github.com/fabienrenaud/micronaut-bug-inconsistent-header-error-handling/blob/master/src/test/java/bug/micronaut/AppTest.java

gradle test:
```
bug.micronaut.AppTest > delete() FAILED
    io.micronaut.http.client.exceptions.HttpClientResponseException: Required Header [hh] not specified

bug.micronaut.AppTest > get() FAILED
    io.micronaut.http.client.exceptions.HttpClientResponseException: Required Header [hh] not specified

bug.micronaut.AppTest > put() FAILED
    io.micronaut.http.client.exceptions.HttpClientResponseException: Failed to convert argument [hh] for value [] due to: For input string: ""

bug.micronaut.AppTest > post() FAILED
    io.micronaut.http.client.exceptions.HttpClientResponseException: Failed to convert argument [hh] for value [] due to: For input string: ""
```

Micronaut:
 - `UnsatisfiedRouteException`: https://github.com/micronaut-projects/micronaut-core/blob/475ac7487f507d3e3009ebc52c1e33a640ff4ab3/router/src/main/java/io/micronaut/web/router/exceptions/UnsatisfiedRouteException.java#L57
 - `ConversionErrorException`: https://github.com/micronaut-projects/micronaut-core/blob/59bff5229b947809117222112860e48bf6aa26b7/core/src/main/java/io/micronaut/core/convert/exceptions/ConversionErrorException.java#L67

**Comment by jameskleeh** [comment] 2019-10-21 16:33
Please try Micronaut 1.2.5 and report back

**Comment by fabienrenaud** [comment] 2019-10-21 16:39
It got fixed in 1.2.4
Apparently with https://github.com/micronaut-projects/micronaut-core/issues/2178 and https://github.com/micronaut-projects/micronaut-core/commit/73dcc548133ee04e2b8f920e30243a948b3f5564

But I am not seeing tests around this use case (nor the one reported in #2178).

Can we add tests for both this ticket and 2178 to make sure regressions are not introduced in the future?

**Comment by jameskleeh** [comment] 2019-10-21 16:50
@fabienrenaud If you'd like to submit a PR to add tests you are welcome to. Would be a matter of modifying `DefaultConversionServiceSpec`.

**Comment by jameskleeh** [comment] 2019-10-21 17:30
Duplicate of #2178

**Closed by jameskleeh** 2019-10-21 17:30 UTC
Labels: closed: duplicate
