### ISSUE TITLE
Micronaut unconditionally enables permessage-deflate in websocket client

### ISSUE THREAD

**Issue by BrentDouglasB1** [micronaut-projects/micronaut-core#7798] opened 2022-08-01 00:19 UTC
### Expected Behavior

I should be able to run without per message deflate enabled.

### Actual Behaviour

Per message deflate is enabled unconditionally here
[https://github.com/micronaut-projects/micronaut-core/blame/3.5.x/http-server-netty/src/main/java/io/micronaut/http/server/netty/HttpPipelineBuilder.java#L252](https://github.com/micronaut-projects/micronaut-core/blame/3.5.x/http-server-netty/src/main/java/io/micronaut/http/server/netty/HttpPipelineBuilder.java#L252)
in this PR 
[https://github.com/micronaut-projects/micronaut-core/pull/6923](https://github.com/micronaut-projects/micronaut-core/pull/6923)

### Steps To Reproduce

1. Open a websocket to a micronaut server using a micronaut client

### Environment Information

Any

### Version

3.5.3

**Comment by BrentDouglasB1** [comment] 2022-08-01 00:25
I guess its more here thats causing the issue
https://github.com/micronaut-projects/micronaut-core/blob/c0d9cbadd591a67e354f31d5353eb4ea9d48b303/http-client/src/main/java/io/micronaut/http/client/netty/DefaultHttpClient.java#L952
rather than the server implementation.

**Comment by BrentDouglasB1** [comment] 2022-08-01 01:35
I think this should either
1. Allow disabling this completely with a config property; or
2. Provide a mechanism to override the WebSocketExtensionFilter to allow configuring this on a frame by frame basis; or
3. Both

**Comment by yawkat** [comment] 2022-08-01 08:04
duplicate of #7711

**Closed as not planned** 2022-08-01 11:52 UTC
