### ISSUE TITLE
Exclude endpoints from http access log

### ISSUE THREAD

**Issue by balintsteinbach** [micronaut-projects/micronaut-core#6643] opened 2021-12-13 16:29 UTC
### Feature description

Access log can be very useful to monitor REST calls. Unfortunately, it can be very verbose if it also logs "probe like" REST calls.
It would be very useful if some endpoints, like health check could, be excluded. If you use such an endpoint for example as a Kubernetes readiness probe it will flood the log.

I would suggest an extra parameter in micronaut.server.netty.access-logger like:

excludeEndpoint:
  - /health/readiness
  - /foo/bar

**Comment by balintsteinbach** [comment] 2021-12-13 16:35
If you think this make sense I would happily contribute it.

**Comment by graemerocher** [comment] 2021-12-13 17:01
PRs welcome

**Comment by jameskleeh** [comment] 2022-01-10 17:24
Duplicate of https://github.com/micronaut-projects/micronaut-core/issues/4653

**Closed as completed by jameskleeh** 2022-01-10 17:24 UTC
