### ISSUE TITLE
Native-Image io.netty.channel.ChannelHandlerMask - Class class io.micronaut.http.server.netty.RoutingInBoundHandler missing method exceptionCaught with native-image graalvm

### ISSUE THREAD

**Issue by eginez** [micronaut-projects/micronaut-core#2154] opened 2019-09-25 19:33 UTC
### Steps to Reproduce

1.git clone https://github.com/eginez/graalvm-demos.git
2. cd micronaut-webapp/todo-service
3. gradlew assemble
4. native-image --verbose --enable-all-security-services --no-server -cp 'build/libs/*'
5. curl -k "https://localhost:8080[or8443]/api/todos"

### Expected Behaviour

Not get an exception.
### Actual Behaviour
server responds with expected answer but also outputs
`
09:29:32.236 [nioEventLoopGroup-2-5] DEBUG io.netty.channel.ChannelHandlerMask - Class class io.micronaut.http.server.netty.RoutingInBoundHandler missing method exceptionCaught, assume we can not skip execution
java.lang.NoSuchMethodException: io.micronaut.http.server.netty.RoutingInBoundHandler.exceptionCaught(io.netty.channel.ChannelHandlerContext, java.lang.Throwable)
    at java.lang.Class.getMethod(DynamicHub.java:1003)
    at io.netty.channel.ChannelHandlerMask$2.run(ChannelHandlerMask.java:172)
    at io.netty.channel.ChannelHandlerMask$2.run(ChannelHandlerMask.java:167)
    at java.security.AccessController.doPrivileged(AccessController.java:89)
    at io.netty.channel.ChannelHandlerMask.isSkippable(ChannelHandlerMask.java:167)
    at io.netty.channel.ChannelHandlerMask.mask0(ChannelHandlerMask.java:153)
    at io.netty.channel.ChannelHandlerMask.mask(ChannelHandlerMask.java:80)
    at io.netty.channel.AbstractChannelHandlerContext.<init>(AbstractChannelHandlerContext.java:104)
    at io.netty.channel.DefaultChannelHandlerContext.<init>(DefaultChannelHandlerContext.java:26)
    at io.netty.channel.DefaultChannelPipeline.newContext(DefaultChannelPipeline.java:120)
    at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:204)
    at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:195)
    at io.micronaut.http.server.netty.NettyHttpServer$1.initChannel(NettyHttpServer.java:311)
    at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:129)
    at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:112)
    at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:964)
    at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:610)
    at io.netty.channel.DefaultChannelPipeline.access$100(DefaultChannelPipeline.java:46)
    at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1474)
    at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1126)
    at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:651)
    at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:503)
    at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:416)
    at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:475)
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:416)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:515)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.lang.Thread.run(Thread.java:748)
    at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:460)`

### Environment Information

- **Operating System**: mac os 10.12.6
- **Micronaut Version:** 1.2.2
- **JDK Version:** native-image ce 19.2.0.1

### Example Application

- git clone https://github.com/eginez/graalvm-demos.git

**Comment by graemerocher** [comment] 2019-09-26 07:48
This issue is known, however since Netty is quite dynamic is this handling and it is not practical to have every single handler under the sun declared for reflection I don't see us resolving this issue.

The particular exception you mention is logged at debug level anyway so you should just adjust your log settings to not output Netty debug output

**Closed by graemerocher** 2019-09-26 07:48 UTC
Labels: closed: won't fix, relates-to: graal

**Comment by eginez** [comment] 2019-09-26 16:59
@graemerocher gotcha so this does not impact anything then

**Comment by eginez** [comment] 2019-09-26 18:07
@graemerocher I actually observing something strange without https in graal native EE as well. Below the details
Operating System: mac os 10.12.6
Micronaut Version: 1.2.2
JDK Version: native-image ee 19.2.0.1

Actual Behaviour
Server *does not* return request
`java.lang.ExceptionInInitializerError: null
	at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:290)
	at java.lang.Class.ensureInitialized(DynamicHub.java:467)
	at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:235)
	at java.lang.Class.ensureInitialized(DynamicHub.java:467)
	at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:235)
	at java.lang.Class.ensureInitialized(DynamicHub.java:467)
	at io.netty.handler.codec.http.HttpServerCodec.<init>(HttpServerCodec.java:68)
	at io.micronaut.http.server.netty.NettyHttpServer$1.initChannel(NettyHttpServer.java:292)
	at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:129)
	at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:112)
	at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:964)
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:610)
	at io.netty.channel.DefaultChannelPipeline.access$100(DefaultChannelPipeline.java:46)
	at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1474)
	at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1126)
	at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:651)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:503)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:416)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:475)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:416)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:515)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:460)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
Caused by: io.netty.util.IllegalReferenceCountException: refCnt: 0
	at io.netty.buffer.AbstractByteBuf.ensureAccessible(AbstractByteBuf.java:1464)
	at io.netty.buffer.AbstractByteBuf.ensureWritable0(AbstractByteBuf.java:279)
	at io.netty.buffer.AbstractByteBuf.ensureWritable(AbstractByteBuf.java:274)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1081)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1089)
	at io.netty.handler.codec.http.HttpObjectEncoder.<clinit>(HttpObjectEncoder.java:55)
	at com.oracle.svm.core.hub.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:350)
	at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:270)
	... 27 common frames omitted`

**Comment by graemerocher** [comment] 2019-09-27 06:25
Please provide an example with steps to reproduce

**Comment by eginez** [comment] 2019-10-14 21:42
I am no longer able to replicate this issue with `1.2.3`. No further action is needed
