### ISSUE TITLE
Http 302 redirect and cookies

### ISSUE THREAD

**Issue by myspec** [micronaut-projects/micronaut-core#4318] opened 2020-10-14 18:09 UTC
### Task List

- [ ] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [ ] Full description of the issue provided (see below)

### Steps to Reproduce

//TestConfiguration has "this.setFollowRedirects(false);"
@Inject
@Client(value = "test-client", configuration = TestConfiguration.class)
RxHttpClient httpClient;

@Inject
@Client(value = "test-client2"
RxHttpClient httpClient2;

public void test() {
    MutableHttpRequest<Map<String, String>> mainRequest = HttpRequest.POST("https://xxx.xxx.com/Login", dataMap).contentType(MediaType.APPLICATION_FORM_URLENCODED_TYPE).headers(headers);
    Flowable<HttpResponse<String>> req = httpClient.exchange(mainRequest, String.class);
    HttpResponse<String> body = req.blockingFirst();
    Set<Cookie> cookie = body.getCookies().getAll();
    Flowable<String> ret = httpClient.retrieve(GET("https://xxx.xxx.com/Load").cookies(cookie), String.class);
    String result = ret.blockingFirst();
    // OK!!
}

public void test2() {
    MutableHttpRequest<Map<String, String>> mainRequest = HttpRequest.POST("https://xxx.xxx.com/Login", dataMap).contentType(MediaType.APPLICATION_FORM_URLENCODED_TYPE).headers(headers);
    Flowable<HttpResponse<String>> req = httpClient2.exchange(mainRequest, String.class);
    HttpResponse<String> body = req.blockingFirst();
    // FAILED
}

### Actual Behaviour
https://xxx.xxx.com/Login redirect to https://xxx.xxx.com/Load
test() success
but test2() failed.

I guess there is an issue on redirect and cookie handling.

03:00:44.433 [default-nioEventLoopGroup-1-4] DEBUG io.micronaut.http.client.netty.DefaultHttpClient - Sending HTTP Request: POST /CRM.Login/LoginProcV3
03:00:44.433 [default-nioEventLoopGroup-1-4] DEBUG io.micronaut.http.client.netty.DefaultHttpClient - Chosen Server: xxx.xxx.com(-1)
03:00:44.472 [default-nioEventLoopGroup-1-4] DEBUG io.netty.handler.ssl.util.InsecureTrustManagerFactory - Accepting a server certificate: CN=*.xxx.com, O="xxx co.,ltd", OU=Dev Team, 
03:00:44.509 [default-nioEventLoopGroup-1-4] DEBUG io.netty.handler.ssl.SslHandler - [id: 0x6e4e9fec, L:/192.168.10.108:57488 - R:xxx.xxx.com/10.10.10.10:443] HANDSHAKEN: protocol:TLSv1.2 cipher suite:TLS_RSA_WITH_AES_256_CBC_SHA
03:00:44.778 [default-nioEventLoopGroup-1-5] DEBUG io.micronaut.http.client.netty.DefaultHttpClient - Sending HTTP Request: GET /Login
03:00:44.778 [default-nioEventLoopGroup-1-5] DEBUG io.micronaut.http.client.netty.DefaultHttpClient - Chosen Server: xxx.xxx.com(-1)
03:00:44.804 [default-nioEventLoopGroup-1-5] DEBUG io.netty.handler.ssl.util.InsecureTrustManagerFactory - Accepting a server certificate: CN=*.xxx.com, O="xxx co.,ltd", OU=Dev Team, 
03:00:44.811 [default-nioEventLoopGroup-1-5] DEBUG io.netty.handler.ssl.SslHandler - [id: 0x66d18f2c, L:/192.168.10.108:57489 - R:xxx.xxx.com/10.10.10.10:443] HANDSHAKEN: protocol:TLSv1.2 cipher suite:TLS_RSA_WITH_AES_256_CBC_SHA

### Environment Information

- **Operating System**: Windows 10
- **Micronaut Version:** 2.1.1
- **JDK Version:** openjdk14

**Comment by jameskleeh** [comment] 2020-10-15 13:32
Please upload an example application with steps to reproduce

**Comment by myspec** [comment] 2020-10-15 16:20
[test.zip](https://github.com/micronaut-projects/micronaut-core/files/5386359/test.zip)
please test with
GET http://localhost:8080/login/test1
GET http://localhost:8080/login/test2

**Comment by jameskleeh** [comment] 2021-01-04 20:36
Duplicate of https://github.com/micronaut-projects/micronaut-core/issues/2650

**Closed as completed by jameskleeh** 2021-01-04 20:36 UTC
Labels: closed: duplicate
