### ISSUE TITLE
UnsupportedOperationException when using bootstrap config with MICRONAUT_ENVIRONMENTS

### ISSUE THREAD

**Issue by ttzn** [micronaut-projects/micronaut-core#4298] opened 2020-10-12 21:31 UTC
### Task List

- [X] Steps to reproduce provided
- [X] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [X] Full description of the issue provided (see below)

### Steps to Reproduce

1. Generate a simple Micronaut app (`mn create-app example.test`)
2. Add a `bootstrap.yml` file to classpath
3. Run `example.Application` with non-empty `MICRONAUT_ENVIRONMENTS`

### Expected Behaviour

Don't crash

### Actual Behaviour

Crashes at startup with the following stack trace:

```
23:12:08.714 [main] INFO  i.m.context.env.DefaultEnvironment - Established active environments: [whatever]
23:12:08.734 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: null
java.lang.UnsupportedOperationException: null
	at java.base/java.util.AbstractList.add(AbstractList.java:153)
	at java.base/java.util.AbstractList.addAll(AbstractList.java:270)
	at io.micronaut.context.env.DefaultEnvironment.<init>(DefaultEnvironment.java:117)
	at io.micronaut.context.DefaultApplicationContext$BootstrapEnvironment.<init>(DefaultApplicationContext.java:517)
	at io.micronaut.context.DefaultApplicationContext$RuntimeConfiguredEnvironment.createBootstrapEnvironment(DefaultApplicationContext.java:745)
	at io.micronaut.context.DefaultApplicationContext$RuntimeConfiguredEnvironment.start(DefaultApplicationContext.java:695)
	at io.micronaut.context.DefaultApplicationContext$RuntimeConfiguredEnvironment.start(DefaultApplicationContext.java:665)
	at io.micronaut.context.DefaultApplicationContext.startEnvironment(DefaultApplicationContext.java:213)
	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:165)
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:64)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:299)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:285)
	at example.Application.main(Application.java:8)
```

### Environment Information

- **Operating System**: Fedora 30
- **Micronaut Version:** 2.1.0
- **JDK Version:** AdoptOpenJDK 11.0.3

I ran into this problem while trying to build an AWS Lambda function which picks up values from the Parameter Store (as per [the documentation](https://docs.micronaut.io/latest/guide/index.html#distributedConfigurationAwsParameterStore)). However, specifying anything in MICRONAUT_ENVIRONMENTS causes the thing to crash with the above exception. This is reproducible without anything involving AWS. The exception is thrown from inside this piece of code in `DefaultEnvironment`:

```java
        List<String> specifiedNames = configuration.getEnvironments();

        specifiedNames.addAll(0, Stream.of(System.getProperty(ENVIRONMENTS_PROPERTY),
                System.getenv(ENVIRONMENTS_ENV))
                .filter(StringUtils::isNotEmpty)
                .flatMap(s -> Arrays.stream(s.split(",")))
                .map(String::trim)
                .collect(Collectors.toList()));
```

This code mutates the `configuration.getEnvironments()` list, but the `BootstrapEnvironment` class uses an anonymous `ApplicationContextConfiguration` with the following:

```java
                public List<String> getEnvironments() {
                    // Crashes when calling .addAll() with non-empty collection arg
                    return Arrays.asList(activeEnvironments); 
                }
```

This seems wrong, but maybe there's something I missed ?

**Comment by jameskleeh** [comment] 2020-10-13 05:28
Duplicate of https://github.com/micronaut-projects/micronaut-core/issues/4244

**Closed as completed by jameskleeh** 2020-10-13 05:28 UTC
Labels: closed: duplicate
