### ISSUE TITLE
Executable method generation for suspending controller methods erases parameter names.

### ISSUE THREAD

**Issue by Hc747** [micronaut-projects/micronaut-core#2946] opened 2020-03-20 04:16 UTC
### Task List

- [X] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [X] Example that reproduces the problem uploaded to Github
- [X] Full description of the issue provided (see below)

### Steps to Recreate

1. Create a controller with a suspending and non-suspending function, both of which have the same signature (name can differ).
2. Compile the project (via gradle).
3. View the $ExampleControllerDefinition's executable method implementations.

### Steps to Reproduce

1. Clone the sample project at: https://github.com/Hc747/micronaut-suspending-example
2. Run the project via gradle's application:run task.
3. Invoke each of the Example controller endpoints with the same request structure.

### Expected Behaviour

The output from each request should be the same. In my case:
passport.jpg 189842

### Actual Behaviour
The output from each request differs.
example/foo:
passport.jpg 189842

example/bar:
{
    "message": "Required argument [CompletedFileUpload p0] not specified",
    "path": "/p0",
    "_links": {
        "self": {
            "href": "/example/bar",
            "templated": false
        }
    }
}

### Environment Information

- **Operating System**: macOS Catalina 10.15.3
- **Micronaut Version:** 1.3.3
- **JDK Version:** 1.8.0_212
- **Kotlin Version:** 1.3.61
- **KotlinX Version:** 1.3.4

### Example Application
https://github.com/Hc747/micronaut-suspending-example

**Comment by Hc747** [comment] 2020-03-20 05:20
@jameskleeh

**Comment by Hc747** [comment] 2020-03-31 01:23
@graemerocher if you can point me in the direction of where to begin, I'd be happy to work on resolving this issue!

**Comment by graemerocher** [comment] 2020-03-31 06:54
Sure, the place to start looking is `BeanDefinitionWriter`: https://github.com/micronaut-projects/micronaut-core/blob/1.3.x/inject/src/main/java/io/micronaut/inject/writer/BeanDefinitionWriter.java#L811

Unfortunately for Kotlin we haven't worked out to a way to dynamically compile kotlin code in a test like we do in Java so you would have to attach a remote debugger to the Kotlin compiler. See https://discuss.kotlinlang.org/t/debug-annotation-processor-kapt/11369/4 for how to do that.

**Comment by Hc747** [comment] 2020-03-31 23:51
Cheers, I'll take a look at this when I can!

**Comment by jameskleeh** [comment] 2020-12-23 16:50
Duplicate of https://github.com/micronaut-projects/micronaut-core/issues/4674

**Closed by jameskleeh** 2020-12-23 16:50 UTC
Labels: lang: kotlin, type: bug
