### ISSUE TITLE
Injection fails when jvm ir is enabled

### ISSUE THREAD

**Issue by junki-oku** [micronaut-projects/micronaut-core#9823] opened 2023-04-18 07:56 UTC
### Actual Behaviour

When com.micronaut.test.Config is set to data class with jvm ir enabled in the attached project, io.micronaut.context.exceptions.DependencyInjectionException is raised.

### Steps To Reproduce

1. Set kapt.use.jvm.ir in gradle.properties to true
2. Make com.micronaut.test.Config a data class
3. run app

### Environment Information

JDK : Amazon Corretto 17
Kotlin : 1.8.20
[MicronautInjectionFailed.zip](https://github.com/micronaut-projects/micronaut-kotlin/files/11259235/MicronautInjectionFailed.zip)

### Version

3.8.8

**Comment by sdelamo** [comment] 2023-08-30 14:53
@timyates can you try this with Micronaut Framework 4 and KAPT?

**Comment by timyates** [comment] 2023-08-31 11:33
@sdelamo This still fails with Micronaut 4.0.5

The error is

```
[ERROR][2023-08-31 12:30:52.346][main] io.micronaut.runtime.Micronaut - Error starting Micronaut server: Bean definition [com.micronaut.test.ApplicationFactory] could not be loaded: Failed to inject value for parameter [stringConfig] of class: com.micronaut.test.Config

Message: No bean of type [java.lang.String] exists. Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor).
Path Taken: new ApplicationFactory() --> ApplicationFactory.config --> new Config([String stringConfig],boolean booleanConfig,int intConfig)
io.micronaut.context.exceptions.BeanInstantiationException: Bean definition [com.micronaut.test.ApplicationFactory] could not be loaded: Failed to inject value for parameter [stringConfig] of class: com.micronaut.test.Config
```

When `kapt.use.jvm.ir` is set to true.

**Comment by timyates** [comment] 2023-08-31 11:37
Cleaned-up reproducer over here https://github.com/bloidonia/micronaut-kapt-ir-failure/tree/main

**Comment by timyates** [comment] 2023-09-04 11:08
I don't believe we currently fully support the IR compiler with Kapt.

I'm moving this issue to core as I believe the change required will be in there somewhere

**Comment by dstepanov** [comment] 2023-09-04 12:01
It looks like KAPT shuffles the methods, and a different constructor is selected.
KAPT doesn't support default values, so the only way is to make them nullable:
```
@ConfigurationProperties("app.config")
data class Config @ConfigurationInject constructor(
	var stringConfig: String?,
	var booleanConfig: Boolean?,
	var intConfig: Int?,
)
```
or do something like this:
```
@ConfigurationProperties("app.config")
class Config @ConfigurationInject constructor(paramS: String?,
											  paramB: Boolean?,
											  paramI: Int?) {

	var stringConfig = paramS ?: ""
	var booleanConfig = paramB ?: true
	var intConfig = paramI ?: 1

}
```

**Comment by timyates** [comment] 2023-09-22 13:41
Between Kapt shuffling the order of the generated methods, and it's lack of support for default methods, I'm not sure there's anything we can do to support Kapt with the IR compiler 🤔 

I'm going to close this

**Closed as not planned by timyates** 2023-09-22 13:41 UTC
Labels: lang: kotlin
