### ISSUE TITLE
Dependency Injection not working with multiple beans of the same type 1.2.0RC2

### ISSUE THREAD

**Issue by Deviad** [micronaut-projects/micronaut-core#1980] opened 2019-08-04 21:21 UTC
Message: Multiple possible bean candidates found: [clarity.dispatcher.MyRxBean, clarity.dispatcher.MyRxBean]
```

@Factory
public class MyRxBusConfig {

  @Named("INPUT")
  @RequestScope
  MyRxBean<String> inputMyRxBean() {
    return new MyRxBean<>();
  }

  @Named("OUTPUT")
  @RequestScope
  MyRxBean<String> outputMyRxBean() {
    return new MyRxBean<>();
  }
}
```

```
@RequestScope
public class WebSocketListenerImpl extends WebSocketListener {

  private static final int NORMAL_CLOSURE_STATUS = 1000;
  @Named("OUTPUT")
  @Inject
  private MyRxBean<String> outputBus;
  @Named("INPUT")
  @Inject
  private MyRxBean<String> inputBus;

  private String json = null;
...
```

It works neither with constructor injection nor with field injection.
https://github.com/Deviad/clarity/tree/feature/micronaut_eigth_attempt_120RC2/clarity-dispatcher

Also, the scope does not matter. It can be @Singleton or @RequestScope

**Comment by graemerocher** [comment] 2019-08-05 11:04
Added a test for this at https://github.com/micronaut-projects/micronaut-core/commit/966e48caaa68ad95ebe4bc41f9f875f621bb3039

However I have been unable to reproduce with master

**Comment by jameskleeh** [comment] 2019-08-05 13:50
This is probably a duplicate of https://github.com/micronaut-projects/micronaut-core/issues/1910

**Closed** 2019-08-05 14:43 UTC
Labels: closed: cannot reproduce, closed: duplicate
