### ISSUE TITLE
@Scheduled doesn't work with JDK 17 and 1 CPU

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-core#6121] opened 2021-09-08 11:41 UTC
### Expected Behavior

The `@Scheduled` GraalVM test application should work for GraalVM JDK 17 as it works for both JDK 11 and JDK 16.

### Actual Behaviour

When an application with an `@Scheduled` bean starts on CI the scheduled task is not executed. I haven't able to reproduce it locally and it only fails on CI.
I've also forced the environments `gcp` and `cloud`, as they are enabled on CI` but I'm not still able to reproduce it locally.

I've set `io.micronaut` package level to `TRACE` and I've seen a difference when I run the application locally or in CI:

### Locally

After the application startups there is a lookup for `CountService`. This is the bean that has a method annotated with `@Schedule`. I also added a few `println`s to check the execution:

```
13:31:46.051 [main] TRACE i.m.context.DefaultBeanContext - Looking up existing bean for key: ApplicationEventPublisher
13:31:46.051 [main] TRACE i.m.context.DefaultBeanContext - No existing bean found for bean key: ApplicationEventPublisher
13:31:46.051 [main] DEBUG i.m.context.DefaultBeanContext - Finding candidate beans for type: ApplicationEventPublisher
13:31:46.052 [main] DEBUG i.m.context.DefaultBeanContext - Resolved bean candidates [io.micronaut.context.event.ApplicationEventPublisherFactory@6cae4cb4] for type: ApplicationEventPublisher
13:31:46.052 [main] DEBUG i.m.context.DefaultBeanContext - Finalized bean definitions candidates: [io.micronaut.context.event.ApplicationEventPublisherFactory@6cae4cb4]
13:31:46.052 [main] DEBUG i.m.context.DefaultBeanContext - Found concrete candidate [io.micronaut.context.event.ApplicationEventPublisherFactory@6cae4cb4] for type: ApplicationEventPublisher 
13:31:46.052 [main] DEBUG io.micronaut.context.lifecycle - Created bean [io.micronaut.context.event.ApplicationEventPublisherFactory$2@361325a] from definition [io.micronaut.context.event.ApplicationEventPublisherFactory@6cae4cb4] with qualifier [null]
13:31:46.052 [main] DEBUG i.m.c.e.ApplicationEventPublisher - Publishing event: io.micronaut.discovery.event.ServiceReadyEvent[source=io.micronaut.http.server.netty.NettyEmbeddedServerInstance@6863cf79]
13:31:46.052 [main] DEBUG i.m.context.DefaultBeanContext - Resolving beans for type: <ServiceReadyEvent> io.micronaut.context.event.ApplicationEventListener 
13:31:46.052 [main] TRACE i.m.context.DefaultBeanContext - Looking up existing beans for key: <ServiceReadyEvent> ApplicationEventListener
13:31:46.052 [main] TRACE i.m.context.DefaultBeanContext - No beans found for key: <ServiceReadyEvent> ApplicationEventListener
13:31:46.052 [main] DEBUG i.m.context.DefaultBeanContext - Qualifying bean [ApplicationEventListener] from candidates [Definition: io.micronaut.runtime.context.scope.refresh.RefreshScope, Definition: io.micronaut.runtime.http.scope.RequestCustomScope] for qualifier: <ServiceReadyEvent> 
13:31:46.052 [main] DEBUG i.m.context.DefaultBeanContext - Found no matching beans of type [ApplicationEventListener] for qualifier: <ServiceReadyEvent> 
13:31:46.052 [main] INFO  io.micronaut.runtime.Micronaut - Startup completed in 331ms. Server Running: http://localhost:8080
13:31:46.882 [scheduled-executor-thread-1] TRACE i.m.context.DefaultBeanContext - Looking up existing bean for key: CountService
13:31:46.882 [scheduled-executor-thread-1] TRACE i.m.context.DefaultBeanContext - No existing bean found for bean key: CountService
13:31:46.882 [scheduled-executor-thread-1] DEBUG i.m.context.DefaultBeanContext - Finding candidate beans for type: CountService
13:31:46.883 [scheduled-executor-thread-1] DEBUG i.m.context.DefaultBeanContext - Resolved bean candidates [Definition: example.micronaut.CountService] for type: CountService
13:31:46.883 [scheduled-executor-thread-1] DEBUG i.m.context.DefaultBeanContext - Finalized bean definitions candidates: [Definition: example.micronaut.CountService]
13:31:46.883 [scheduled-executor-thread-1] DEBUG i.m.context.DefaultBeanContext - Found concrete candidate [Definition: example.micronaut.CountService] for type: CountService 
13:31:46.883 [scheduled-executor-thread-1] DEBUG io.micronaut.context.lifecycle - Created bean [example.micronaut.CountService@4b4ebe71] from definition [Definition: example.micronaut.CountService] with qualifier [null]
13:31:46.883 [scheduled-executor-thread-1] DEBUG i.m.context.DefaultBeanContext - Registering singleton bean example.micronaut.CountService@4b4ebe71 for type [CountService] using bean key CountService
-------> total = 0
13:31:47.883 [scheduled-executor-thread-1] TRACE i.m.context.DefaultBeanContext - Looking up existing bean for key: CountService
13:31:47.883 [scheduled-executor-thread-1] DEBUG i.m.context.DefaultBeanContext - Resolved existing bean [example.micronaut.CountService@4b4ebe71] for type [CountService] and qualifier [null]
-------> total = 1
...
```

### CI

See https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/1572167387#L941

The application starts up and nothing happens. Please notice that it starts at 10:29.20.517 and then, 10 seconds later it receives a GET request. There is a 10 seconds sleep in the test script to give time to the application to run the scheduled code. Then the GET request returns the counter and it checks if it's correct (which is not in this case):

```
10:29:20.517 [main] TRACE i.m.context.DefaultBeanContext - No beans found for key: <ServiceReadyEvent> ApplicationEventListener
10:29:20.517 [main] DEBUG i.m.context.DefaultBeanContext - Qualifying bean [ApplicationEventListener] from candidates [Definition: io.micronaut.runtime.http.scope.RequestCustomScope, Definition: io.micronaut.runtime.context.scope.refresh.RefreshScope] for qualifier: <ServiceReadyEvent> 
10:29:20.517 [main] DEBUG i.m.context.DefaultBeanContext - Found no matching beans of type [ApplicationEventListener] for qualifier: <ServiceReadyEvent> 
10:29:20.517 [main] INFO  io.micronaut.runtime.Micronaut - Startup completed in 148ms. Server Running: http://runner-72989761-project-10315337-concurrent-0:8080
+ curl -s localhost:8080/count
10:29:30.385 [default-nioEventLoopGroup-1-2] TRACE i.m.h.server.netty.NettyHttpServer - Server runner-72989761-project-10315337-concurrent-0:8080 Received Request: GET /count
10:29:30.386 [default-nioEventLoopGroup-1-2] DEBUG i.m.h.s.netty.RoutingInBoundHandler - Request GET /count
10:29:30.386 [default-nioEventLoopGroup-1-2] TRACE i.m.h.s.netty.RoutingInBoundHandler - Matched route GET - /count to controller class example.micronaut.CountController
10:29:30.386 [default-nioEventLoopGroup-1-2] TRACE i.m.context.DefaultBeanContext - Looking up existing bean for key: countService
10:29:30.386 [default-nioEventLoopGroup-1-2] DEBUG i.m.context.DefaultBeanContext - Resolved existing bean [example.micronaut.CountService@23ae8c9c] for type [CountService countService] and qualifier [null]
10:29:30.387 [default-nioEventLoopGroup-1-2] DEBUG io.micronaut.context.lifecycle - Created bean [example.micronaut.CountController@1facd9db] from definition [Definition: example.micronaut.CountController] with qualifier [null]
10:29:30.387 [default-nioEventLoopGroup-1-2] DEBUG i.m.context.DefaultBeanContext - Registering singleton bean example.micronaut.CountController@1facd9db for type [CountController] using bean key CountController
10:29:30.387 [default-nioEventLoopGroup-1-2] TRACE i.m.h.s.netty.RoutingInBoundHandler - Encoding emitted response object [0] using codec: io.micronaut.runtime.http.codec.TextPlainCodec@43e25e0f
...
```

### More info

I've also tried annotating the bean with `@Context` but the behaviour is the same.

I'm not sure if some of the changes or optimizations done for GraalVM are affected by something on JDK 17 but as I mentioned I'm still not able to reproduce this locally.

### Steps To Reproduce

- `git clone https://github.com/micronaut-graal-tests/micronaut-schedule-graal`
- `cd micronaut-schedule-graal`
- `git checkout issue-jdk17`
- Use GraalVM JDK 17
- `./build-native-image.sh`
- `./schedule`

You should see a println with the value of the counter when the application works.

### Version

3.0.2-SNAPSHOT

**Comment by ilopmar** [comment] 2021-09-10 14:09
I've been trying a few more things and I've found the problem.

### Log when it works

```
13:21:22.343 [main] DEBUG i.m.context.DefaultBeanContext - Found 1 beans for type [<Scheduled> ExecutableMethodProcessor]: [BeanRegistration: io.micronaut.scheduling.processor.ScheduledMethodProcessor@4011cc0f] 
13:21:22.343 [main] DEBUG i.m.context.condition.Condition - Bean [io.micronaut.scheduling.io.watch.$DefaultWatchThread$Definition] will not be loaded due to failing conditions:
13:21:22.343 [main] DEBUG i.m.context.condition.Condition - * Required property [micronaut.io.watch.paths] with value [null] not present
13:21:22.343 [main] DEBUG i.m.context.condition.Condition - Configuration: io.micronaut.http.server.cors will not be loaded due to failing conditions:
13:21:22.343 [ForkJoinPool.commonPool-worker-2] TRACE i.m.context.DefaultBeanContext - Looking up existing bean for key: @Named('scheduled') TaskScheduler
13:21:22.343 [ForkJoinPool.commonPool-worker-4] DEBUG i.m.context.condition.Condition - Bean [io.micronaut.discovery.cloud.digitalocean.$DigitalOceanMetadataConfiguration$Definition] will not be loaded due to failing conditions:
13:21:22.343 [main] DEBUG i.m.context.condition.Condition - * Required property [micronaut.server.cors.enabled] with value [true] not present
13:21:22.343 [ForkJoinPool.commonPool-worker-4] DEBUG i.m.context.condition.Condition - * None of the required environments [digitalocean] are active: [gcp, cloud]
13:21:22.343 [ForkJoinPool.commonPool-worker-2] TRACE i.m.context.DefaultBeanContext - No existing bean found for bean key: @Named('scheduled') TaskScheduler
13:21:22.343 [main] DEBUG i.m.context.DefaultBeanContext - Loaded active configurations: io.micronaut.jackson
13:21:22.343 [ForkJoinPool.commonPool-worker-2] DEBUG i.m.context.DefaultBeanContext - Finding candidate beans for type: TaskScheduler
13:21:22.343 [main] DEBUG i.m.context.DefaultBeanContext - BeanContext Started.
13:21:22.343 [ForkJoinPool.commonPool-worker-4] DEBUG i.m.context.condition.Condition - Bean [io.micronaut.discovery.cloud.digitalocean.$DigitalOceanMetadataResolver$Definition] will not be loaded due to failing conditions:
13:21:22.343 [main] TRACE i.m.context.DefaultBeanContext - Looking up existing bean for key: ApplicationEventPublisher
13:21:22.343 [ForkJoinPool.commonPool-worker-4] DEBUG i.m.context.condition.Condition - * None of the required environments [digitalocean] are active: [gcp, cloud]
13:21:22.343 [ForkJoinPool.commonPool-worker-2] DEBUG i.m.context.DefaultBeanContext - Resolved bean candidates [Definition: io.micronaut.scheduling.ScheduledExecutorTaskScheduler] for type: TaskScheduler
13:21:22.343 [main] TRACE i.m.context.DefaultBeanContext - No existing bean found for bean key: ApplicationEventPublisher
13:21:22.343 [ForkJoinPool.commonPool-worker-2] DEBUG i.m.context.DefaultBeanContext - Finalized bean definitions candidates: [Definition: io.micronaut.scheduling.ScheduledExecutorTaskScheduler]
13:21:22.343 [ForkJoinPool.commonPool-worker-2] DEBUG i.m.context.DefaultBeanContext - Qualifying bean [TaskScheduler] for qualifier: @Named('scheduled') 
13:21:22.343 [ForkJoinPool.commonPool-worker-2] DEBUG i.m.context.DefaultBeanContext - Found concrete candidate [Definition: io.micronaut.scheduling.ScheduledExecutorTaskScheduler] for type: @Named('scheduled') TaskScheduler 
13:21:22.343 [ForkJoinPool.commonPool-worker-4] DEBUG i.m.context.condition.Condition - Bean [io.micronaut.http.netty.channel.$EpollEventLoopGroupFactory$Definition] will not be loaded due to failing conditions:
```

### Log when it doesn't work (on CI)

```
07:53:30.425 [main] DEBUG i.m.context.DefaultBeanContext - Found 1 beans for type [<Scheduled> ExecutableMethodProcessor]: [BeanRegistration: io.micronaut.scheduling.processor.ScheduledMethodProcessor@2c8dd814] 
07:53:30.425 [main] DEBUG i.m.context.condition.Condition - Bean [io.micronaut.scheduling.io.watch.$DefaultWatchThread$Definition] will not be loaded due to failing conditions:
07:53:30.425 [main] DEBUG i.m.context.condition.Condition - * Required property [micronaut.io.watch.paths] with value [null] not present
07:53:30.426 [main] DEBUG i.m.context.condition.Condition - Configuration: io.micronaut.http.server.cors will not be loaded due to failing conditions:
07:53:30.426 [main] DEBUG i.m.context.condition.Condition - * Required property [micronaut.server.cors.enabled] with value [true] not present
07:53:30.426 [main] DEBUG i.m.context.DefaultBeanContext - Loaded active configurations: io.micronaut.jackson
07:53:30.426 [main] DEBUG i.m.context.DefaultBeanContext - BeanContext Started.
07:53:30.426 [main] TRACE i.m.context.DefaultBeanContext - Looking up existing bean for key: ApplicationEventPublisher
07:53:30.427 [main] TRACE i.m.context.DefaultBeanContext - No existing bean found for bean key: ApplicationEventPublisher
07:53:30.427 [main] DEBUG i.m.context.DefaultBeanContext - Finding candidate beans for type: ApplicationEventPublisher
07:53:30.427 [main] DEBUG i.m.context.DefaultBeanContext - Resolved bean candidates [io.micronaut.context.event.ApplicationEventPublisherFactory@1f69aa10] for type: ApplicationEventPublisher
07:53:30.427 [main] DEBUG i.m.context.DefaultBeanContext - Finalized bean definitions candidates: [io.micronaut.context.event.ApplicationEventPublisherFactory@1f69aa10]
07:53:30.427 [main] DEBUG i.m.context.DefaultBeanContext - Found concrete candidate [io.micronaut.context.event.ApplicationEventPublisherFactory@1f69aa10] for type: ApplicationEventPublisher 
07:53:30.427 [main] DEBUG io.micronaut.context.lifecycle - Created bean [io.micronaut.context.event.ApplicationEventPublisherFactory$2@1aa9f0a6] from definition [io.micronaut.context.event.ApplicationEventPublisherFactory@1f69aa10] with qualifier [null]
07:53:30.428 [main] DEBUG i.m.c.e.ApplicationEventPublisher - Publishing event: io.micronaut.context.event.StartupEvent[source=io.micronaut.context.DefaultApplicationContext@784d2895]
07:53:30.428 [main] DEBUG i.m.context.DefaultBeanContext - Resolving beans for type: <StartupEvent> io.micronaut.context.event.ApplicationEventListener 
07:53:30.428 [main] TRACE i.m.context.DefaultBeanContext - Looking up existing beans for key: <StartupEvent> ApplicationEventListener
```

On the second we can't find `TRACE i.m.context.DefaultBeanContext - No existing bean found for bean key: @Named('scheduled') TaskScheduler` or anything related to that. It seems that everything that runs on `ForkJoinPool.commonPool-worker` is not executed.

I've done two things to confirm this:

- Run the tests on CI in a more powerful instance. The **test pass** and we can see `ForkJoinPool.commonPool-worker` in the log. See https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/1580160113
- Run the native image in a Docker container with just 1 CPU. The scheduled code is not executed and there is no `ForkJoinPool.commonPool-worker` on the log:
```
docker run -it --rm --cpus=1 -v $PWD:/app frolvlad/alpine-glibc:alpine-3.12 /app/schedule

# In the output there is no ForkJoinPool.commonPool-worker
```

Now, running it again with more than 1 CPU (like 1.5). It works!:

```
docker run -it --rm --cpus=1.5 -v $PWD:/app frolvlad/alpine-glibc:alpine-3.12 /app/schedule
 __  __ _                                  _   
|  \/  (_) ___ _ __ ___  _ __   __ _ _   _| |_ 
| |\/| | |/ __| '__/ _ \| '_ \ / _` | | | | __|
| |  | | | (__| | | (_) | | | | (_| | |_| | |_ 
|_|  |_|_|\___|_|  \___/|_| |_|\__,_|\__,_|\__|
  Micronaut (v3.0.2-SNAPSHOT)

...
...
16:06:39.328 [main] DEBUG i.m.context.DefaultBeanContext - Found no matching beans of type [ApplicationEventListener] for qualifier: <ServiceReadyEvent> 
16:06:39.328 [main] INFO  io.micronaut.runtime.Micronaut - Startup completed in 55ms. Server Running: http://edf828c74d46:8080
16:06:40.284 [scheduled-executor-thread-1] TRACE i.m.context.DefaultBeanContext - Looking up existing bean for key: CountService
16:06:40.284 [scheduled-executor-thread-1] TRACE i.m.context.DefaultBeanContext - No existing bean found for bean key: CountService
16:06:40.284 [scheduled-executor-thread-1] DEBUG i.m.context.DefaultBeanContext - Finding candidate beans for type: CountService
16:06:40.284 [scheduled-executor-thread-1] DEBUG i.m.context.DefaultBeanContext - Resolved bean candidates [Definition: example.micronaut.CountService] for type: CountService
16:06:40.284 [scheduled-executor-thread-1] DEBUG i.m.context.DefaultBeanContext - Finalized bean definitions candidates: [Definition: example.micronaut.CountService]
16:06:40.284 [scheduled-executor-thread-1] DEBUG i.m.context.DefaultBeanContext - Found concrete candidate [Definition: example.micronaut.CountService] for type: CountService 
16:06:40.284 [scheduled-executor-thread-1] DEBUG io.micronaut.context.lifecycle - Created bean [example.micronaut.CountService@7eccbfcd] from definition [Definition: example.micronaut.CountService] with qualifier [null]
16:06:40.284 [scheduled-executor-thread-1] DEBUG i.m.context.DefaultBeanContext - Registering singleton bean example.micronaut.CountService@7eccbfcd for type [CountService] using bean key CountService
-------> total = 0
16:06:41.284 [scheduled-executor-thread-1] TRACE i.m.context.DefaultBeanContext - Looking up existing bean for key: CountService
16:06:41.284 [scheduled-executor-thread-1] DEBUG i.m.context.DefaultBeanContext - Resolved existing bean [example.micronaut.CountService@7eccbfcd] for type [CountService] and qualifier [null]
-------> total = 1
^C16:06:41.798 [Thread-1] INFO  io.micronaut.runtime.Micronaut - Embedded Application shutting down

```

**Comment by graemerocher** [comment] 2021-09-10 14:25
Seems we probably need to detect if there is only 1 CPU and run it synchronously if there is 😕

**Comment by ilopmar** [comment] 2021-09-10 14:48
This is something that has been changed in JDK 17 and it's not related to GraalVM. I've build the fatjar locally and run inside Docker:

```
docker run -it --rm --cpus=1 -v $PWD:/app openjdk:17-alpine 

$ java -jar /app/build/libs/micronaut-schedule-graal-0.1-all.jar

```

It happens the same, it doesn't work. Change that to `openjdk:16-alpine` and it works again...

**Comment by schoenobates** [comment] 2021-11-12 17:10
I hit the same issue today running a container in K8S - setting the resource limits to 2 or more for the CPU solves the problem. Without this setting, the JVM is reporting one CPU and I don;t see the Scheduled tasks running either.

**Comment by johndevs** [comment] 2021-11-20 09:10
Thanks for reporting this, we've been struggling to find the root cause for this as well after a jdk17 upgrade.

**Comment by lightbody** [comment] 2021-11-24 14:11
Seems we're having the same problem. Things worked great on Java 11 on the same infrastructure. In fact, we're running the largest Fargate instance (4 vCPUs) but we've found Java likes to report back 1 CPU often, so I suspect what we'll see is it sometimes works, sometimes doesn't.

**Comment by lightbody** [comment] 2021-11-24 16:18
OK, I can confirm that adding `-XX:ActiveProcessorCount=2` (or more) fixes this. @jameskleeh believes the issue might be a core JDK bug and is rooted around the use of `ForkJoinPool.commonPool().execute()`.

**Comment by jameskleeh** [comment] 2021-11-24 16:56
This is a bug in the JDK

https://bugs.openjdk.java.net/browse/JDK-8274349

It looks like they have only fixed it in 18 instead of putting it in 17 where the regression was introduced. I would suggest anyone facing this issue to let them know

I think the better fix is to set the system property `-Djava.util.concurrent.ForkJoinPool.common.parallelism=1` rather than changing the active processor count

**Comment by jameskleeh** [comment] 2021-11-24 17:03
Apparently it was backported https://bugs.openjdk.java.net/browse/JDK-8274756. Need to wait for 17.0.2

**Comment by jameskleeh** [comment] 2021-12-01 16:40
Going to close this since there isn't anything we can do

**Closed as completed by jameskleeh** 2021-12-01 16:40 UTC
