### ISSUE TITLE
Using ProxyHttpClient from a Controller produces response with empty body

### ISSUE THREAD

**Issue by candrews-ns** [micronaut-projects/micronaut-core#6284] opened 2021-10-06 09:45 UTC
### Expected Behavior

Using ProxyHttpClient from a Controller like this:

```
public class HelloController {

    @Inject
    ProxyHttpClient proxyHttpClient;

    @Get(uri = "/publisher")
    public Publisher<MutableHttpResponse<?>> publisher() {
        MutableHttpRequest<?> req = HttpRequest.GET(...);
        return proxyHttpClient.proxy(req);
    }
```

should return a correct response, like substantially the same code does when used in a Filter, per the documentation - https://docs.micronaut.io/latest/guide/index.html#proxyClient

This is an example of ProxyHttpClient working correctly, used in a Filter, in the repro application I've provided for this issue:

```
$ curl -svk http://localhost:8080/hello/foo
*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /hello/foo HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.78.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< date: Wed, 6 Oct 2021 09:30:10 GMT
< Content-Type: text/plain
< content-length: 10
< connection: close
<
* Closing connection 0
Hello foo!
```

### Actual Behaviour

The response returned by the controller method shown above looks like this:

```
$ curl -svk http://localhost:8080/controller/publisher
*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /controller/publisher HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.78.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 Ok
< connection: keep-alive
< transfer-encoding: chunked
<
* Connection #0 to host localhost left intact
```

The response body is empty, even though tcpdump shows that the correct upstream request is made and the response is sent, and the application logging shows that the upstream response is received.

Logging from HandlerPublisher for a request to the controller method:

```
10:33:16.076 [default-nioEventLoopGroup-1-9] TRACE i.m.h.n.reactive.HandlerPublisher - HandlerPublisher (state: BUFFERING) buffering message: Hello foo!
```

Equivalent logs for the filter method:

```
10:30:10.903 [default-nioEventLoopGroup-1-6] TRACE i.m.h.n.reactive.HandlerPublisher - HandlerPublisher (state: BUFFERING) buffering message: Hello foo!
10:30:10.903 [default-nioEventLoopGroup-1-6] TRACE i.m.h.n.reactive.HandlerPublisher - HandlerPublisher (state: DRAINING) received demand: 1
10:30:10.903 [default-nioEventLoopGroup-1-6] TRACE i.m.h.n.reactive.HandlerPublisher - HandlerPublisher (state: DRAINING) release message from buffer to satisfy demand: 1
10:30:10.903 [default-nioEventLoopGroup-1-6] TRACE i.m.h.n.reactive.HandlerPublisher - HandlerPublisher (state: DRAINING) emitting next message: Hello foo!
10:30:10.904 [default-nioEventLoopGroup-1-6] TRACE i.m.h.n.reactive.HandlerPublisher - HandlerPublisher (state: DRAINING) received cancellation request
```

### Steps To Reproduce

1. With either Micronaut 2.5.13 or 3.0.2 (the bug appears to be present in both)
2. Using the linked demo app (originally generated from https://micronaut.io/launch/)
3. Implement a Controller, and use ProxyHttpClient to return an upstream response
4. Make a request to the controller route, and observe that the response body is missing. 

In the linked demo app, there is a test ProxyViaFilterOrControllerTest#test_via_controller() which demonstrates this failing case, along with the various passing cases using a Filter.

For Micronaut 2.x there is a workaround using .singleOrError() shown in the demo app on the `mn2.5.13` branch, but I haven't found an equivalent workaround in Micronaut 3.x.

### Environment Information

- MacOS 10.15.7
- JDK 15.0.1+9-18

### Example Application

https://github.com/candrews-ns/micronaut-proxy-repro

### Version

3.0.2

**Comment by jameskleeh** [comment] 2021-10-06 15:18
ProxyHttpClient is meant for proxying requests. That isn't what is being done in this case:

```
    // Directly return a Publisher<...> -- does not work, returns an empty body.
    @Get(uri = "/publisher")
    public Publisher<MutableHttpResponse<?>> publisher() {
        MutableHttpRequest<?> req = HttpRequest.GET(getUri());
        return proxyHttpClient.proxy(req);
    }
```

Simply use a regular `HttpClient`

**Comment by candrews-ns** [comment] 2021-10-06 15:59
It looks like in simplifying the repro case here, I've eliminated the justification for using a ProxyHttpClient in the first place. 

Let me see if I can put something together that shows that.

**Comment by jameskleeh** [comment] 2021-10-11 19:38
I'm 95% sure this is the same issue as https://github.com/micronaut-projects/micronaut-core/issues/6178

**Comment by jameskleeh** [comment] 2021-10-11 20:55
Duplicate of #6178

**Closed as completed by jameskleeh** 2021-10-11 20:55 UTC
Labels: closed: duplicate
