### ISSUE TITLE
Micronaut fails for LocalDateTime method parameter

### ISSUE THREAD

**Issue by rlconst** [micronaut-projects/micronaut-core#9969] opened 2023-10-12 07:00 UTC
### Expected Behavior

You can pass LocalDateTime as parameter
```
String localDateTime(@NotNull @QueryValue LocalDateTime time) {
    ...
}
```

### Actual Behaviour

```
ERROR i.m.r.intercept.RecoveryInterceptor - Type [io.micronaut.http.client.convert.DateTimeConversionSpec$TimeClient$Intercepted] executed with error: Unsupported field: OffsetSeconds
java.time.temporal.UnsupportedTemporalTypeException: Unsupported field: OffsetSeconds
	at java.base/java.time.LocalDate.get0(LocalDate.java:709)
	at java.base/java.time.LocalDate.getLong(LocalDate.java:688)
	at java.base/java.time.LocalDateTime.getLong(LocalDateTime.java:718)
	at java.base/java.time.format.DateTimePrintContext.getValue(DateTimePrintContext.java:308)
	at java.base/java.time.format.DateTimeFormatterBuilder$OffsetIdPrinterParser.format(DateTimeFormatterBuilder.java:3628)
	at java.base/java.time.format.DateTimeFormatterBuilder$CompositePrinterParser.format(DateTimeFormatterBuilder.java:2402)
	at java.base/java.time.format.DateTimeFormatter.formatTo(DateTimeFormatter.java:1849)
	at java.base/java.time.format.DateTimeFormatter.format(DateTimeFormatter.java:1823)
	at io.micronaut.runtime.converters.time.TimeConverterRegistrar.lambda$register$3(TimeConverterRegistrar.java:141)
	at io.micronaut.core.convert.DefaultConversionService.convert(DefaultConversionService.java:155)
	at io.micronaut.context.env.DefaultEnvironment.convert(DefaultEnvironment.java:311)
	at io.micronaut.core.convert.ConversionService.convert(ConversionService.java:120)
	at io.micronaut.http.client.bind.binders.QueryValueClientArgumentRequestBinder.bind(QueryValueClientArgumentRequestBinder.java:119)
```

### Version

3.10.1

**Comment by rlconst** [comment] 2023-10-12 07:07
I'm on 3.10.x and I did a simple fix. 4.x logic is significantly different. What is the best aproach: backport or keep it as is?

**Comment by sdelamo** [comment] 2023-10-26 10:45
This does not happen in Micronaut Framework 4, does it?

**Comment by sdelamo** [comment] 2023-10-26 11:04
@rlconst I am not able to reproduce this with @QueryValue or FormUrlEncoded body

https://github.com/micronaut-projects/micronaut-core/pull/10027

what am I missing to reproduce it @rlconst ?

**Comment by yawkat** [comment] 2023-10-26 11:53
ok looking at the 3.x code it seems this is an issue because youre trying to return an LDT in a format that needs an offset. imo it is correct that this fails and this is not a bug.

**Comment by rlconst** [comment] 2023-10-27 14:00
@sdelamo the problem is on Micronaut 3.10.1. On 4.x LocalDateTime handled properly. To reproduce the problem, just copy test-case without fix and you should see

**Comment by rlconst** [comment] 2023-10-27 14:04
@yawkat passing data with fake offset (UTC) is for minimizing changes in code. I disagree that HTTP Client should fail because it can't correctly serialize and deserialize some class from the core JDK because for some reason it decided that you can't pass timestamp without offset.

**Comment by yawkat** [comment] 2023-10-27 14:06
We should not hallucinate a time zone. If you want to produce a string that contains a zone/offset, you must use a type that includes the offset.

**Comment by rlconst** [comment] 2023-10-27 14:12
@yawkat I want to be able to pass `LocalDateTime` as `@RequestParam` and I don't care about offsets and timezones

**Comment by sdelamo** [comment] 2023-11-01 14:21
I think this can be closed via https://github.com/micronaut-projects/micronaut-core/pull/10027

**Closed as completed by sdelamo** 2023-11-01 14:21 UTC
