### ISSUE TITLE
Umlauts are not supported by default

### ISSUE THREAD

**Issue by wowselim** [micronaut-projects/micronaut-core#4766] opened 2020-12-30 21:19 UTC
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a controller and return an umlaut in the response body

### Expected Behaviour

When sending "Glück" back to the client, the client should see "Glück"

### Actual Behaviour

Client receives "GlÃ¼ck"

### Environment Information

- **Operating System**: Windows 10
- **Micronaut Version:** 2.2.2
- **JDK Version:** 11.0.9

### Example Application
I have created a reproducer but it's really simple so I also included the source directly.

https://github.com/wowselim/micronaut-umlaut-reproducer

```java
package com.example.controller;

import io.micronaut.http.annotation.Controller;
import io.micronaut.http.annotation.Get;

@Controller
public class UmlautController {
    @Get
    String getWord() {
        System.out.println("Glück");
        return "Glück";
    }
}
```

**Comment by jameskleeh** [comment] 2021-01-04 14:30
I can't reproduce this. Perhaps your client is mangling the data.

```
micronaut-umlaut-reproducer main $ curl localhost:8080
Glückmicronaut-umlaut-reproducer main $ 
```

**Comment by wowselim** [comment] 2021-01-04 14:34
> I can't reproduce this. Perhaps your client is mangling the data.
> 
> ```
> micronaut-umlaut-reproducer main $ curl localhost:8080
> Glückmicronaut-umlaut-reproducer main $ 
> ```

I can't reproduce it on OS X either but on windows in both firefox and insomnia I was getting "GlÃ¼ck" as response. Might be a windows only issue?

**Comment by jameskleeh** [comment] 2021-01-04 14:37
Try `@Get(produces = "text/plain;charset=utf-8")`

**Comment by wowselim** [comment] 2021-01-05 05:49
It's still the same on Windows. This time I've included a screenshot with insomnia and microsofts edge browser.

![grafik](https://user-images.githubusercontent.com/5699586/103611214-197c7000-4f22-11eb-90ad-b061317c2d18.png)

**Comment by wetted** [comment] 2021-01-06 17:22
I tried it with a Spock test on Windows 10 Enterprise 1809

```groovy
import io.micronaut.http.HttpRequest
import io.micronaut.http.client.RxHttpClient
import io.micronaut.http.client.annotation.Client
import io.micronaut.test.extensions.spock.annotation.MicronautTest
import spock.lang.Specification

import javax.inject.Inject

@MicronautTest
class UmlautControllerSpec extends Specification {
    @Inject
    @Client("/")
    RxHttpClient client

    void "test umlaut"() {
        when:
        HttpRequest<String> request = HttpRequest.GET("/")
        String response = client.toBlocking().retrieve(request)

        then:
        response == "Glück"
    }
}
```
The test result is,

```
GlÃ¼ck

Condition not satisfied:

response == "Glück"
|        |
GlÃ¼ck   false
         2 differences (66% similarity)
         Gl(Ã¼)ck
         Gl(ü-)ck
```

**Comment by paulk-asert** [comment] 2021-01-12 02:07
I tried setting on the command-line the normal trick:

```
set JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8
```

but that didn't seem to work. Also adding the following to the gradle build seemed to fix the problem:

```
tasks.withType(JavaCompile) {
    options.fork = true
    options.forkOptions.jvmArgs << '-Dfile.encoding=UTF8'
}
```
This fixed the version emitted via http but doesn't fix the version echoed to the console if you still have the windows default encoding of Cp1252.

**Comment by timyates** [comment] 2022-01-28 16:57
I believe this is this issue over here on the gradle project itself

https://github.com/gradle/gradle/issues/19235

With that, and Paul's workaround above, I'm tempted to close this.  Any objections?

**Comment by jameskleeh** [comment] 2022-01-28 17:01
@timyates No objections. I don't think there is anything we can do here

**Comment by timyates** [comment] 2022-01-28 17:48
Closing as this is an issue external to micronaut

**Closed as completed by timyates** 2022-01-28 17:48 UTC
Labels: status: validated
