### ISSUE TITLE
Deadlock during bean initialization

### ISSUE THREAD

**Issue by mancze** [micronaut-projects/micronaut-core#6706] opened 2022-01-03 09:01 UTC
### Expected Behavior

No deadlock during bean initialization.

### Actual Behaviour

We have observed a deadlock situation during `RequestScoped` bean initialization.

Locks in play:

- `RequestCustomScope`'s `ReentrantReadWriteLock` (in its base class `AbstractConcurrentCustomScope`)
- `singletonObjects` monitor (by using `synchronized` keyword)

What is happening is that one thread (for http request) acquires write lock of `RequestCustomScope`. While initialization this request-scoped bean a singleton bean dependency is needed (need to enter `singletonObjects` synchronized block). But before this singleton block is entered, another thread acquires `singletonObjects` monitor.

This other thread is in the stage when it is in a `singletonObjects` synchronized block to create some bean. In the case above the bean to initialize itself is not a singleton (but prototype), but is produced by a factory (which is singleton - not sure if it plays a role). The key point is here that thread is in `singletonObjects` synchronized section. The factory itself however needs a request-scope dependency and therefore to obtain read lock of `RequestCustomScope`'s `ReentrantReadWriteLock`.

### Steps To Reproduce

See in the repository with repro-steps.

### Example Application

https://github.com/mancze/micronaut-request-scope-deadlock

### Version

3.2.3

**Comment by mancze** [comment] 2022-01-03 11:24
Another concern is that implementation of `RequestCustomScope` is based on `AbstractConcurrentCustomScope` which uses single `ReentrantReadWriteLock` for all requests. I'm afraid that can be a bottleneck and not performant enough.

**Comment by yawkat** [comment] 2022-05-10 08:47
Looks like a duplicate of #3910

**Comment by dstepanov** [comment] 2022-05-10 10:37
The test is passing in 3.5.0 branch. Closing as fixed.

**Closed as completed by dstepanov** 2022-05-10 10:37 UTC
Labels: type: bug, status: example attached
