### ISSUE TITLE
Beans are sometimes not injected in junit tests

### ISSUE THREAD

**Issue by l0co** [micronaut-projects/micronaut-core#4730] opened 2020-12-17 14:13 UTC
In `2.1.4`, but I've also caught it in previous version.

Sometimes tests are not executed, but the following exception is thrown:

```
No ParameterResolver registered for parameter [io.luna.service.main.test.TestObjectBuilder builder] in constructor [public io.luna.service.main.test.finance.algorithm.reassignment.ReassignmentTest(io.luna.service.main.test.TestObjectBuilder,io.luna.service.main.finance.common.service.CompanyService,io.luna.service.main.finance.bank.service.PooledBankAccountService,io.luna.service.main.finance.user.service.UserAccountService,io.luna.service.main.finance.common.service.AssignmentService,io.luna.service.main.rbac.service.UserBankService,io.luna.service.main.finance.algorithm.repository.ReassignmentRepository,io.luna.service.main.finance.algorithm.service.ReassignmentService)].
org.junit.jupiter.api.extension.ParameterResolutionException: No ParameterResolver registered for parameter [io.luna.service.main.test.TestObjectBuilder builder] in constructor [public io.luna.service.main.test.finance.algorithm.reassignment.ReassignmentTest(io.luna.service.main.test.TestObjectBuilder,io.luna.service.main.finance.common.service.CompanyService,io.luna.service.main.finance.bank.service.PooledBankAccountService,io.luna.service.main.finance.user.service.UserAccountService,io.luna.service.main.finance.common.service.AssignmentService,io.luna.service.main.rbac.service.UserBankService,io.luna.service.main.finance.algorithm.repository.ReassignmentRepository,io.luna.service.main.finance.algorithm.service.ReassignmentService)].
	at org.junit.jupiter.engine.execution.ExecutableInvoker.resolveParameter(ExecutableInvoker.java:200)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.resolveParameters(ExecutableInvoker.java:183)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:74)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeTestClassConstructor(ClassBasedTestDescriptor.java:342)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.instantiateTestClass(ClassBasedTestDescriptor.java:289)
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.instantiateTestClass(ClassTestDescriptor.java:79)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.instantiateAndPostProcessTestInstance(ClassBasedTestDescriptor.java:267)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$testInstancesProvider$2(ClassBasedTestDescriptor.java:259)
	at java.base/java.util.Optional.orElseGet(Optional.java:362)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$testInstancesProvider$3(ClassBasedTestDescriptor.java:258)
	at org.junit.jupiter.engine.execution.TestInstancesProvider.getTestInstances(TestInstancesProvider.java:31)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$prepare$0(TestMethodTestDescriptor.java:101)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.prepare(TestMethodTestDescriptor.java:100)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.prepare(TestMethodTestDescriptor.java:65)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$prepare$1(NodeTestTask.java:111)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.prepare(NodeTestTask.java:111)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:79)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:248)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$5(DefaultLauncher.java:211)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:226)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:199)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:132)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:99)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:79)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:75)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy5.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.stop(TestWorker.java:133)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

Interesting thing is that it somehow depends on test class structure (hash?), so I suppose there's a race condition somewhere during tests instantiation or not enforced a proper order in some hash maps/sets.

I've caught it with my test class. I can reproduce the problem each time, unless I change the method name. Please look at the attached video.

[Kazam_screencast_00000-enc.mp4.gz](https://github.com/micronaut-projects/micronaut-core/files/5709949/Kazam_screencast_00000-enc.mp4.gz)

**Comment by jameskleeh** [comment] 2020-12-18 19:35
There is no Micronaut code in that stacktrace so I don't see how we could be the cause

**Comment by l0co** [comment] 2020-12-21 09:01
I don't know. I'm just reporting not working `@MicronautTest`.

**Comment by jameskleeh** [comment] 2020-12-22 19:33
@l0co I would need a sample app to look into this

**Comment by ikarsokolov** [comment] 2020-12-23 22:25
Same issue here with Micronaut 2.2.1 (default generated app from mn CLI) and Kotlin 1.4.10-1.4.20.

Sometime changes to code (especially annotations) lead to bean injection failures and other oddities. Happens with unit tests and application restarts.

`gradle clean` always fixes the issue.

IDE setup is not the cause since problem manifests from `gradle test` too.

Possibly caused by Kotlin annotation processor [bug](https://youtrack.jetbrains.com/issue/KT-40493).

**Comment by graemerocher** [comment] 2020-12-24 15:38
@Happy-Neko please provide an example

**Comment by graemerocher** [comment] 2020-12-24 15:39
but yes that bug hopefully will improve the situation for Kotlin code that is compiled incrementally

**Comment by ttzn** [comment] 2020-12-26 13:23
@Happy-Neko what is your Gradle wrapper version ? I had the exact same issues and they were solved by upgrading from `6.7-rc-3` to `6.7` (see #4277).

**Comment by l0co** [comment] 2021-01-05 12:39
@jameskleeh I cannot share the project, unfortunately.

@Happy-Neko Thanks for the hint with gradle clean, I'm going to try it.

BTW. I have gradle 6.7 and the problem is present in this version.

**Comment by jeffscottbrown** [comment] 2021-01-06 14:31
> I have gradle 6.7 and the problem is present in this version.

Do you have incremental compilation enabled in your `build.gradle` with anything like this?

```
micronaut {
    runtime("netty")
    processing {
        incremental(true)
        annotations("com.example.*")
    }
}
```

**Comment by l0co** [comment] 2021-01-14 12:19
I have incremental  annotations processing enabled, however I was waiting a long time for them to work with kotlin and previously had it disabled and at the time I had this problem with tests as well.

I doesn't seem to be related to incremental annotations for me. When I bump into this problem, it's enough for me to change any method name to get rid of this. It's very weird.

**Comment by l0co** [comment] 2021-01-14 12:39
~~However, it seems it's gradle problem, because `./gradlew --no-build-cache cleanTest` helps for me.~~

[EDIT]: Actually, `--rerun-tasks` option helps, not cleaning the cache.

**Comment by graemerocher** [comment] 2021-01-14 15:21
@l0co it seems worthy of a Gradle issue report

**Comment by l0co** [comment] 2021-02-03 11:45
Just for the record, also removing `project/.gradle` helps for this problem, as well as `--rerun-tasks`. `clean`, `cleanTest`, `--no-build-cache` doesn't work.

**Comment by graemerocher** [comment] 2021-02-19 15:45
@l0co is this still an issue with latest Kotlin/KAPT/Micronaut?

**Comment by l0co** [comment] 2021-02-22 07:10
It happens from time to time but I don't believe this has any relation to kotlin/kapt/micronaut, but it's pure gradle problem.

**Comment by graemerocher** [comment] 2021-02-22 08:16
@l0co have you reported an issue to the Gradle issue tracker?

**Comment by l0co** [comment] 2021-02-22 08:39
@graemerocher No, I have a workaround. After my experience with kotlin/kapt I feel driving this bug to be solved with gradle team is a task for someone who has inordinate amount of free time :)

**Comment by l0co** [comment] 2021-02-22 08:56
I have upgraded gradle 6.7 -> 6.8.2. We will see if the bug is still there over time.

**Comment by jameskleeh** [comment] 2021-05-19 13:25
Closing this as I don't see a path forward for us to do anything about it

**Closed as completed by jameskleeh** 2021-05-19 13:25 UTC
Labels: status: awaiting feedback

**Comment by l0co** [comment] 2021-05-20 07:45
I haven't seen it for some time.
