### ISSUE TITLE
Create federation not working properly

### ISSUE THREAD

**Issue by volnei** [micronaut-projects/micronaut-core#548] opened 2018-08-30 23:09 UTC
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Command
``` 
mn create-federation myfederation --services users,posts,comments --stacktrace --features security-jwt,hibernate-gorm 
```

### Expected Behaviour

Create a federation

### Actual Behaviour

Doesn't create a federation, throws an exception

### Environment Information

- OS
```
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
```

- Micronaut version
```
 Micronaut Version: 1.0.0.M4
 JVM Version: 1.8.0_181
```

StackTrace

```
| Error Error occurred running Micronaut CLI: null (NOTE: Stack trace has been filtered. Use --verbose to see entire trace.)
java.lang.NullPointerException
	at io.micronaut.cli.profile.commands.AbstractCreateCommand$_addDependentFeatures_closure17.doCall(AbstractCreateCommand.groovy:571)
	at io.micronaut.cli.profile.commands.AbstractCreateCommand.addDependentFeatures(AbstractCreateCommand.groovy:571)
	at io.micronaut.cli.profile.commands.AbstractCreateCommand.populateFeatures(AbstractCreateCommand.groovy:544)
	at io.micronaut.cli.profile.commands.AbstractCreateCommand.evaluateFeatures(AbstractCreateCommand.groovy:477)
	at io.micronaut.cli.profile.commands.AbstractCreateCommand.handle(AbstractCreateCommand.groovy:272)
	at io.micronaut.cli.profile.commands.CreateFederationCommand.handle(CreateFederationCommand.groovy:92)
	at io.micronaut.cli.MicronautCli.executeCommand(MicronautCli.groovy:351)
	at io.micronaut.cli.MicronautCli.execute(MicronautCli.groovy:234)
	at io.micronaut.cli.MicronautCli.main(MicronautCli.groovy:175)
| Error Error occurred running Micronaut CLI: null

```

**Comment by jameskleeh** [comment] 2018-08-31 21:34
Duplicate of https://github.com/micronaut-projects/micronaut-core/issues/509

**Closed by jameskleeh** 2018-08-31 21:34 UTC
Labels: closed: duplicate
