### ISSUE TITLE
This issue is re-occurring with 1.2.0.RC2

### ISSUE THREAD

**Issue by juliuskrah** [micronaut-projects/micronaut-core#1925] opened 2019-07-23 16:04 UTC
This issue is re-occurring with 1.2.0.RC2

_Originally posted by @juliuskrah in https://github.com/micronaut-projects/micronaut-core/issues/1848#issuecomment-514275337_

**Comment by jameskleeh** [comment] 2019-07-23 16:06
Duplicate of https://github.com/micronaut-projects/micronaut-core/issues/1848

**Closed by jameskleeh** 2019-07-23 16:06 UTC
Labels: closed: duplicate
