### ISSUE TITLE
Infrequent errors when opening websockets: "java.util.NoSuchElementException: websocket-upgrade-handler"

### ISSUE THREAD

**Issue by jchambers** [micronaut-projects/micronaut-core#7920] opened 2022-08-29 20:21 UTC
### Expected Behavior

Netty pipelines are assembled in a deterministic order and expected handlers are always found when attempting to insert handlers in positions relative to other handlers in the pipeline.

### Actual Behaviour

In about 1 in every 250 requests, we see an error message in our logs like the following:

```
2022-08-28 17:09:57,069 [default-nioEventLoopGroup-3-17] ERROR io.micronaut.http.server.netty.websocket.NettyServerWebSocketUpgradeHandler - Error opening WebSocket: websocket-upgrade-handler
java.util.NoSuchElementException: websocket-upgrade-handler
	at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1073)
	at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:248)
	at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:237)
	at io.micronaut.http.server.netty.websocket.NettyServerWebSocketUpgradeHandler.lambda$channelRead0$2(NettyServerWebSocketUpgradeHandler.java:184)
	at reactor.core.publisher.LambdaMonoSubscriber.onNext(LambdaMonoSubscriber.java:171)
	at io.micronaut.reactive.reactor.instrument.ReactorSubscriber.onNext(ReactorSubscriber.java:57)
	at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107)
	at io.micronaut.reactive.reactor.instrument.ReactorSubscriber.onNext(ReactorSubscriber.java:57)
	at reactor.core.publisher.MonoSubscribeOn$SubscribeOnSubscriber.onNext(MonoSubscribeOn.java:146)
	at io.micronaut.reactive.reactor.instrument.ReactorSubscriber.onNext(ReactorSubscriber.java:57)
	at reactor.core.publisher.MonoPublishOn$PublishOnSubscriber.run(MonoPublishOn.java:181)
	at io.micronaut.reactive.reactor.instrument.ReactorInstrumentation.lambda$null$0(ReactorInstrumentation.java:62)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:96)
	at io.netty.util.concurrent.PromiseTask.run(PromiseTask.java:106)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
```

### Steps To Reproduce

Unclear! Given the low frequency, my two suspicions are:

1. A race condition where the client sends data while the pipeline is still being constructed?
2. An exception somewhere else in the pipeline prevents the websocket upgrade handler from being added as expected?

On the latter: we don't see any other suspicious entries in our logs around the times of these `NoSuchElementExceptions`.

### Environment Information

- Operating system: Ubuntu 20.04.4
- Java:
  ```
  $ java --version
  openjdk 17.0.2 2022-01-18
  OpenJDK Runtime Environment Temurin-17.0.2+8 (build 17.0.2+8)
  OpenJDK 64-Bit Server VM Temurin-17.0.2+8 (build 17.0.2+8, mixed mode, sharing)
  ```

### Version

3.5.0 (upgrading to 3.6.1 now)

**Comment by yawkat** [comment] 2022-08-30 11:46
I can see the potential for a race condition in the code, but it looks *very* awkward to trigger. Essentially, it would involve a somewhat long-running `HttpFilter`, and some action that modifies the channel pipeline while that http filter hasn't completed. I can think of two causes:

- The client closes the connection before the http filter completes, clearing the channel handlers. This would mean that the client is unaffected by this error, since the connection is closed anyway.
- The client sends some additional data (maybe the first websocket frame?) *before* it gets the handshake response. I'm not sure if this is in compliance with the spec. This could lead to failures on the client side when this error happens, that should be observable. (a malicious client could do this to trigger the error too, but I doubt you have one of those)

So I want to ask, what client are you using (just web browsers?) and are you seeing corresponding errors on the client? If this is just an error that accompanies the channel closing, we can simply suppress the error, but if the client expects a functioning websocket, then the fix will be more difficult.

A test case to reproduce this would also help, but I imagine that's difficult. However, a pcap of the error would probably be just as good. You can capture a pcap by configuring `micronaut.server.netty.pcap-logging-path-pattern: /tmp/pcap/{localAddress}-{remoteAddress}-{qualifier}-{random}-{timestamp}.pcap`. There will be an `encapsulated` and, in case of http, a `ssl-decapsulated` pcap made for every connection. I would need both for the connection that is failing. Note that the pcap is a full connection log, so it would contain any sensitive information that is sent over the socket.

**Comment by gram-signal** [comment] 2022-08-30 16:14
@yawkat is `AuthenticationProvider` an HTTP filter?  We do some remote, async calls in our `AuthenticationProvider` out to a Redis instance that stores rate limiting information; I'm wondering if that might be what's allowing this race to happen.  Something like:

- client connects
- server starts async redis call to check connection rate limiting
- client disconnects
- async redis returns, `AuthenticationProvider` returns
- race condition hit?

**Comment by yawkat** [comment] 2022-08-30 16:18
yes that is a likely explanation

**Closed as completed** 2022-08-31 16:15 UTC

**Comment by jchambers** [comment] 2022-08-31 23:53
Awesome; will try out the changes from #7927 when 3.6.2 is available and report back!

**Comment by jchambers** [comment] 2022-09-09 21:01
Following up: #7927 did, indeed, solve the problem. Thanks for tackling it so quickly!
