### ISSUE TITLE
Checkstyle Is Too Restrictive With Copyright Header

### ISSUE THREAD

**Issue by jeffbrown** [micronaut-projects/micronaut-core#188] opened 2018-05-24 17:44 UTC
Because of the way the template at https://github.com/micronaut-projects/micronaut-core/blob/f6917a0f18bc526867b6d699eb4f1db117b926ed/config/HEADER#L1 is written, Checkstyle will complain about a missing header if the copyright doesn't include exactly `2017-2018`.  It shouldn't be a requirement that the copyright include that particular year range.

**Comment by jeffbrown** [comment] 2018-05-29 05:29
> Checkstyle doesn't complain about the missing header but about an empty line after the header.

I don't agree that Checkstyle doesn't complain about the missing header.  It does complain about the missing header if the copyright date isn't `2017-2018`.  This is because the template defines the date to be that and if that date isn't present, Checkstyle doesn't recognize the copyright header so it complains that it is missing.  Change a copyright date in a file from `2017-2018` and you will see Micronaut complain that the header does not exist:

    Missing header in: spring/src/main/java/io/micronaut/spring/beans/MicronautBeanProcessor.java

**Comment by ilopmar** [comment] 2018-05-29 07:55
I think we have two different topics here:
- The first one is the year in the copyright header. I'm not an expert about this so I took a look at Griffon and what Andres was doing was defining the variable with a range and then, every January 1st (or 2nd or 3rd) he updates the new year (e.g: from `2017-2018` to `2017-2019`), executes the `licenseFormat` task so all the files are updated with the new year and then he commits those changes.
I though that this was ok and that's why I did it like this. If this is not what we want then I think it's going to be complicated to use the plugin because it applies the same header to the files and I think we can't have different years because we only have one template for the header.

- Besides that we have the checkstyle thing. Checkstyle only complains about the license header if the license is there and there is no empty line after the license header. If there is no license header or there is with an empty line after it, it doesn't complain. Checkstyle doesn't check for a specific license and it doesn't know about the gradle-license plugin we're using. If fact there are other files with other licenses and it doesn't complain about them (check these exclusions: https://github.com/micronaut-projects/micronaut-core/blob/master/gradle/license.gradle#L18-L26).
I've done different tests and I can't reproduce the behavior you see about checkstyle. If I change the year in `MicronautBeanProcessor.java` from `2017-2018` to `2018` and execute `./gradlew spring:checkstyleMain`, then checkstyle doesn't complain about the file. 
This is the only checkstyle violation I have, I don't know how to get the "Missing header" error you showed. I've tried with both gradle taks and IntelliJ checkstyle plugin and nothing new happened.

So, as a summary I think we should discuss about these two topics separately. I submitted the PR #193 to disable the checkstyle check for empty line after the header but Graeme mentioned that it seems a good idea to have that empty line after the header, so I think we should close the PR without merging it.

**Comment by jeffbrown** [comment] 2018-05-31 18:27
> I've done different tests and I can't reproduce the behavior you see about checkstyle.

@ilopmar I can reproduce the behavior...

```
micronaut-core master $ ./gradlew spring:clean spring:check

> Task :spring:compileJava 
Note: Creating bean classes for 1 type elements
Note: /Users/jeffbrown/projects/micronaut-core/spring/src/main/java/io/micronaut/spring/core/env/PropertyResolverAdapter.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

Missing header in: spring/src/main/java/io/micronaut/spring/beans/MicronautBeanProcessor.java

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.6/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 2s
15 actionable tasks: 4 executed, 11 up-to-date



micronaut-core master $ git diff
diff --git a/spring/src/main/java/io/micronaut/spring/beans/MicronautBeanProcessor.java b/spring/src/main/java/io/micronaut/spring/beans/MicronautBeanProcessor.java
index db40d42bb..f22bdb087 100644
--- a/spring/src/main/java/io/micronaut/spring/beans/MicronautBeanProcessor.java
+++ b/spring/src/main/java/io/micronaut/spring/beans/MicronautBeanProcessor.java
@@ -1,5 +1,5 @@
 /*
- * Copyright 2017-2018 original authors
+ * Copyright 2019 original authors
  *
  * Licensed under the Apache License, Version 2.0 (the "License");
  * you may not use this file except in compliance with the License.
@@ -128,4 +128,3 @@ public class MicronautBeanProcessor implements BeanFactoryPostProcessor, Disposa
         this.environment = environment;
     }
 }
-
```

Notice the `Missing header...` message.

There is something surprising going on with the relevant dirty checking because if I run `./gradlew spring:clean spring:check` over and over I don't see the error.  If I change the source file and then run `./gradlew spring:clean spring:check` the error will be reported the first time and not on subsequent runs until I change the source file again.

**Comment by ilopmar** [comment] 2018-06-04 09:32
I've been able to reproduce it. Also if instead of modifying the source file again you `rm -rf .gradle` and run the task again, the `Missing header...` message is displayed again.

I've also found that the warning message it's not because of checkstyle but license plugin. Running:

```
ivan@nobita ~/workspaces/micronaut/micronaut-core $ rm -rf .gradle/
ivan@nobita ~/workspaces/micronaut/micronaut-core $ ./gradlew spring:license
Missing header in: spring/src/main/java/io/micronaut/spring/beans/MicronautBeanProcessor.java

BUILD SUCCESSFUL in 6s
1 actionable task: 1 executed
```
Shows again the `Missing header...` message.

And regarding PR #193 I think we should reject it because it's not related with these issues.

**Comment by graemerocher** [comment] 2018-08-09 15:16
Don't think this is valid anymore, so closing. If there are still issues here let us know

**Closed by graemerocher** 2018-08-09 15:16 UTC
