### ISSUE TITLE
Http response wrong headers

### ISSUE THREAD

**Issue by d3bt3ch** [micronaut-projects/micronaut-core#4962] opened 2021-02-19 19:58 UTC
The Controller

```
@Controller(value = "/about", produces = MediaType.APPLICATION_JSON)
public class AboutController extends BaseController {

    /**
     * ctor
     *
     * @param executor
     */
    public AboutController(@Named(TaskExecutors.IO) Executor executor) {
        super(executor);
    }

    @Get(uris = {"", "/"}, produces = MediaType.APPLICATION_JSON)
    public CompletableFuture<HttpResponse<String>> index() {

        return CompletableFuture.supplyAsync(() -> {

            return HttpResponse
                    .ok()
                    .body(JSON_STRING);

        }, executor()).exceptionally(e -> {

                    // log error

                    // return
                    return HttpResponse
                            .serverError()
                            .body(JSON_STRING);
                }

        ).thenApply(m -> m);
    }
}
```

The response headers

```
Content-Type: text/plain;charset=ISO-8859-1
Transfer-Encoding: chunked
....
```

Even tried to set the `contentType` `contentEncoding` `characterEncoding` on the `HttpResponse` object but with no luck.

**Comment by mattmoss** [comment] 2021-06-04 22:00
Are you using something other than netty? (i.e. Tomcat, Jetty, or Undertow)

**Comment by mattmoss** [comment] 2021-06-04 22:20
Duplicate of https://github.com/micronaut-projects/micronaut-servlet/issues/157

**Closed as completed** 2021-06-09 01:17 UTC
Labels: closed: duplicate
