### ISSUE TITLE
Websocket returns 404

### ISSUE THREAD

**Issue by ejohnsonw** [micronaut-projects/micronaut-core#924] opened 2018-11-18 01:44 UTC
I have an application that I want to communicate both via HTTP and websockets. Declared class as
```
@ServerWebSocket("/kafka/{topic}/{username}")
@Singleton
@KafkaListener(offsetReset = OffsetReset.EARLIEST)
class KafkaProxyServer {
//....

}
```
Client built with **socket.io** is configured to connect to:
http://10.0.0.7:8050/kafka/flight_search/7bef9687-7cda-43b4-a45c-58f16a60ad3a

And it gets a 404 response, it works with other websocket server implementations.

### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce
Checked out sample provided for micronaut and ran, also returns 404 out of the box.

### Expected Behaviour
1) Client can connect to socket server, no 404 and 
2) Have a setting in application yml that allows to determine what port will be used by websocket, so it can coexist with http endpoints in the application

### Actual Behaviour

Client cannot connect.

### Environment Information

- **Operating System**: MAC OS
- **Micronaut Version: 1.0.0
- **JDK Version:1.8.182

### Example Application

Please use micronaut websocket sample.

**Comment by ejohnsonw** [comment] 2018-11-20 02:18
Hi @graemerocher probably need to split this in 2 one is an improvement (being able to define a port) the other I believe is a bug, because you get 404s, e.g. tried Micronaut Sample Websocket application, same behavior.

Please let me know if should open another one.

**Comment by graemerocher** [comment] 2018-11-20 07:02
Not sure what you are referring to? If you are referring to https://github.com/micronaut-projects/micronaut-examples/tree/master/websocket-chat

Seems to work fine. How does one reproduce the 404 you refer to?

As for the port, the same port as the HTTP server is used for WebSocket. There is no separate port for websocket. The client must simply send an appropriate upgrade request.

**Comment by ejohnsonw** [comment] 2018-11-20 15:45
Correct, that is what I used to test: I just downloaded zip file of the project, I assume 'master' is correct. Just tested after the last update you did. I turned on logging.

<img width="1101" alt="screen shot 2018-11-20 at 10 35 53 am" src="https://user-images.githubusercontent.com/1215773/48784332-766c2c00-ecb0-11e8-810c-b6f8866c5911.png">


10:35:51.422 [nioEventLoopGroup-1-9] DEBUG i.m.h.server.netty.NettyHttpServer - Server localhost:8080 Received Request: GET /
10:35:51.423 [nioEventLoopGroup-1-9] DEBUG i.m.h.s.netty.RoutingInBoundHandler - Matching route GET - /
10:35:51.423 [nioEventLoopGroup-1-9] DEBUG i.m.h.s.netty.RoutingInBoundHandler - No matching route found for URI / and method GET
10:35:51.423 [nioEventLoopGroup-1-9] DEBUG i.m.h.s.netty.RoutingInBoundHandler - Matched route GET - /
10:35:51.439 [nioEventLoopGroup-1-10] DEBUG i.m.h.server.netty.NettyHttpServer - Server localhost:8080 Received Request: GET /style.css
10:35:51.439 [nioEventLoopGroup-1-10] DEBUG i.m.h.s.netty.RoutingInBoundHandler - Matching route GET - /style.css
10:35:51.440 [nioEventLoopGroup-1-11] DEBUG i.m.h.server.netty.NettyHttpServer - Server localhost:8080 Received Request: GET /websocketDemo.js
10:35:51.440 [nioEventLoopGroup-1-10] DEBUG i.m.h.s.netty.RoutingInBoundHandler - No matching route found for URI /style.css and method GET
10:35:51.440 [nioEventLoopGroup-1-11] DEBUG i.m.h.s.netty.RoutingInBoundHandler - Matching route GET - /websocketDemo.js
10:35:51.440 [nioEventLoopGroup-1-11] DEBUG i.m.h.s.netty.RoutingInBoundHandler - No matching route found for URI /websocketDemo.js and method GET
10:35:51.440 [nioEventLoopGroup-1-11] DEBUG i.m.h.s.netty.RoutingInBoundHandler - Matched route GET - /websocketDemo.js
10:35:51.440 [nioEventLoopGroup-1-10] DEBUG i.m.h.s.netty.RoutingInBoundHandler - Matched route GET - /style.css
10:35:51.486 [nioEventLoopGroup-1-12] DEBUG i.m.h.server.netty.NettyHttpServer - Server localhost:8080 Received Request: GET /ws/chat/stuff/fred
10:35:51.486 [nioEventLoopGroup-1-12] DEBUG i.m.context.DefaultBeanContext - Resolved existing bean [io.micronaut.http.server.exceptions.HttpStatusHandler@51957152] for type [interface io.micronaut.http.server.exceptions.ExceptionHandler] and qualifier [<HttpStatusException,Object>]
10:35:51.487 [nioEventLoopGroup-1-12] DEBUG i.m.h.s.netty.RoutingInBoundHandler - Encoding emitted response object [WebSocket Not Found] using codec: io.micronaut.jackson.codec.JsonMediaTypeCodec@169da7f2
10:35:58.798 [pool-1-thread-4] DEBUG i.m.context.DefaultBeanContext - Resolved existing bean [io.micronaut.health.HeartbeatTask@bcb09a6] for type [class io.micronaut.health.HeartbeatTask] and qualifier [null]
10:35:58.799 [pool-1-thread-4] DEBUG i.m.c.e.ApplicationEventPublisher - Publishing event: io.micronaut.health.HeartbeatEvent[source=io.micronaut.http.server.netty.NettyEmbeddedServerInstance@5f78de22]
10:35:58.799 [pool-1-thread-4] DEBUG i.m.context.DefaultBeanContext - Resolving beans for type: <HeartbeatEvent> io.micronaut.context.event.ApplicationEventListener 

JDK I'm using 8.0.172-zulu on Mac.

The same behavior happens when I point my client to a purposed build application using @ServerWebSocket annotation. It gets 404s

I was looking to migrate a websocket application I have using another java library, so this is NOT high priority.

**Comment by ejohnsonw** [comment] 2018-11-20 15:50
Hmm, weird
It fails when I run from InteliJ, I do **gradlew run** it works perfectly

**Comment by graemerocher** [comment] 2018-11-20 15:50
probably you don't have annotation processing enabled

**Comment by ejohnsonw** [comment] 2018-11-20 15:59
Yes that was it.

**Comment by sdelamo** [comment] 2019-02-25 17:01
I am closing this issue because I think it was an issue with annotation processing being enabled which is documented here: https://docs.micronaut.io/latest/guide/index.html#ideSetup

**Closed by sdelamo** 2019-02-25 17:01 UTC
Labels: relates-to: websockets, status: under consideration, type: improvement
