### ISSUE TITLE
http.services doesn't inherit http.client.timeout configs 

### ISSUE THREAD

**Issue by ivyazmitinov** [micronaut-projects/micronaut-core#1884] opened 2019-07-10 15:34 UTC
### Steps to Reproduce

1. Create an app with `http.client.read-timeout: 2h`
2. Create a service like `http.services.test-bug-service` with no timeout configs
3. Create a `@Client` for service
4. Invoke a method of such a client

### Expected Behaviour

Configs for `DefaultHttpClient` are used

### Actual Behaviour

Default timeout configs are used.

It is also possible to observe used configs by setting a breakpoint at `io.micronaut.http.client.interceptor.HttpClientIntroductionAdvice` and  looking at resloved `io.micronaut.http.client.HttpClient` for declarative client: it is using instance of `io.micronaut.http.client.ServiceHttpClientConfiguration`, which created via `io.micronaut.context.annotation.EachProperty` have no relation to `io.micronaut.http.client.DefaultHttpClientConfiguration`

### Environment Information

- **Micronaut Version:** 1.2.0.RC2

### Example Application

- TODO: link to github repository with example that reproduces the issue

https://github.com/ivyazmitinov/micronaut-http-client-bug

**Comment by ivyazmitinov** [comment] 2019-07-10 16:05
Such a functionality is implied at https://docs.micronaut.io/latest/guide/index.html#clientConfiguration, IMO, as it first shows config for default client, and then states "If you wish to have a separate configuration per client...".
So, if such a feature wasn't planned, it is better to reword documentation to avoid confusion.

**Comment by jameskleeh** [comment] 2019-10-17 19:45
A newer issue that was opened describes the request more generally, so I'll close this as a duplicate of https://github.com/micronaut-projects/micronaut-core/issues/1884

**Closed by jameskleeh** 2019-10-17 19:45 UTC
Labels: status: under consideration
