### ISSUE TITLE
Running from Gradle or Maven build should enable development environment

### ISSUE THREAD

**Issue by musketyr** [micronaut-projects/micronaut-core#2764] opened 2020-02-07 15:41 UTC
### Steps to Reproduce

1. Create a new application
2. Run the application using the build tool

### Expected Behaviour

The new application should start in the development environment.

### Actual Behaviour

The application is running without any environment selected.

### Environment Information

- **Operating System**: Darwin
- **Micronaut Version:** 1.3.0
- **JDK Version:** Java 8

### Example Application

This is a line one must add to Gradle build to run in development:

```
run.systemProperty('micronaut.environments', 'development')
```

**Comment by musketyr** [comment] 2020-02-07 16:17
As a consequence, if the `development` environment is missing then there should be at least one environment present - `production`.

**Comment by jameskleeh** [comment] 2020-02-07 16:43
Duplicate of https://github.com/micronaut-projects/micronaut-core/issues/2417

**Comment by jameskleeh** [comment] 2020-02-07 16:43
I don't think we're going to be opinionated about this and have a default environment, but per the linked issue I think we will support defining a default environment

**Closed by jameskleeh** 2020-02-07 16:43 UTC

**Comment by musketyr** [comment] 2020-02-07 17:40
ok, thanks for letting me know
