### ISSUE TITLE
OpenAPI error with Kotlin

### ISSUE THREAD

**Issue by nkiesel** [micronaut-projects/micronaut-core#1456] opened 2019-03-28 19:27 UTC
### Steps to Reproduce

1. create app for kotlin with swagger
2. set `kotlinVersion` to `1.3.21` in `gradle.properties`
2. try to compile

Solution for me is to change `@Info` to `Info` in `Application.kt`.  I see the correctly generated swagger YAML after that.

```shell
lt-nkiesel:~/work/Micronaut% mn --version                                                     
| Micronaut Version: 1.1.0.RC2
| JVM Version: 1.8.0_212
lt-nkiesel:~/work/Micronaut% mn create-app api --lang=kotlin --features=swagger-kotlin
| Generating Kotlin project...
| Application created at /home/nkiesel/work/Micronaut/api
lt-nkiesel:~/work/Micronaut% cd api 
lt-nkiesel:~/work/Micronaut/api% perl -p -i -e 's/(kotlinVersion)=.+/$1=1.3.21/' gradle.properties
lt-nkiesel:~/work/Micronaut/api% gradle run

> Task :kaptGenerateStubsKotlin FAILED
e: /home/nkiesel/work/Micronaut/api/src/main/kotlin/api/Application.kt: (11, 6): Expecting an element

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':kaptGenerateStubsKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
1 actionable task: 1 executed
lt-nkiesel:~/work/Micronaut/api% perl -p -i -e 's/\@Info/Info/' /home/nkiesel/work/Micronaut/api/src/main/kotlin/api/Application.kt
lt-nkiesel:~/work/Micronaut/api% gradle run                                                                                        

> Task :run
12:21:32.972 [main] INFO  io.micronaut.runtime.Micronaut - Startup completed in 769ms. Server Running: http://localhost:8080
<===========--> 85% EXECUTING [6s]
> :run
^C%
lt-nkiesel:~/work/Micronaut/api% cat build/tmp/kapt3/classes/main/META-INF/swagger/api-0.0.yml 
openapi: 3.0.1
info:
  title: api
  version: "0.0"
lt-nkiesel:~/work/Micronaut/api% 
```

**Comment by puneetbehl** [comment] 2019-04-11 09:16
Duplicate of micronaut-projects/micronaut-profiles#110

**Closed** 2019-04-11 09:17 UTC
Labels: closed: duplicate, lang: kotlin, relates-to: open-api, type: bug
