### ISSUE TITLE
CLI "create-app --features=spock --build=maven" not working.

### ISSUE THREAD

**Issue by witek1902** [micronaut-projects/micronaut-core#439] opened 2018-07-26 05:18 UTC
### Steps to Reproduce

1. Run command:
```
$ mn create-app spock-example --features=spock --build=maven
```
Output:
```
Resolving dependencies..
............................
|Application created at C:\asclab\asclab-micronaut-poc\spock-example
```

### Expected Behaviour

Generate Maven project with Spock tests and configuration in pom.xml for run Spock tests.

### Actual Behaviour

Generate Maven project with empty java folder in test resources.
![Project](https://i.imgur.com/y0V9ZAa.png)
I add controller with CLI: `mn create-controller HelloController`
With result:
```
|Rendered template Controller.java to destination src\main\java\spock\example\HelloController.java
|Rendered template ControllerSpec.groovy to destination src\test\groovy\spock\example\HelloControllerSpec.groovy
```
And run `mvn test`:
```
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building spock-example 0.1
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ spock-example ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 2 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.7.0:compile (default-compile) @ spock-example ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ spock-example ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory C:\asclab\asclab-micronaut-poc\spock-example\src\test\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.7.0:testCompile (default-testCompile) @ spock-example ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ spock-example ---
[INFO] No tests to run.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.788 s
[INFO] Finished at: 2018-07-26T07:16:31+02:00
[INFO] Final Memory: 10M/245M
[INFO] ------------------------------------------------------------------------
```

### Environment Information

- **Operating System**: Windows 10 Version 1803 (OS Build 17134.165)
- **Micronaut Version:** 1.0.0.M3
- **JDK Version:** 1.8.0_152

**Comment by ZacharyKlein** [comment] 2018-07-30 03:55
@graemerocher I have a sample Maven project here (built with a WIP version of the CLI), with Spock set up. I am unable to get Spock to run the Micronaut tests succesfully. Currently I get errors when I attempt to run a simple test that makes use of the embedded server and application context.
 
Sample project here. https://github.com/ZacharyKlein/maven-spock-micronaut/tree/master - I suspect the issue is on my end, as I don't know Maven very well.  Once I have an example of a working Maven/Spock build with Micronaut I can fix this issue immediately.

**Comment by benrhine** [comment] 2019-11-20 18:53
The above mentioned issues will be fixed in a future release once PR micronaut-projects/micronaut-profiles#201 is merged. In addition to the pr I have explained more on some older configs updates in the thread here https://github.com/micronaut-projects/micronaut-kafka/issues/12. If you feel that any of the explanations or the pr does not satisfy your questions please feel free to re-open.

**Closed by benrhine** 2019-11-20 18:53 UTC
Labels: relates-to: cli, type: bug
