### ISSUE TITLE
Kotlin constructor injection ignores default value

### ISSUE THREAD

**Issue by asarkar** [micronaut-projects/micronaut-core#1872] opened 2019-07-09 05:23 UTC
A bean with a default constructor argument should be interpreted as "inject the dependency if it exists, else use the default value". However, currently, the default value is ignored and the application fails to start.

JDK: OpenJDK 64-Bit Server VM Zulu11.31+11-CA (build 11.0.3+7-LTS, mixed mode)
Micronaut: 1.2.0.RC1
Kotlin: 1.3.41

**Comment by asarkar** [comment] 2019-07-14 06:36
@jameskleeh I contend that this is a bug, not an enhancement. Default arguments is a Kotlin language feature; ignoring it and later fixing it is hardly an enhancement.

**Comment by graemerocher** [comment] 2019-07-14 08:36
Whilst that is true the root cause of the problem is that Kapt (the annotation processing tool for Kotlin) does not expose information about default arguments for Kotlin so from the Micronaut perspective this issue is not fixable with our current implementation 

Theoretically it would be possible to write a native Kotlin compiler plugin but that is a much larger piece of work that this issue falls under hence why it is categorized as an enhancement 

The alternative is to just close the issue as “won’t fix” if that is what you prefer

**Comment by asarkar** [comment] 2019-07-14 08:44
@gramerocher Thanks for your response. If I preferred closing the issue, obviously I’d not have taken the time to create it in the first place. Why is it that often times OSS maintainers start acting like sovereign kings?

**Comment by graemerocher** [comment] 2019-07-14 10:42
Apologies if you feel that is the case. I think our interaction is at an end

**Comment by jameskleeh** [comment] 2019-07-16 15:56
Duplicates https://github.com/micronaut-projects/micronaut-core/issues/1530

**Closed by jameskleeh** 2019-07-16 15:56 UTC
Labels: lang: kotlin, relates-to: native-kotlin, type: enhancement

**Comment by asarkar** [comment] 2019-07-16 16:40
@jameskleeh are you sure that this is a dup? I didn’t see anything in 1530 about default values.

**Comment by jameskleeh** [comment] 2019-07-16 17:08
@asarkar https://github.com/micronaut-projects/micronaut-core/issues/1530#issuecomment-482781406
