### ISSUE TITLE
Servlet 3.1 Support

### ISSUE THREAD

**Issue by bjfish** [micronaut-projects/micronaut-core#1013] opened 2018-12-07 17:13 UTC
It would be nice to be able to run Micronaut using Servlet 3.1.

I was interested in trying MN on App Engine SE Java 8 runtime where it seems like the fast startup and low memory of Micronaut would be a good fit for AppEngine: https://cloud.google.com/appengine/docs/standard/java/runtime-java8

**Comment by mdirkse** [comment] 2018-12-26 10:31
I'm also interested in running Micronaut on App Engine Standard which, as I understand it, basically meand bring Able to run it on Jetty.
I'd like to help out. @graemerocher any pointers on where I can start?

**Comment by graemerocher** [comment] 2018-12-26 10:36
We do have plans to at some point implement Servlet support. Contributions are of course welcome, but an implementation is a non-trivial task. 

The following classes would need re-implementing on top of the Servlet API:

https://github.com/micronaut-projects/micronaut-core/tree/master/http-server-netty/src/main/java/io/micronaut/http/server/netty

Servlet 4.x doesn't support Netty's `ByteBuf` interface but does allow working with native `ByteBuffer` instances. The main logic that would need re-implementing is 

https://github.com/micronaut-projects/micronaut-core/blob/master/http-server-netty/src/main/java/io/micronaut/http/server/netty/RoutingInBoundHandler.java#L358

It is of course technically possible, but by my estimates it would probably take at least a month or 2 someone working full time.

**Comment by mdirkse** [comment] 2018-12-26 10:52
Would there be some way to run Micronaut on AE standard without doing this? Like running Netty inside a servlet container for instance?

**Comment by graemerocher** [comment] 2018-12-26 11:30
Possibly, not sure how that could be achieved

**Comment by jameskleeh** [comment] 2019-08-01 18:36
Duplicate of https://github.com/micronaut-projects/micronaut-core/issues/1002

**Closed by jameskleeh** 2019-08-01 18:36 UTC
Labels: status: under consideration, type: enhancement
