### ISSUE TITLE
Views not found (404) when running from .jar file with view/handlebars.

### ISSUE THREAD

**Issue by mphouston** [micronaut-projects/micronaut-core#881] opened 2018-11-09 12:07 UTC
When displaying page that renders a handlebars view from a .jar file, the view is not found (404).  This is probably only a problem when the app is run on a Windows platform.

This issue is similar to one found with Thymeleaf: [753](https://github.com/micronaut-projects/micronaut-core/issues/753)

Pull request [859](https://github.com/micronaut-projects/micronaut-core/pull/859)  submitted.

### Task List

- [X] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [X] Example that reproduces the problem uploaded to Github
- [X] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create app: mn create-app test --features groovy
2. Add handlebars/views support
```
 compile "io.micronaut:micronaut-views"
 compile "com.github.jknack:handlebars:4.1.0"
```
3. Start Application
```
gradlew runShadow
```
4. Browse to http://localhost:8080/

### Expected Behaviour

The page will be displayed.

### Actual Behaviour

An Http 404 status is returned.

### Environment Information

- **Operating System**: Windows 7
- **Micronaut Version:** 1.0.0
- **JDK Version:** 1.8.0_191

### Example Application

- Example: [https://github.com/mphouston/mn-issue-view-jar](https://github.com/mphouston/mn-issue-view-jar)

### Comments
The page works fine when the application is run using the normal run command:
```
gradlew run
```

**Comment by sdelamo** [comment] 2018-11-12 11:45
I am not able to reproduce the error with the sample repository. 

I've cloned the repo and executed `gradlew runShadow`and I was able to access `http://localhost:8080`. 

![issue881](https://user-images.githubusercontent.com/864788/48345628-d04d7000-e678-11e8-8616-510c86503954.gif)


@mphouston any idea what I am missing to reproduce the issue?

**Comment by mphouston** [comment] 2018-11-12 12:12
I think you need to run this on a Windows server.  The FILE_SEPARATOR on linux/IOS is '/', which works fine from .jar files.  When the JVM sets the FILE_SEPARATOR to '\', then the .jar resource loader can't find the views.

Thanks for looking into this.  I am glad you posted the video.  I never would have guessed the server OS.

**Comment by sdelamo** [comment] 2018-11-12 15:42
There is a related PR: https://github.com/micronaut-projects/micronaut-core/pull/859

**Comment by jameskleeh** [comment] 2018-12-22 02:34
Fixed by https://github.com/micronaut-projects/micronaut-core/commit/789e712fbfb9158c3d234f61a6ee4905f72fad80

**Closed by jameskleeh** 2018-12-22 02:34 UTC
Labels: relates-to: views, type: bug
