### ISSUE TITLE
Problem running (or testing with JUnit) HelloWorld application within Eclipse GUI

### ISSUE THREAD

**Issue by nbuubuu** [micronaut-projects/micronaut-core#714] opened 2018-10-10 13:10 UTC
Hello,

I experienced "page not found" problems when I launch the HelloWorld application within Eclipse GUI (whereas with gradle command line everything works fine). Using these tutorials : 
http://guides.micronaut.io/creating-your-first-micronaut-app/guide/index.html
https://docs.micronaut.io/latest/guide/index.html#creatingClient

In order to work within Eclipse GUI I had to remove the 'shadow' gradle plugin from the build.gradle.
And I had to add the "/" path in the @Get annotation value attribute of the HelloClient hello method.

### Task List

- [x] Steps to reproduce provided
- [] Stacktrace (if present) provided
- [] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. mn create-app com-demo-app --build gradle --features java,junit
2. follow the tutorial : http://guides.micronaut.io/creating-your-first-micronaut-app/guide/index.html
3. run the test with Eclipse GUI, by right clicking on the HelloControllerTest.java and choosing "Run as -> Junit Test". => fail (maybe shadow gradle plugin)
4. follow the tutorial to create a client : https://docs.micronaut.io/latest/guide/index.html#creatingClient
5. run the application by right clicking on the Application.java and choosing "Run as -> Java application".
6. open a web browser (or use curl) and put http://localhost:8080/hello/ => "page not found" (maybe shadow gradle plugin and 'missing' "/" path in @Get HelloClient method annotation.)

### Expected Behaviour
Tests should have succeed.
'Hello world' should have been printed on the web browser.

### Actual Behaviour
Running JUnit test within Eclipse fails.
Calling the service within web browser indicates : "page not found".

### Environment Information

- **Operating System**: Ubuntu 18.04
- **Micronaut Version:** 1.0.0.RC2
- **JDK Version:** 1.8.0_181
- **Eclipse:**  2018-09 (4.9.0) Eclipse Java EE IDE for Web Developers. Build id: 20180917-1800
- **Java version:** 1.8.0_181

**Comment by graemerocher** [comment] 2018-10-10 13:47
Did you follow the instructions to setup an appropriate version of Eclipse as per https://docs.micronaut.io/latest/guide/index.html#ideSetup ?

**Comment by nbuubuu** [comment] 2018-10-10 13:56
I ran "gradle eclipse" before importing the project into Eclipse.

**Comment by graemerocher** [comment] 2018-10-10 13:56
Yes, but do you have the necessary plugins installed as per the linked IDE setup instructions?

**Comment by nbuubuu** [comment] 2018-10-10 13:59
This plugin ? :

Buildship: Eclipse Plug-ins for Gradle	2.2.1.v20180125-1441	org.eclipse.buildship.feature.group	Eclipse Buildship

**Comment by graemerocher** [comment] 2018-10-10 14:09
Works fine for me. I am using:

```
Eclipse SDK
Version: 4.9
Build id: I20180730-0800
Buildship: Eclipse Plug-ins for Gradle	2.2.1.v20180125-1441	org.eclipse.buildship.feature.group	Eclipse Buildship
```

You need Eclipse 4.9 or above

**Comment by graemerocher** [comment] 2018-10-10 15:01
Interesting, will take a look.. thx

**Comment by graemerocher** [comment] 2018-10-11 07:16
Thanks for the report.. the "No value available for annotation member" was a bug when using the Eclipse compiler. This will be resolved in RC3

**Closed** 2018-10-11 07:15 UTC
Labels: closed: cannot reproduce, status: awaiting feedback

**Comment by ballcoach12** [comment] 2020-07-16 18:52
I am having a similar issue with running JUnit tests in Eclipse. The error I get is:

`org.junit.jupiter.engine.execution.ConditionEvaluationException: Failed to evaluate condition [io.micronaut.test.extensions.junit5.MicronautJunit5Extension]: @MicronautTest used on test but no bean definition for the test present. This error indicates a misconfigured build or IDE. Please add the 'micronaut-inject-java' annotation processor to your test processor path (for Java this is the testAnnotationProcessor scope, for Kotlin kaptTest and for Groovy testCompile). See the documentation for reference: https://micronaut-projects.github.io/micronaut-test/latest/guide/
	at org.junit.jupiter.engine.execution.ConditionEvaluator.evaluationException(ConditionEvaluator.java:81)
	at org.junit.jupiter.engine.execution.ConditionEvaluator.evaluate(ConditionEvaluator.java:69)
	at org.junit.jupiter.engine.execution.ConditionEvaluator.lambda$evaluate$0(ConditionEvaluator.java:55)
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(Unknown Source)
	at java.util.stream.Streams$ConcatSpliterator.tryAdvance(Unknown Source)
	at java.util.stream.Streams$ConcatSpliterator.tryAdvance(Unknown Source)
	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.findFirst(Unknown Source)
	at org.junit.jupiter.engine.execution.ConditionEvaluator.evaluate(ConditionEvaluator.java:57)
	at org.junit.jupiter.engine.descriptor.JupiterTestDescriptor.shouldBeSkipped(JupiterTestDescriptor.java:202)
	at org.junit.jupiter.engine.descriptor.JupiterTestDescriptor.shouldBeSkipped(JupiterTestDescriptor.java:57)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$checkWhetherSkipped$2(NodeTestTask.java:115)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.checkWhetherSkipped(NodeTestTask.java:115)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:77)
	at java.util.ArrayList.forEach(Unknown Source)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.util.ArrayList.forEach(Unknown Source)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:229)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:197)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:211)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:191)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:137)
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestReference.run(JUnit5TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)
Caused by: org.junit.jupiter.api.extension.TestInstantiationException: @MicronautTest used on test but no bean definition for the test present. This error indicates a misconfigured build or IDE. Please add the 'micronaut-inject-java' annotation processor to your test processor path (for Java this is the testAnnotationProcessor scope, for Kotlin kaptTest and for Groovy testCompile). See the documentation for reference: https://micronaut-projects.github.io/micronaut-test/latest/guide/
	at io.micronaut.test.extensions.junit5.MicronautJunit5Extension.evaluateExecutionCondition(MicronautJunit5Extension.java:100)
	at org.junit.jupiter.engine.execution.ConditionEvaluator.evaluate(ConditionEvaluator.java:64)
	... 54 more

`

I have set up the IDE according to instructions, but I'm not sure how to resolve this problem.

**Comment by PyvesB** [comment] 2021-12-19 18:28
Hello 👋🏻  I'm getting the same error as @ballcoach12, I've opened a new detailed report here: https://github.com/micronaut-projects/micronaut-test/issues/498
