### ISSUE TITLE
DuplicateRouteException when using two Controller uris

### ISSUE THREAD

**Issue by johndevs** [micronaut-projects/micronaut-core#10957] opened 2024-07-08 15:53 UTC
### Expected Behavior

When I create two end-points like this:

```java
@Get(uris = { "/foo", "/bar" }
public String method1(){ ... }

@Get(uris = { "/one", "/two" }
public String method2(){ ... }
```

And call /foo then I expect `method1()` to be executed.

I would also expect if there is an error with duplicate routing that the error log would include the controller class and method names for easier debugging.

### Actual Behaviour

Instead I get DuplicateRouteException thrown from the `Router#findClosest(request)` with the message:

`More than 1 route matched the incoming request. The following routes matched /: GET - /, GET - /`

From this message it is not clear which controller methods are conflicting nor is the error correct. 

Apparently the Router only considers the `uri` parameter, not `uris`.

### Version

4.2.2

**Comment by ersalazar** [comment] 2024-07-11 15:51
Hello; can I work on this?

**Comment by yawkat** [comment] 2024-07-11 16:10
sure

**Comment by pragyamutluru** [comment] 2024-07-18 09:02
Hi @ersalazar , are you working on this?
I was also planning to start on it.

Should we throw a new exception (such as MultipleRouteException) which communicates a more succinct message?

**Comment by graemerocher** [comment] 2024-07-18 12:41
better error messages are always good

**Comment by ersalazar** [comment] 2024-07-18 14:41
Hello @pragyamutluru, yes I'm working on it. I know its been a bit long but I ran into an issue where I couldnt run the project locally but that was fixed yesterday in this PR https://github.com/micronaut-projects/micronaut-core/pull/10990

**Comment by ersalazar** [comment] 2024-07-18 17:01
I'm trying to replicate the error in version 4.6.x but it seems to be fixed. When I try to go to version 4.2.x where this error was reported I get the same dependency error that was patched in 4.6.x with PR https://github.com/micronaut-projects/micronaut-core/pull/10990 Can anyone help me with this?

**Comment by ersalazar** [comment] 2024-07-19 16:00
@yawkat can you help me with this?

**Comment by yawkat** [comment] 2024-07-22 09:01
I think the easiest way would be to try reproducing this bug outside micronaut-core, where #10990 does not apply. That can help narrow down whether this issue existed in 4.2.x.

**Comment by pragyamutluru** [comment] 2024-07-23 16:52
I am also unable to reproduce the issue with 4.6.x and with 4.2.x.
@johndevs  if you could please provide us with dependency list, that would be great!

**Comment by yawkat** [comment] 2024-07-24 10:12
Thanks for testing. I will close this issue for now. @johndevs please provide a test case.

**Comment by johndevs** [comment] 2024-07-31 13:00
Thanks everyone for testing!

We did quite a big migration from `4.2.2` to `4.5.1` and now I cannot either reproduce this issue anymore. So something in some version in-between has fixed it for sure. Or it was some transient dependency that was updated in the process that was causing issues.

Anyway, sorry to bother you all with testing an old version; but great to see such an active team working on Micronaut! :beers:

**Comment by johndevs** [comment] 2024-08-21 09:12
@yawkat I have managed to reproduce the issue now on 4.5.1 as well.

Attached a minimal test-case. I would expect the test in the project to pass.


[duplicate-uris-test-case.zip](https://github.com/user-attachments/files/16689272/duplicate-uris-test-case.zip)

**Comment by yawkat** [comment] 2024-09-02 08:25
Thanks for the reproducer. I think it still uses the default value for `uri` even though you have an explicit `uris` parameter.

**Closed as completed** 2024-10-09 08:51 UTC
Labels: type: bug, info: good first issue

**Comment by johndevs** [comment] 2024-12-18 13:20
:partying_face:
