### ISSUE TITLE
Regression in Jackson serialization, nested classes broken in graalvm native

### ISSUE THREAD

**Issue by piizei** [micronaut-projects/micronaut-core#6910] opened 2022-02-12 12:50 UTC
### Expected Behavior

After upgrading from 3.0.0M5 I noticed that nested bean jackson serialization has been broken in 3.3.1 when using nativeCompile

Example application should return same JSON structure as both Java and GraalVM native.

### Actual Behaviour

With following structure:

```
@Introspected
data class Top(
    val a: String,
    val b: Int,
    val nested: Set<Nested>
)

@Introspected
data class Nested(
    val c: String = "",
    val d: Int = 0,
)
```

When serializing `"[{\"a\":\"avalue\",\"b\":3, \"nested\": [{\"c\":\"cvalue\",\"d\":5}]}]"`

Example application returns with Java:

```
[{"a":"avalue","b":3,"nested":[{"c":"cvalue","d":5}]}]
```

And with GraalVM native:

```
[{"a":"avalue","b":3,"nested":[{"d":0}]}]
```

### Steps To Reproduce

Checkout the example project.  Created with following command:
- mn create-app --features=graalvm,reactor bug --build=gradle --lang=kotlin
- mn create-controller bug

Call endpoint http://localhost:8080/bug with both Java and GraalVM native

### Environment Information

- JDK 17 / GraalVM 22.0.0.2 Java 17 CE
- M1 OSX

### Example Application

https://github.com/piizei/micronaut-bug

### Version

3.3.1

**Comment by timyates** [comment] 2022-02-15 12:56
Hiya!  Thanks for the report!

Removing the default values from `Nested` seems to fix the issue... i.e:

```
@Introspected
data class Nested(
    val c: String,
    val d: Int
)
```

Not sure why the issue is occurring though...  I'll keep looking

**Comment by timyates** [comment] 2022-02-15 13:17
Found it!

This is a duplicate of https://github.com/micronaut-projects/micronaut-core/issues/6534

Due to a change in Kapt https://youtrack.jetbrains.com/issue/KT-47908

Not sure what we can do here, apart from wait until we have an alternative to Kapt

**Closed as completed by timyates** 2022-02-15 13:17 UTC
Labels: lang: kotlin, relates-to: graal
