### ISSUE TITLE
Compile fails in Kotlin with needs Nullable even if defaultValue provided in QueryValue

### ISSUE THREAD

**Issue by wdroste** [micronaut-projects/micronaut-core#1911] opened 2019-07-19 21:12 UTC
mn --version
| Micronaut Version: 1.2.0.RC2
| JVM Version: 1.8.0_212

Kotlin 1.3.41

### Steps to Reproduce

Create a Controller with the following method.

```
  @Get("/{?snapshot}")
  @Produces(MediaType.APPLICATION_JSON)
  fun index(@QueryValue(defaultValue="false" snapshot: Boolean): List<MyDTO> {
    return myService.invokeMethod(snapshot)
  }
```

Compile Error

```
.....//ConnectorsController.java:17: error: The uri variable [snapshot] is optional, but the corresponding method argument [boolean snapshot] is not defined as an Optional or annotated with the javax.annotation.Nullable annotation.
    public final java.util.List<MyDTO> index(@io.micronaut.http.annotation.QueryValue(defaultValue = "false")
```

### Expected Behavior

The expected behavior is to honor the default value. Basically since the default value is provided, the argument 'snapshot' should never be null, therefore I should not need to specify the Nullable annotation or change the type to Optional.

### Actual Behavior
The annotation processor fails to build the proper code.

**Comment by jameskleeh** [comment] 2019-07-21 00:47
Duplicate of https://github.com/micronaut-projects/micronaut-core/issues/1866. Fixed in the snapshot

**Closed by jameskleeh** 2019-07-21 00:47 UTC
Labels: closed: duplicate
