### ISSUE TITLE
Controller @Header JSR-303 Validation Not Performed

### ISSUE THREAD

**Issue by brianwyka** [micronaut-projects/micronaut-core#2285] opened 2019-10-31 10:21 UTC
When creating a controller method, `@Post`, `@Put`, etc... when adding a validation to a `@Header` field (whether it is optional or required) results in no validation being performed.

### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a `@Controller`
2. Add a `@Post` method which takes in `@Header` and `@Body` fields
3. Add a validation annotation next to `@Header` such as `@Digits(integer = 2, fraction = 0)`

### Expected Behaviour

The header should be validated just like request parameter `@Parameter`,  query value `@QueryValue`, or request body `@Body`

### Actual Behaviour

No JSR-303 validation is performed

### Environment Information

- **Operating System**: Linux
- **Micronaut Version:** `1.2.2`
- **JDK Version:** `1.8`

### Example Application

```java
    @Post(value = "/proxies/{name}", consumes = MediaType.TEXT_PLAIN)
    public Single<HttpResponse> createProxy(@Header("Timeout") @Digits(integer= 2000, fraction = 0) final long timeout,
                                            @Parameter final String name,
                                            @Body @NotEmpty final String proxy) {
...
}
```

**Comment by jameskleeh** [comment] 2019-10-31 13:13
Can you verify the same behavior exists in 1.2.5?

**Comment by brianwyka** [comment] 2019-11-02 13:51
The behavior didn't work in `1.2.5` either. 

There might be some funky business going on with the `@Nullable` and `Optional` handling as well...

In this example, the `Optional` works, but the validation does not.
```java
@Header("Timeout") @Digits(integer= 2000, fraction = 0) final Optional<Long> timeout
```

In this example, the `@Nullable` does not work with `Long` value.  Did not try with `String`.  Also, the validation does not trigger.
```java
@Nullable @Header("Timeout") @Digits(integer= 2000, fraction = 0) final Long timeout
```

**Comment by jameskleeh** [comment] 2019-11-04 16:23
I can't reproduce. Please upload an example project that reproduces the issue

**Comment by jameskleeh** [comment] 2019-11-07 20:55
Closing until feedback is received

**Closed by jameskleeh** 2019-11-07 20:55 UTC
Labels: closed: cannot reproduce
