### ISSUE TITLE
Getting compile error running tests in IntelliJ

### ISSUE THREAD

**Issue by tsgautier** [micronaut-projects/micronaut-core#2173] opened 2019-09-29 16:43 UTC
### Steps to Reproduce

1. Make a change to a test file (add a blank line, doesn't matter what change)
2. Run the test in IntelliJ by clicking the green triangle in the test file
3. Note that the first test run gives error
4. Press run again (without changes) 
5. Note that the second run (without changes) suceeds

### Expected Behaviour

Test should run without failure every time.

### Actual Behaviour

On each change of a file and then running the test, the following error is given:

```
Testing started at 9:38 AM ...
> Task :cleanTest
> Task :compileJava UP-TO-DATE
> Task :processResources UP-TO-DATE
> Task :classes UP-TO-DATE
> Task :compileTestJava FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':compileTestJava'.
> Not a valid class name: example.micronaut.
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org
BUILD FAILED in 406ms
4 actionable tasks: 2 executed, 2 up-to-date
```

After running the test one time, the test can be re-run and it works without failure.

### Environment Information

- **Operating System**: OS X
- **Micronaut Version:** 1.2.3
- **JDK Version:** 1.8.0_151
- **IntelliJ Version:** Ultimate 2019.2.3

### Example Application

- https://github.com/tsgautier/micronaut-test.git

**Comment by graemerocher** [comment] 2019-10-09 10:02
Workaround is to downgrade to Gradle 5.3 by updating `gradle/gradle-wrapper.properties`. I have reported https://github.com/gradle/gradle/issues/10985 which is the issue in Gradle that causes this.

**Comment by jameskleeh** [comment] 2019-10-09 16:52
Duplicate of https://github.com/micronaut-projects/micronaut-core/issues/2207

**Closed by jameskleeh** 2019-10-09 16:52 UTC
Labels: closed: duplicate
