### ISSUE TITLE
Declarative http client: Using JacksonFeatures: DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES causes JsonError parsing error

### ISSUE THREAD

**Issue by StephenOTT** [micronaut-projects/micronaut-core#2386] opened 2019-11-21 22:19 UTC
Micronaut 1.2.6
Kotlin 1.3.50

Consider:

```kotlin
@Client("\${formValidatorService.host}")
@JacksonFeatures(
   enabledDeserializationFeatures = [FAIL_ON_IGNORED_PROPERTIES, FAIL_ON_NULL_FOR_PRIMATIVES, FAIL_ON_UNKNOWN_PROPERTIES
)
interface FormValidatorServiceClient {

    @Post("/validate")
    fun validate(@Body validationRequest: Single<FormSubmission>): Single<HttpResponse<ValidationResponseValid>>

}
```

When the validate function throws a error such as the HttpClientResponseException, someone under the hood of Micronaut, the error handling is trying to pass the response body into a `JsonError` type.  When the Client is configured to throw errors for unknown properties (typical use case where api contract is strict), the client will throw a non-blocking error related to its inability to parse the response body (a `application/json` response) into the JsonError.

**Comment by yawkat** [comment] 2022-05-16 13:18
Can't reproduce this anymore, I first thought this might have been fixed by #6850, but from testing it worked before that already, probably fixed by #5935

**Closed by yawkat** 2022-05-16 13:18 UTC
Labels: status: awaiting validation
