### ISSUE TITLE
Assets not loading when static-resources mapping is '/'

### ISSUE THREAD

**Issue by weesftw** [micronaut-projects/micronaut-core#8190] opened 2022-10-19 14:18 UTC
### Expected Behavior

Apply the mapping of static-resources with some content, example: `/foo` and be able to access the page with the assets loaded.

### Actual Behaviour

When I map the property `micronaut.router.static-resources.swagger-ui.mapping` with the value `/foo` and access `http://localhost:8080/foo` it does not load the page assets (css and js) just a white page and the browser's debug console shows that the resources were not found. But when I do the mapping with `/foo/**` and accessing `http://localhost:8080/foo/` it works but is not the expected behavior. My [application.yml](https://github.com/weesftw/micronaut-multi-module-openapi/blob/master/main/src/main/resources/application.yml) configuration can be found in the test repository.

- Note: this problem started to show with the 3.7.x bump, before (3.6.4 version) applying the `/foo` mapping worked normally.

### Steps To Reproduce

1. Start application in [main](https://github.com/weesftw/micronaut-multi-module-openapi/tree/master/main) module.
2. See: http://localhost:8080/foo 

### Environment Information

- Java 11 

### Example Application

https://github.com/weesftw/micronaut-multi-module-openapi

### Version

3.7.2

**Comment by altro3** [comment] 2024-02-18 09:56
@weesftw  If you have context path for your application or set different path to swagger-ui, you also need to tell about it to micronaut-openapi annotation processor, because you changed path to javascript / css resource-files. Look here: https://micronaut-projects.github.io/micronaut-openapi/latest/guide/index.html#swaggerui

![изображение](https://github.com/micronaut-projects/micronaut-starter/assets/48474279/9401a853-5fd0-444f-b228-f85f6c073db0)

You just need to add value to `openapi.properties` in your case:
```properties
swagger-ui.js.url=demo/swagger-ui
```

**Comment by altro3** [comment] 2024-02-18 09:56
@graemerocher you can close it. It's not a bug

**Closed as completed** 2024-02-18 11:31 UTC
Labels: closed: notabug
