### ISSUE TITLE
Generate CLI app with correct main class name (was: CLI command stopped working when app is assembled)

### ISSUE THREAD

**Issue by sascha-frinken** [micronaut-projects/micronaut-core#474] opened 2018-08-06 09:39 UTC
I am currently playing around with the `CLI profile (picocli)` on latest snapshot. The app stopped working when assembled and called via `java -jar …`. Running the app as `Application` from my IntelliJ IDE still works.

### Steps to Reproduce
* create an app with profile  `cli` enabled 
* create a command
* assemble app
* call jar
```
$ mn create-app my-cli-app --profile cli
Generating Java project...
| Application created at /tmp/my-cli-app
$ cd my-cli-app/
$ mn
| Starting interactive mode...
| Enter a command name to run. Use TAB for completion:
mn> create-command test
| Rendered template Command.java to destination src/main/java/my/cli/app/TestCommand.java
| Rendered template CommandTest.java to destination src/test/java/my/cli/app/TestCommandTest.java

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.8/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 4s
11 actionable tasks: 10 executed, 1 up-to-date
$ java -jar build/libs/my-cli-app-0.1-all.jar -v
11:14:05.005 [main] INFO  io.micronaut.runtime.Micronaut - No embedded container found. Running as CLI application

```   
### Expected Behaviour
CLI command is called and shows `Hi!`

### Actual Behaviour
CLI command is not invoked instead the message: 
`INFO  io.micronaut.runtime.Micronaut - No embedded container found. Running as CLI application` shows up

### Environment Information

- **Operating System**: Linux 4.17.11-200.fc28.x86_64 
- **Micronaut Version:** 1.0.0.BUILD-SNAPSHOT
- **JDK Version:** 1.8.0_171

### Example Application
n/a

**Comment by graemerocher** [comment] 2018-08-07 08:26
@remkop Any ideas on this one?

**Comment by remkop** [comment] 2018-08-07 10:01
Yes, I believe this is because the main class in the `build.gradle` file in the generated application is still pointing to `Application`. 


Before building the project, open the `gradle.build` file, and change the `mainClassName` line to:

```
mainClassName = "my.cli.app.TestCommand"
```

Now, when you rebuild the project and start the application, it should work as expected.

FYI, there is work in progress to improve this so that the `build.gradle` for a generated CLI app has the correct main class name. Hopefully this can make it into the next micronaut release. (@graemerocher  is there a timeline?)

**Comment by graemerocher** [comment] 2018-08-07 10:02
Thursday we will do the next release

**Comment by remkop** [comment] 2018-08-07 10:03
ok. I'll hurry. :-)

**Comment by sascha-frinken** [comment] 2018-08-07 10:12
Thank you guys! 
Just let me know if you want me to close the issue.

**Comment by remkop** [comment] 2018-08-07 10:16
First: did that solve the issue?

**Comment by remkop** [comment] 2018-08-07 10:47
Let's leave it open. I will rename this issue and reference it from my PR for creating CLI apps with the correct main class set.

**Comment by remkop** [comment] 2018-08-07 10:49
Oops, I cannot rename it. Anyway, I'll reference it from the PR.

**Comment by sascha-frinken** [comment] 2018-08-07 10:53
Just let me know how you want the issue to be named and I'll do that for you.

**Comment by remkop** [comment] 2018-08-07 10:54
How about "Generate CLI app with correct main class name (was: CLI command stopped working when app is assembled)" ?

**Comment by remkop** [comment] 2018-08-07 10:55
Thank you!

**Comment by remkop** [comment] 2018-08-08 04:01
@graemerocher Status update: implementation and testing done; todo: update documentation. I hope to push be able to this tonight.

**Comment by remkop** [comment] 2018-08-08 11:11
@graemerocher it took a while, but please find PR https://github.com/micronaut-projects/micronaut-core/pull/480 and PR https://github.com/micronaut-projects/micronaut-profiles/pull/59 that address this issue.

**Comment by remkop** [comment] 2018-08-08 11:25
@graemerocher That was fast! :-) Did you also merge the accompanying micronaut-profiles PR https://github.com/micronaut-projects/micronaut-profiles/pull/59 ? (They need to go together)

**Comment by remkop** [comment] 2018-08-08 11:45
I now see both PRs are merged. Thanks!

**Comment by mOo7King** [comment] 2018-09-24 11:08
Any solution for same issue but in maven project?

My dependencies are the following:


<dependencies>


        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-jdk14</artifactId>
            <version>1.7.25</version>
        </dependency>
        <dependency>
            <groupId>javax.annotation</groupId>
            <artifactId>javax.annotation-api</artifactId>
            <version>1.3.2</version>
        </dependency>

        
        <dependency>
            <groupId>io.micronaut</groupId>
            <artifactId>runtime</artifactId>
            <version>1.0.0.M4</version>
        </dependency>
        <dependency>
            <groupId>io.micronaut</groupId>
            <artifactId>http-client</artifactId>
            <version>1.0.0.M4</version>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.11</version>
            <scope>test</scope>
        </dependency>

    </dependencies>

**Comment by remkop** [comment] 2018-09-24 11:53
@mOo7King  Did you generate the app with the `create-cli-app` command?

**Comment by remkop** [comment] 2018-09-24 11:54
@mOo7King  The user manual has more details: https://docs.micronaut.io/latest/guide/index.html#picocliGenerateProject

**Comment by mOo7King** [comment] 2018-09-24 12:59
I followed this (http://guides.micronaut.io/creating-your-first-micronaut-app/guide/index.html) guide but instead of generate a Gradle project I created a new project with that maven dependencies I said before.
In that way I only have two classes: Application.java and HelloController.java.
My purpose was to simply run Application.java in Intellij's IDE and what I expected was the creation of a random port localhost which I would be able to invoke with, for example, postman's application.
What really happens is that when I run the class the following message appears:

 _"io.micronaut.runtime.Micronaut start
INFO: No embedded container found. Running as CLI application"_


------------------------------------------------------------------

**HelloController.java**

`import io.micronaut.http.MediaType;
import io.micronaut.http.annotation.Controller;
import io.micronaut.http.annotation.Get;
import io.micronaut.http.annotation.Produces;

@Controller("/hello") // <1>
public class HelloController {
    @Get("/") // <2>
    @Produces(MediaType.TEXT_PLAIN) // <3>
    public String index() {
        return "Hello World"; // <4>
    }
}`

------------------------------------------------------------------

**Application.java**

`import io.micronaut.runtime.Micronaut;

public class Application {

    public static void main(String[] args) {
        Micronaut.run(Application.class);
    }
}`

------------------------------------------------------------------

**pom.xml**

`<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.microservice</groupId>
    <artifactId>example-micronaut</artifactId>
    <version>1.0-SNAPSHOT</version>

    <dependencies>

        
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-jdk14</artifactId>
            <version>1.7.25</version>
        </dependency>

        
        <dependency>
            <groupId>io.micronaut</groupId>
            <artifactId>runtime</artifactId>
            <version>1.0.0.M4</version>
        </dependency>
        <dependency>
            <groupId>io.micronaut</groupId>
            <artifactId>http-client</artifactId>
            <version>1.0.0.M4</version>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.11</version>
            <scope>test</scope>
        </dependency>

    </dependencies>

</project>`

**Comment by remkop** [comment] 2018-09-26 10:46
@mOo7King Is this still an issue?

**Comment by mOo7King** [comment] 2018-09-26 10:56
@remkop  I decided to generate a Gradle project just like the guide and it worked perfectly. However I need to convert that Gradle project into a Maven one (requirement I need to reach) and as a newbie I don't know how to do that. Any help would be appreciated.

**Comment by remkop** [comment] 2018-09-26 12:37
@mOo7King  I missed your earlier comment. I understand a bit better now. I believe you are commenting on the wrong ticket. This ticket is about creating a command line Micronaut application that uses picocli for command line parsing (so the application can have command line options, subcommands etc.)

What you are looking to do does not require command line parsing.

I am not 100% sure why you are seeing this error

> io.micronaut.runtime.Micronaut start INFO: No embedded container found. Running as CLI application"

...but it seems that you may be missing a dependency in your POM.
The best way to proceed I think is to either raise a separate ticket where you re-state the problem (the comment that starts with "I followed this (http://guides.micronaut.io/creating-your-first-micronaut-app/guide/index.html) guide but ..." is a good text for such a ticket), or start a conversation on https://gitter.im/micronautfw/

**Comment by mOo7King** [comment] 2018-09-26 13:39
@remkop Thank you. I started a new issue: https://github.com/micronaut-projects/micronaut-core/issues/630

**Comment by gavinws** [comment] 2018-10-26 21:21
I hate to bring up an old issue, but I am seeing the same problem happen with the `--build maven` option. This is my first time using Micronaut or PicoCLI. I can see that your changes were not undone after your PRs were merged, so I'm not sure what's up with this unless Micronaut 1.0.0 was built on the wrong changeset or something.

What I did on macOS High Sierra (10.13.6) with Azul Zulu JDK 8 (Java 8u162):

1. Installed SDKMan
2. Installed Micronaut 1.0.0
3. `mn create-cli-app --build maven analyzer`
4. `mvn clean install`
5. `java -jar target/analyzer-0.1.jar -v` (also used `-h` and `--verbose`)

The output is:
```
13:51:15.915 [main] INFO  io.micronaut.runtime.Micronaut - No embedded container found. Running as CLI application
```
Checking the pom.xml I see:
```xml
  <properties>
    <exec.mainClass>analyzer.Application</exec.mainClass>
    <micronaut.version>1.0.0</micronaut.version>
    <jdk.version>1.8</jdk.version>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>
```

After changing mainClass to `<exec.mainClass>analyzer.AnalyzerCommand</exec.mainClass>` and rebuilding, I get the expected output when running it.

**Comment by remkop** [comment] 2018-10-27 05:49
I’ll try if I can reproduce the issue.

**Comment by remkop** [comment] 2018-10-27 09:52
I've been able to reproduce the issue: it works for Gradle but is broken for Maven: the main command is `analyzer.Application` in Maven. Is there some difference in how the tokens in the skeletons are replaced?...

**Comment by ZacharyKlein** [comment] 2018-10-27 23:10
Limited internet connectivity at the moment, but I will look into this early next week and get back to you.

**Comment by jameskleeh** [comment] 2018-11-01 20:48
Fixed by https://github.com/micronaut-projects/micronaut-profiles/commit/2278087944a8747b8845e2fc265289e51200ffc8

**Closed by jameskleeh** 2018-11-01 20:48 UTC

**Comment by remkop** [comment] 2018-11-01 21:37
Thanks @jameskleeh !
