### ISSUE TITLE
BeanDefinitionReference not generated with kapt incremental annotations processing when class interface is changed

### ISSUE THREAD

**Issue by l0co** [micronaut-projects/micronaut-core#3742] opened 2020-07-16 09:20 UTC
In `2.0.0`. 

I'm continuing to chase hotswap problems with kapt, after #3734.

Now, I'm stuck on random `NoSuchBeanException` after I change the class interface. In such a scenario the hotswap fails (and it should). But after restarting the server I frequently stumble upon `NoSuchBeanException`.

It seems, when the class interface changes, and kapt works in incremental annotations processing mode, the annotations aren't processes and generated `BeanDefinitionReference` is empty. I have the following micronaut application:

```java
public class Application {

    public static void main(String[] args) {
        Micronaut.run(Application.class);
    }

}

@Singleton @Validated
public class AutoStartingBean {

	public static final Logger logger = LoggerFactory.getLogger(AutoStartingBean.class);

	@EventListener
	public void start(StartupEvent event) {
		logger.debug("Starting...");
	}

}
```

And generated `BeanDefinitionReference` is:

```
micronaut.general.$AutoStartingBean$ApplicationEventListener$start1$InterceptedDefinitionClass
micronaut.general.$$AutoStartingBeanDefinition$InterceptedDefinitionClass
micronaut.general.$AutoStartingBeanDefinitionClass
```

When I add some method to `Application` and rebuild with `gradle build`, the `BeanDefinitionReference` is missing (in the other project it sometimes is present and contains fewer beans than it should). The curious thing is that when I add a method to `AutoStartingBean`, the `BeanDefinitionReference` file is generated properly again. Otherwise, only `gradle clean` helps.

It seems, because when I change `Application` kapt incremental processing skips processing of `AutoStartingBean`, it is never re-generated by kapt and never gets to `BeanDefinitionReference`. While all previously generated classes are still in the right spot:

```
$ ls build/tmp/kapt3/classes/main/micronaut/general/
AutoStartingBean$ApplicationEventListener$start1$Intercepted.class
$AutoStartingBean$ApplicationEventListener$start1$InterceptedDefinition.class
$AutoStartingBean$ApplicationEventListener$start1$InterceptedDefinitionClass.class
AutoStartingBean$ApplicationEventListener$start1$Intercepted$$proxy0.class
$AutoStartingBeanDefinition.class
$AutoStartingBeanDefinitionClass.class
$AutoStartingBeanDefinition$Intercepted.class
$$AutoStartingBeanDefinition$InterceptedDefinition.class
$$AutoStartingBeanDefinition$InterceptedDefinitionClass.class
$$AutoStartingBeanDefinition$InterceptedDefinition$$exec1.class
$AutoStartingBeanDefinition$Intercepted$$proxy0.class
```

So, the problem is only related to `BeanDefinitionReference` file generator.

I've recorded this problem [here](https://youtu.be/jhXN4H4IPzw). Also, I provide test repository for this problem [here](https://github.com/l0co/micronaut-playground/tree/micronaut-3742).

**Comment by graemerocher** [comment] 2020-07-16 09:47
Might be related to https://github.com/gradle/gradle/issues/13767 although that is Java and in Java's case it fails fast with an error but looks like Kotlin maybe silently swallows the problem

**Comment by graemerocher** [comment] 2020-07-21 10:13
Since this problem doesn't exist in the Java impl it must be an issue with KAPT. Could you report an issue to https://youtrack.jetbrains.com/issues/KT and link it here. Thanks.

**Comment by l0co** [comment] 2020-07-21 10:20
https://youtrack.jetbrains.com/issue/KT-40493

**Comment by l0co** [comment] 2020-10-14 12:42
@graemerocher Unfortunately, they moved the ticket to the backlog without solving it. It currently means that kotlin+linux is generally a bad idea, especially if you use any annotation processing libs. And what is really sad for me it now means that Micronaut+kotlin+linux is generally a bad idea...

Maybe you could push them a bit to debug it?

**Comment by max-kammerer** [comment] 2020-11-09 08:36
During investigation of original issue I've found another one with Gradle Java project (look like regression in Gradle): https://github.com/gradle/gradle/issues/15097

**Comment by graemerocher** [comment] 2020-11-09 08:41
@max-kammerer thanks for the report and I am glad to hear you are investigating this issue :)

**Comment by max-kammerer** [comment] 2020-11-25 11:34
Hi Folks! Fix for this problem is available since `1.4.30-dev-3102` Kotlin compiler build. We would appreciate for any early feedback for this changes.
Compiler plugin could be obtained from  https://oss.sonatype.org/content/repositories/snapshots/ repository

**Comment by graemerocher** [comment] 2020-11-25 13:08
@max-kammerer Thanks that is great news! @l0co could you try out the fix and provide feedback?

**Comment by l0co** [comment] 2020-11-30 13:42
I'm putting the feedback to kotlin ticket.

**Comment by l0co** [comment] 2020-12-01 10:35
It seems it's [fixed](https://youtrack.jetbrains.com/issue/KT-40493#focus=Comments-27-4560145.0-0). I've upgraded the test repo with [this commit](https://github.com/l0co/micronaut-playground/commit/82f486fa7bb534323c860d8c678647cc97ae35de) where you can check it works. However, I'd wait with resolving this ticket to official release. In the meantime I'm going to work a bit with this version in IDE and I'll give a feedback if there's something wrong.

**Comment by graemerocher** [comment] 2020-12-01 11:39
@l0co that is great news! @max-kammerer thanks and I am glad KAPT is getting some attention :)

**Comment by adamkobor** [comment] 2021-02-04 09:00
Kotlin 1.4.30 is out with KT-40493 included. So far I didn't experience the kapt issue from the past, fingers crossed :)

**Closed** 2021-03-11 19:37 UTC
Labels: status: awaiting third-party
