### ISSUE TITLE
Responses Swapped with HTTP/2

### ISSUE THREAD

**Issue by RyanHoldren** [micronaut-projects/micronaut-core#4390] opened 2020-10-26 19:23 UTC
We are experiencing a very strange and elusive issue with HTTP/2. It may be that this is a bug in Netty and not Micronaut but after hours of debugging I am no closer to figure out what is going on.

### Steps to Reproduce

I've put together [an example project](https://github.com/RyanHoldren/micronaut-response-problem) that demonstrates the issue.

1. Run the example project.
2. Go to `https://localhost:8443/` in Chromium or Firefox
3. Open your browser's developer tools
4. Turn on "Disable cache" on the Network tab
5. Refresh the page over and over again until the error occurs.

### Expected Behaviour

The result should look like this **every time**:

![Success](https://user-images.githubusercontent.com/9664712/97217213-280d1500-1784-11eb-83a0-8989247a1988.png)

### Actual Behaviour

Every now and then⁠—perhaps one time in fifty⁠—one of the images will fail to load:

![Fail To Load on Chromium](https://user-images.githubusercontent.com/9664712/97216383-fb0c3280-1782-11eb-82f9-ba94231c5b46.png)

Even more strangely, sometimes the responses will be _swapped_ such that the wrong response is returned to a request. This always occurs in conjunction with a failure.

![Wrong Response on Chromium](https://user-images.githubusercontent.com/9664712/97216502-2c84fe00-1783-11eb-9d3f-4560e1493682.png)

### Environment Information

- **Operating System**: Amazon Linux release 2 (Karoo)
- **Micronaut Version:** 2.1.2
- **Firefox Version:** 78.0.2
- **Chromium Version:** 86.0.4240.75
- **JDK Version:** OpenJDK 64-Bit Server VM AdoptOpenJDK (build 15.0.1+9, mixed mode, sharing)

### Example Application

Here is [an example project](https://github.com/RyanHoldren/micronaut-response-problem) that demonstrates the issue.

My apologies for the manual nature of the example. I tried to write a unit test that would demonstrate the issue but was not able to. Specifically, I tried using Java 9's HTTP Client issuing many requests in parallel, but I couldn't get it to fail.

**Comment by graemerocher** [comment] 2020-10-30 15:45
Still investigating this one, but like you spent several hours on it and it does appear to be a Netty bug. It seems that Netty receives from the browser an event to close the stream but still has data to write so throws an exception but somehow still leaves the write pending. I have added this commit to fix the exception https://github.com/micronaut-projects/micronaut-core/commit/3c13f4eecebcaccab54bba431b28119492f69ffc

But there still appears to be an occasional issue though less frequent, it seems to be that Netty gets into a state whereby this write is left pending and not cleared after the exception and then when a stream ID appears that uses the same ID it is still around so it it sends it out down.

**Comment by RyanHoldren** [comment] 2020-11-02 22:52
Thanks for looking into this, @graemerocher. I am wondering how to proceed. Do you think my example project is suitable evidence for opening a ticket with Netty?

**Comment by yawkat** [comment] 2021-12-06 14:15
The swapping seems plausible if there is some confusion about the HTTP/2 STREAM_ID in the request processing. However I can't reproduce this with 3.2, so I assume this was fixed at some point – there have been many improvements to this code. I will close this, please reopen if this is still an issue.

**Closed as completed by yawkat** 2021-12-06 14:15 UTC
Labels: status: awaiting validation

**Comment by RyanHoldren** [comment] 2021-12-06 16:18
I haven't seen this issue in sometime. You are probably right that it was fixed at some point. Thanks for investigating, @yawkat :)
