### ISSUE TITLE
Memory Leak when using CompletedFileUpload

### ISSUE THREAD

**Issue by rn55** [micronaut-projects/micronaut-core#5259] opened 2021-04-16 11:40 UTC
Hi,
After upgrading Micronaut from 1.3 to 2.4 we noticed memory leak. We use CompletedFileUpload to handle multi-part forms.
To reproduce issue faster, I started server with -Xmx256 arg, after uploading 10-15 files (~30MB each) server crashes:
```
io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 16777216 byte(s) of direct memory (used: 251658247, max: 257425408)
    at io.netty.util.internal.PlatformDependent.incrementMemoryCounter(PlatformDependent.java:776)
    at io.netty.util.internal.PlatformDependent.allocateDirectNoCleaner(PlatformDependent.java:731)
    at io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:645)
    at io.netty.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:621)
    at io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:204)
    at io.netty.buffer.PoolArena.tcacheAllocateNormal(PoolArena.java:188)
    at io.netty.buffer.PoolArena.allocate(PoolArena.java:138)
    at io.netty.buffer.PoolArena.reallocate(PoolArena.java:288)
    at io.netty.buffer.PooledByteBuf.capacity(PooledByteBuf.java:118)
    at io.netty.buffer.AbstractByteBuf.ensureWritable0(AbstractByteBuf.java:307)
    at io.netty.buffer.AbstractByteBuf.ensureWritable(AbstractByteBuf.java:282)
    at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1105)
    at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1098)
    at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1089)
    at io.netty.handler.codec.http.multipart.HttpPostMultipartRequestDecoder.offer(HttpPostMultipartRequestDecoder.java:340)
    at io.netty.handler.codec.http.multipart.HttpPostMultipartRequestDecoder.offer(HttpPostMultipartRequestDecoder.java:52)
    at io.netty.handler.codec.http.multipart.HttpPostRequestDecoder.offer(HttpPostRequestDecoder.java:223)
    at io.micronaut.http.server.netty.FormDataHttpContentProcessor.onData(FormDataHttpContentProcessor.java:113)
```

Sometimes following log from Netty's Leak Detector appears:
```
2021-04-16 11:11:24.228 ERROR i.n.util.ResourceLeakDetector     LEAK: ByteBuf.release() was not called before it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records: 
Created at:
    io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:385)
    io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:187)
    io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:178)
    io.netty.buffer.AbstractByteBufAllocator.buffer(AbstractByteBufAllocator.java:115)
    io.netty.handler.codec.http.multipart.HttpPostMultipartRequestDecoder.offer(HttpPostMultipartRequestDecoder.java:350)
    io.netty.handler.codec.http.multipart.HttpPostMultipartRequestDecoder.offer(HttpPostMultipartRequestDecoder.java:52)
    io.netty.handler.codec.http.multipart.HttpPostRequestDecoder.offer(HttpPostRequestDecoder.java:223)
    io.micronaut.http.server.netty.FormDataHttpContentProcessor.onData(FormDataHttpContentProcessor.java:113)
    io.micronaut.http.server.netty.AbstractHttpContentProcessor.doOnNext(AbstractHttpContentProcessor.java:78)
    io.micronaut.http.server.netty.AbstractHttpContentProcessor.doOnNext(AbstractHttpContentProcessor.java:36)
    io.micronaut.core.async.subscriber.CompletionAwareSubscriber.onNext(CompletionAwareSubscriber.java:52)
    io.micronaut.http.netty.reactive.HandlerPublisher.publishMessage(HandlerPublisher.java:378)
    io.micronaut.http.netty.reactive.HandlerPublisher.channelRead(HandlerPublisher.java:334)
```

The problem also exists when I disable direct memory using flag -Dio.netty.noPreferDirect=true 

```
2021-04-16 11:43:35.485 ERROR i.m.h.s.n.RoutingInBoundHandler   Unexpected error occurred: Java heap space
java.lang.OutOfMemoryError: Java heap space
    at io.netty.util.internal.PlatformDependent.allocateUninitializedArray(PlatformDependent.java:286)
    at io.netty.buffer.PoolArena$HeapArena.newByteArray(PoolArena.java:552)
    at io.netty.buffer.PoolArena$HeapArena.newChunk(PoolArena.java:562)
    at io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:204)
    at io.netty.buffer.PoolArena.tcacheAllocateNormal(PoolArena.java:188)
    at io.netty.buffer.PoolArena.allocate(PoolArena.java:138)
    at io.netty.buffer.PoolArena.reallocate(PoolArena.java:288)
    at io.netty.buffer.PooledByteBuf.capacity(PooledByteBuf.java:118)
    at io.netty.buffer.AbstractByteBuf.ensureWritable0(AbstractByteBuf.java:307)
    at io.netty.buffer.AbstractByteBuf.ensureWritable(AbstractByteBuf.java:282)
    at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1105)
    at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1098)
    at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1089)
    at io.netty.handler.codec.http.multipart.HttpPostMultipartRequestDecoder.offer(HttpPostMultipartRequestDecoder.java:340)
    at io.netty.handler.codec.http.multipart.HttpPostMultipartRequestDecoder.offer(HttpPostMultipartRequestDecoder.java:52)
    at io.netty.handler.codec.http.multipart.HttpPostRequestDecoder.offer(HttpPostRequestDecoder.java:223)
    at io.micronaut.http.server.netty.FormDataHttpContentProcessor.onData(FormDataHttpContentProcessor.java:113)

```
### Steps to reproduce:

1. Sample controller:

```
    @Post("/upload")
    @Consumes(MediaType.MULTIPART_FORM_DATA)
    public HttpResponse<String> upload(String json, CompletedFileUpload file0) {

        System.out.println("Processing multipart request: ");
        System.out.printf("Part json [%s]%n", json);
        System.out.printf("Part file0 [size: %s, type: %s]%n", file0.getSize(), file0.getContentType());

        InputStream stream = null;
        try {
            stream = file0.getInputStream();
            File targetFile = File.createTempFile("test.", ".tmp");
            Files.copy(stream, targetFile.toPath(), StandardCopyOption.REPLACE_EXISTING);
        } catch (IOException e) {
            e.printStackTrace();
        } finally {
            try {
                if (stream != null) {
                    stream.close();
                }
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
        System.out.println("Request completed");
        return HttpResponse.ok();
    }

```

2. Curl script for uploading the file (it can be also reproduced using other clients e.g. postman):

```
curl --location --request POST 'http://localhost/oom/upload' \
--form 'json="{\"test\":\"12345}"' \
--form 'file0=@"test.zip"'
```

3. Starting Micronaut app:

`java -Xmx256m -jar test-all.jar`
or
`java -Dio.netty.noPreferDirect=true -Xmx256m -jar test-all.jar`

### Expected Behaviour

Memory should be released after file is read and stream is closed.

### Actual Behaviour

Memory usage (direct or heap if direct disabled) increases until the server stops accepting requests.

### Environment Information

- **Operating System**: Linux, MacOS
- **Micronaut Version:** 2.4.2
- **JDK Version:** 8

**Comment by rn55** [comment] 2021-04-16 12:42
Problem does not exist in Micronaut 2.0.2, it seems that it appeared in 2.1.0 - this is the first version where I'm able to reproduce it.

**Comment by jameskleeh** [comment] 2021-04-19 16:16
Unfortunately this is a bug in Netty. I will work with them to resolve it

**Comment by jameskleeh** [comment] 2021-04-20 16:52
I reported https://github.com/netty/netty/issues/11174 for this issue

**Comment by rn55** [comment] 2021-04-26 09:48
Hi @jameskleeh, related netty issue 11174 has been closed, what will be next steps to resolve this issue?

**Comment by jameskleeh** [comment] 2021-04-26 13:03
@rn55 The issue is fixed in 63, however that release also includes a terrible performance regression https://github.com/netty/netty/issues/11175. We will need to wait until that is fixed and then we can upgrade

**Comment by rn55** [comment] 2021-05-14 06:07
Hi @jameskleeh, any update on this? When a release is expected?

**Closed as completed** 2021-05-17 16:02 UTC
Labels: type: bug

**Comment by jameskleeh** [comment] 2021-05-17 16:35
@rn55 Likely today
