### ISSUE TITLE
ResourceLeakDetector reports missing ByteBuf.release() call before garbage collection frequently 

### ISSUE THREAD

**Issue by hunsricker** [micronaut-projects/micronaut-core#9677] opened 2023-08-03 15:47 UTC
### Expected Behavior

The _ResourceLeakDetector_ should not report any missing _release()_ calls and the service should not run out of memory.

### Actual Behaviour

The application is a proxy taking POST requests containing JSON, manipulate the string, sending the request to the destination server and just returns the answer to the client.
The service answers about 20k requests per hour and runs out of memory after a day or one and a half.

I built the service using several versions of micronaut 3.9.x and 4.0.x.  

The `ResourceLeakDetector` writes the following message to the logs:
`LEAK: ByteBuf.release() was not called before it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records: 
Created at:
	io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:403)
	io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:188)
	io.netty.buffer.UnsafeByteBufUtil.copy(UnsafeByteBufUtil.java:436)
	io.netty.buffer.PooledUnsafeDirectByteBuf.copy(PooledUnsafeDirectByteBuf.java:216)
...`

### Steps To Reproduce

Unfortunately I didn't make it to reproduce the error locally. Starting the service on my Mac didn't produce the leak messages neither. Running load tests didn't cause the local instance to run out of memory.

So the hints I can offer you to get to the bottom of this behavior are the sample data in the repository:
- different leak messages
- heap dumps of two different service instances ran out of memory
- one hour of flight recording
- the system properties produced by the `jcmd <pid> VM.system_properties_ command

### Environment Information

Operating System	Linux 5.0.0-1035-azure
VM Version	OpenJDK 64-Bit Server VM version 17.0.1+12-39 (Java version 17.0.1+12-39)
OS Architecture	amd64
VM Arguments	-XX:+UseZGC -Xmx256M -Xms256M -Dcom.sun.management.jmxremote.port=7501 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.password.file=/opt/apps/proxy-service/jmxremote.password -Dlog4j.configurationFile=/opt/apps/proxy-service/log4j2.xml -Dmicronaut.config.files=/opt/apps/proxy-service/proxy-service.properties

### Example Application

https://github.com/hunsricker/proxyRunningOutOfMemory/tree/master

### Version

3.9.3, 3.9.4, 4.0.0, 4.0.1

**Comment by yawkat** [comment] 2023-08-03 15:49
can you try running with `-Dio.netty.leakDetection.level=paranoid`? that may make it easier to reproduce

**Comment by hunsricker** [comment] 2023-08-03 16:11
I have one instance started with the `paranoid` value. All of the leak messages except the one in the file `leakDetectionMessage_ByteBuf` are captured running the service with this property.

Any other difference to get when using the `paranoid` value?

**Comment by hunsricker** [comment] 2023-08-03 16:13
deleted my response ... misunderstood your comment. OK, I'll try out ...

**Comment by hunsricker** [comment] 2023-08-04 15:11
**Steps to reproduce**
1. compile using maven (I used 3.9.3)
2. adapt path to the executable files in `runProxy.sh`, `runLoadtest.sh`, `mockDestinationServer`
3. execute `mockDestinationServer`
4. execute `runProxy.sh`
5. execute `runLoadTest.sh` (needs apache jmeter to be installed)

On my Mac it tooks about 25 minutes to get the OutOfMemoryError.

**Comment by yawkat** [comment] 2023-08-07 08:17
oh great it's multipart...

**Comment by yawkat** [comment] 2023-08-07 12:46
Thank you for the reproducer!

**Comment by hunsricker** [comment] 2023-08-07 13:08
you're welcome! Thank you for your quick help. Seems that you found the reason and fixed it ...

**Comment by hunsricker** [comment] 2023-09-04 11:56
Running the reproducer on version 4.0.4 still ends up with an _OutOfMemoryError_. Seems that the bug is not fixed.

> **Steps to reproduce**
> 
>     1. compile using maven (I used 3.9.3)
> 
>     2. adapt path to the executable files in `runProxy.sh`, `runLoadtest.sh`, `mockDestinationServer`
> 
>     3. execute `mockDestinationServer`
> 
>     4. execute `runProxy.sh`
> 
>     5. execute `runLoadTest.sh` (needs apache jmeter to be installed)
> 
> 
> On my Mac it tooks about 25 minutes to get the OutOfMemoryError.

**Comment by hunsricker** [comment] 2023-09-04 14:11
Running the reproducer on version 4.1.0 seems to be stable. Getting warnings in the logs like
`16:00:40.847 [default-nioEventLoopGroup-1-2] WARN  io.netty.util.concurrent.AbstractEventExecutor - A task raised an exception. Task: io.micronaut.http.server.netty.handler.PipeliningServerHandler$StreamingOutboundHandler$$Lambda$642/0x0000000334faf238@36379845
java.lang.IllegalStateException: onComplete before request?
        at io.micronaut.http.server.netty.handler.PipeliningServerHandler$StreamingOutboundHandler.onComplete(PipeliningServerHandler.java:884) ~[proxyrunningoutofmemory-0.1.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[proxyrunningoutofmemory-0.1.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[proxyrunningoutofmemory-0.1.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[proxyrunningoutofmemory-0.1.jar:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[proxyrunningoutofmemory-0.1.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[proxyrunningoutofmemory-0.1.jar:?]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[proxyrunningoutofmemory-0.1.jar:?]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[proxyrunningoutofmemory-0.1.jar:?]
        at java.lang.Thread.run(Thread.java:1623) [?:?]`

but having served more than 1.8 million requests in 80 minutes without failing at least one.

**Comment by graemerocher** [comment] 2023-09-04 14:17
@yawkat perhaps look into the warnings?

**Comment by hunsricker** [comment] 2023-09-07 13:07
Unfortunately two of the eight instances of the services ran again into an _OutOfMemoryError_ within the first nine hours after starting the service ...

**Comment by hunsricker** [comment] 2023-09-25 06:37
are there any new information on this issue?

**Comment by yawkat** [comment] 2023-09-25 06:39
no, i've not looked at it further yet. multipart + proxy is pretty obscure.

**Comment by yawkat** [comment] 2023-10-24 13:03
@hunsricker can you test with the recent pr once there's a release

**Comment by sdelamo** [comment] 2023-11-01 14:31
Closing this for now, @hunsricker let me know if the issue is still happening for you.

**Closed as completed** 2023-11-01 14:30 UTC
Labels: type: bug

**Comment by hunsricker** [comment] 2023-11-27 14:00
I'm sorry for the late answer. Running the proxy service for a couple of days without getting the warning of the leak detector and without running into an OutOfMemoryError.
So, it seems to be fixed with v4.1.6
Thank you for your help

**Comment by yawkat** [comment] 2023-12-04 10:43
thanks!
