### ISSUE TITLE
Allow for 404 handling to be configurable

### ISSUE THREAD

**Issue by stepanv** [micronaut-projects/micronaut-core#2234] opened 2019-10-15 14:07 UTC
Hi,

when using a reactive declarative client:
```

@Client
public interface MyReactiveClient {

    // on 404, Maybe.empty() is returned
    @Get
    Maybe<String> getMyReactiveMaybe();

    // on 404, HttpClientResponseException is thrown
    @Get
    Single<String> getMyReactiveSingle();

    // on 404, HttpClientResponseException is thrown
    @Get
    Observable<String> getMyReactiveObservable();

    // !!! WRONG !!! on 404, Mono.empty() is returned
    @Get
    Mono<String> getMyReactiveMono();
    
    // !!! WRONG !!! on 404, Flux.empty() is returned
    @Get
    Flux<String> getMyReactiveFlux();
}
```

an `404` is either transformed to an "empty" reactive response or an exception is passed to the downstream subscribers.

### Expected Behaviour
In case of `404`, for Reactor `Mono` and `Flux`, I'd expect the same behavior as for ReactiveX `Single` and `Observable`.
That is to pass an exception to the downstream subscribers.

### Actual Behaviour
However, because of `ReactorReactiveClientResultTransformer `, it behaves similarly to ReactiveX `Maybe`. As a result, since there is no other concept than Flux/Mono in Reactor, one has no way to have reactive client based on Reactor where `404` is treated as an error.

I'd say, the `ReactorReactiveClientResultTransformer` (or the functionality it provides) should be either removed completely, or disabled by default and switched on only if a user explicitly likes it in a particular case.

### Workaround
One can disable the `ReactorReactiveClientResultTransformer` thanks to the `Replaces` annotation on a custom `ReactiveClientResultTransformer` implementation that does identity.

**Comment by graemerocher** [comment] 2019-10-15 14:10
I'm not understanding why you believe these 2 cases are "Wrong". Both `Mono` and `Flux` allow empty results hence why no exception is thrown. `Single` on the other hand forbids an empty `Single` hence the exception.

**Comment by stepanv** [comment] 2019-10-15 21:24
Looking at it from the perspective you're describing, I think I understand why you actually implemented the transformer.
However, from the other end, as a user of Reactor, if I wanted to get an error in case of 404, I need to know that it doesn't get propagated as all the other errors, but as an "empty" (e.g., `Mono.switchOnEmpty()`). Furthermore, the payload from the 404 response is discarded, so the explanation what I did wrong as a user is gone.

I would be really happy to understand the reasoning to handle 404 in such unique way. Unfortunately, the documentation is not really explaining why.

https://docs.micronaut.io/latest/guide/index.html#clientError

As a side note, the documentation explicitly states, the declarative client throws an exception in case of 404.

**Comment by stepanv** [comment] 2019-10-16 12:19
Thinking about the `404` behavior, I realized it works almost perfectly for the REST world.

As long as the `404` means the entity does not exist, it makes sense to model it as `null` or `Mono.empty()`. But what if the context path is wrong? In that case it's an exceptional state that needs an exceptional handling.

But in general, for a generic http client (which I believe Micronaut Http Client is) one can use it to do even RPC call. Modeling `404` into a non-exceptional state is quite surprising for me as a user.

Nevermind, now when I think I understand your motivation to design the HTTP client as a REST client, I'm confident the workaround to disable the `ReactorReactiveClientResultTransformer` is the right think to do to have just an HTTP client.

cc @graemerocher

**Comment by graemerocher** [comment] 2019-10-16 14:05
Our motivation is the same as OpenFeigns motivation. See https://github.com/OpenFeign/feign/blob/770b579fd66a773288c7ba4552467f92e63719d3/core/src/main/java/feign/Feign.java#L164

Fundamentally 404 is not seen as an exceptional condition which would/should trigger retry handling. Normally retrying for a 404 is pointless hence the behaviour.


I think we should probably improve the documentation in this area. We could probably make the behaviour configurable like it is in Feign.

**Comment by stepanv** [comment] 2019-10-16 17:43
> The one exception to this rule is HTTP Not Found (404) responses. This exception only applies to the declarative client.

@jameskleeh , I see what you mean. I was reading it: "The HttpClientResponseException only applies to the declarative client" while you're probably reading it "The exception that HttpClientResponseException is not thrown only applies to the declarative client".

Now it all makes sense, thanks for clarification.

**Comment by stepanv** [comment] 2019-10-16 17:47
@graemerocher if it was configurable like Feign is, it would be great! And thanks for Micronaut!

**Comment by jameskleeh** [comment] 2019-10-30 17:11
Duplicate of https://github.com/micronaut-projects/micronaut-core/issues/2193

**Closed by jameskleeh** 2019-10-30 17:11 UTC
Labels: closed: duplicate
