### ISSUE TITLE
Defining multiple @Named @Bean methods returning same type in a @Factory with around advice fails to inject with NonUniqueBeanException

### ISSUE THREAD

**Issue by l0co** [micronaut-projects/micronaut-core#1927] opened 2019-07-24 16:34 UTC
Almost the same as #1097. Now, two beans of the same class with different names work well:

```java
@Factory
public class MyBeanFactory {

	@Bean @Named("bean1")
	public IMyBean bean1() {
		return new MyBean();
	}

	@Bean @Named("bean2")
	public IMyBean bean2() {
		return new MyBean();
	}

}
```

However, according to [the docs](https://docs.micronaut.io/latest/guide/index.html#aroundAdvice) (*AOP Advice on @Factory Beans* chapter) the beans created by the factory can be wrapped with Around Advice. For example `@Validated`:

```java
@Factory
public class MyBeanFactory {

	@Bean @Named("bean1") @Validated
	public IMyBean bean1() {
		return new MyBean();
	}

	@Bean @Named("bean2") @Validated
	public IMyBean bean2() {
		return new MyBean();
	}

}
```

With the above factory injection ends up with `NonUniqueBeanException`.

Please see the example [here](https://github.com/l0co/micronaut-playground/tree/named-factory).

**Comment by l0co** [comment] 2019-07-24 17:19
Also, in the same scenario (proxy around bean created by the factory), for such a declaration:

```java
@Factory
public class MyBeanFactory {

	@Prototype @Validated
	public IMyBean bean1(BeanResolutionContext resolutionContext) {
		return new MyBean();
	}

}
```

Without `@Validated` I have the path accessible in `resolutionContext`, but with `@Validated` the path is empty.

**Comment by jameskleeh** [comment] 2019-07-24 19:10
This is actually a duplicate of https://github.com/micronaut-projects/micronaut-core/issues/1910

**Comment by l0co** [comment] 2019-08-20 05:59
@jameskleeh You have made this ticket a duplicate of #1910 while the fix is [already merged into 1.2.0](https://github.com/micronaut-projects/micronaut-core/issues/1910#issuecomment-522633311).

If so, this is not fixed yet in 1.2.0. I've upgraded the version in my sample and I still have:

```
07:57:11.804 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: Error instantiating bean of type  [micronaut.general.AutoStartingBean]

Message: Multiple possible bean candidates found: [micronaut.general.IMyBean, micronaut.general.IMyBean]
Path Taken: AutoStartingBean.myBean1
io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [micronaut.general.AutoStartingBean]

Message: Multiple possible bean candidates found: [micronaut.general.IMyBean, micronaut.general.IMyBean]
Path Taken: AutoStartingBean.myBean1
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1555)
	at io.micronaut.context.DefaultBeanContext.getScopedBeanForDefinition(DefaultBeanContext.java:2017)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:1919)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1892)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1021)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForField(AbstractBeanDefinition.java:1379)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForField(AbstractBeanDefinition.java:1152)
	at micronaut.general.$AutoStartingBeanDefinition.injectBean(Unknown Source)
	at micronaut.general.$AutoStartingBeanDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1535)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2248)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:1917)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1892)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:577)
	at io.micronaut.context.DefaultBeanContext$BeanExecutionHandle.getTarget(DefaultBeanContext.java:2769)
	at io.micronaut.context.DefaultBeanContext$BeanExecutionHandle.invoke(DefaultBeanContext.java:2790)
	at io.micronaut.aop.chain.AdapterIntroduction.intercept(AdapterIntroduction.java:81)
	at io.micronaut.aop.MethodInterceptor.intercept(MethodInterceptor.java:40)
	at io.micronaut.aop.chain.InterceptorChain.proceed(InterceptorChain.java:150)
	at micronaut.general.AutoStartingBean$ApplicationEventListener$start1$Intercepted.onApplicationEvent(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.lambda$publishEvent$17(DefaultBeanContext.java:1071)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at io.micronaut.context.DefaultBeanContext.publishEvent(DefaultBeanContext.java:1065)
	at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:214)
	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:187)
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:69)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:303)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:289)
	at micronaut.general.Application.main(Application.java:8)
Caused by: io.micronaut.context.exceptions.NonUniqueBeanException: Multiple possible bean candidates found: [micronaut.general.IMyBean, micronaut.general.IMyBean]
	at io.micronaut.context.DefaultBeanContext.findConcreteCandidate(DefaultBeanContext.java:1631)
	at io.micronaut.context.DefaultApplicationContext.findConcreteCandidate(DefaultApplicationContext.java:395)
	at io.micronaut.context.DefaultBeanContext.lastChanceResolve(DefaultBeanContext.java:2230)
	at io.micronaut.context.DefaultBeanContext.findConcreteCandidateNoCache(DefaultBeanContext.java:2143)
	at io.micronaut.context.DefaultBeanContext.lambda$findProxyTargetBeanDefinition$11(DefaultBeanContext.java:925)
	at io.micronaut.core.util.clhm.ConcurrentLinkedHashMap.lambda$compute$0(ConcurrentLinkedHashMap.java:721)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1688)
	at io.micronaut.core.util.clhm.ConcurrentLinkedHashMap.compute(ConcurrentLinkedHashMap.java:733)
	at io.micronaut.core.util.clhm.ConcurrentLinkedHashMap.computeIfAbsent(ConcurrentLinkedHashMap.java:710)
	at io.micronaut.context.DefaultBeanContext.findProxyTargetBeanDefinition(DefaultBeanContext.java:917)
	at io.micronaut.context.BeanDefinitionRegistry.getProxyTargetBeanDefinition(BeanDefinitionRegistry.java:275)
	at io.micronaut.context.DefaultBeanContext.getProxyTargetBean(DefaultBeanContext.java:890)
	at micronaut.general.$MyBeanFactory$Bean10Definition$Intercepted.$resolveTarget(Unknown Source)
	at micronaut.general.$MyBeanFactory$Bean10Definition$Intercepted.<init>(Unknown Source)
	at micronaut.general.$$MyBeanFactory$Bean10Definition$InterceptedDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1535)
	... 28 common frames omitted
```

**Comment by jameskleeh** [comment] 2019-08-20 13:49
While this issue was a duplicate of the original problem, it appears this is hitting a slightly different path that has another issue

**Closed** 2019-09-04 18:57 UTC
Labels: type: bug

**Comment by l0co** [comment] 2019-09-10 10:54
I can confirm this fixes the problem.
