### ISSUE TITLE
ServerRequestContext.currentRequest not returning current request

### ISSUE THREAD

**Issue by jonnii** [micronaut-projects/micronaut-core#6052] opened 2021-08-23 01:53 UTC
### Expected Behavior

The following should return the current request in a suspend context:

```
// called from a suspend controller function
suspend fun doSomethingWithCurrentRequest() {
    val currentRequest = ServerRequestContext.currentRequest<HttpRequest<Any>>().orElseGet {
        error("Expected a current http server request")
    }

    someSuspendableThing(currentRequest.headers["some-custom-header'])
}
```

### Actual Behaviour

Whereas previously this approach has worked without any issue since upgrade to `3.0` we have started seeing "weirdness". When running load tests we'll see requests failing our internal validation which uses the header provided by the above that I can't explain and which coincide with the upgrade of one of our services to micronaut 3.0. 

Upon closer inspection what I think is going on is the coroutine is being suspended and resumed on a different thread and the thread local is not being provided to the continuation so the call to `ServerRequestContext.currentRequest` is returning a different concurrent `currentRequest`.

This is all conjecture because I do not (yet) have a reproduction - but I'm going to try to make one.

I'm not sure if we have a workaround because the controller method is `suspend` and it's possible the context switch can happen before hitting the controller. 

#### Further results

I have removed the following and the problem still persists: 

1. All the `suspend` and Kotlin coroutines stuff from the code path 
2. All `@ExecuteOn` and `@NewSpan` annotations

I have also added a `@Header` binding to capture the header value being passed to the controller:

```
# this value comes from the
header value=PARTNER

# this value comes from ServerRequestContext.currentRequest
Creating headers actorType=CUSTOMER
```

These log messages are 1ms apart. 

### Example Application

I'm trying to replicate here:

https://github.com/jonnii/http2error/tree/concurrency-error

### Version

3.0.0

**Comment by jonnii** [comment] 2021-08-23 03:15
Things I'm going to try:

 - [X] Is this affected by `@ExecuteOn`
 - [X] Is this affected by `@NewSpan`
 - [ ] Find a way to get the `CoroutineContext` to grab the httpRequest off of that instead of the ThreadLocal (seems everything is private?)

Removing `@ExecuteOn` and/or `@NewSpan` does not change the outcome.

**Comment by jonnii** [comment] 2021-08-23 20:30
We have downgraded to the previous version of micronaut we were on 2.5.8 and the problem went away. We'll try updating to 2.5.13 once it is released.

**Comment by jameskleeh** [comment] 2021-08-25 13:22
Your example application works for me

```
http2error concurrency-error $ curl localhost:8080/things?opt=hello -H "x-opt: goodbye"
{"query":"hello","header":"goodbye","cheader":"goodbye"}http2error concurrency-error $ 
```

**Comment by jonnii** [comment] 2021-08-25 14:36
@jameskleeh I was unable to reproduce myself outside of our dev environment - the problem only happens under high-ish load too so it's tricky to replicate. Do you have any tips on what I can do to figure out what's causing the problem?

**Comment by jameskleeh** [comment] 2021-08-25 15:02
@jonnii Run the app in a local docker container and use a load testing utility. Really though just FYI ServerRequestContext shouldn't be used for cases where it's possible to pass the request as an argument. So unless you can find the cause its unlikely this would be a priority for us to fix if it is difficult to produce/debug

**Comment by jameskleeh** [comment] 2021-08-26 15:35
Going to close this for now because there is no action we can take at this time. I'll reopen it if you update this issue with more details

**Closed as completed by jameskleeh** 2021-08-26 15:35 UTC
Labels: closed: cannot reproduce
