### ISSUE TITLE
Micronaut 4 does not print version to console anymore

### ISSUE THREAD

**Issue by saw303** [micronaut-projects/micronaut-core#9582] opened 2023-07-19 18:44 UTC
### Expected Behavior

Micronaut 3 printed the version to the console.

```
 __  __ _                                  _   
|  \/  (_) ___ _ __ ___  _ __   __ _ _   _| |_ 
| |\/| | |/ __| '__/ _ \| '_ \ / _` | | | | __|
| |  | | | (__| | | (_) | | | | (_| | |_| | |_ 
|_|  |_|_|\___|_|  \___/|_| |_|\__,_|\__,_|\__|
  Micronaut (v3.9.4)

20:41:12.209 [main] INFO  io.micronaut.runtime.Micronaut - Startup completed in 5171ms. Server Running: http://localhost:8080
```

### Actual Behaviour

Micronaut 4 does not print the version to the console.
```
 __  __ _                                  _   
|  \/  (_) ___ _ __ ___  _ __   __ _ _   _| |_ 
| |\/| | |/ __| '__/ _ \| '_ \ / _` | | | | __|
| |  | | | (__| | | (_) | | | | (_| | |_| | |_ 
|_|  |_|_|\___|_|  \___/|_| |_|\__,_|\__,_|\__|
20:39:05.656 [main] INFO  io.micronaut.runtime.Micronaut - Startup completed in 391ms. Server Running: http://localhost:8080
```

### Steps To Reproduce

1. Clone https://github.com/saw303/m4configuration
2. You'll find a Micronaut 3.9.4 app on branch `micronaut394`
3. You'll find a Micronaut 4.0.0 app on branch `micronaut400_fixed`

### Environment Information

- macOS Ventura
- Java 17

### Example Application

https://github.com/saw303/m4configuration

### Version

4.0.0

**Comment by jeffscottbrown** [comment] 2023-07-19 23:46
https://github.com/micronaut-projects/micronaut-core/commit/7eb851a9690e0f7816378b4d7324bee42450fdbd#diff-7d4a2a3a14e9d6d1c7742301748564a52548946d0a7387c1a22ea4946457ec8cL52-L54

**Comment by alvarosanchez** [comment] 2023-07-20 00:08
@saw303 the banner was purposely removed in #9441 for the reasons discussed in #9190 

Closing this issue as it is certainly not a bug, but please don't hesitate to create a feature request if you still think it is worth it.

**Closed as not planned by alvarosanchez** 2023-07-20 00:08 UTC
Labels: closed: notabug
