### ISSUE TITLE
This issue is re-occurring with 1.2.0.RC2

### ISSUE THREAD

**Issue by juliuskrah** [micronaut-projects/micronaut-core#1926] opened 2019-07-23 16:06 UTC
This issue is re-occurring with 1.2.0.RC2

Generic types are treated as ObjectNodes

_Originally posted by @juliuskrah in https://github.com/micronaut-projects/micronaut-core/issues/1769#issuecomment-514276072_

**Comment by jameskleeh** [comment] 2019-07-23 17:48
Duplicate of https://github.com/micronaut-projects/micronaut-core/issues/1769

**Closed by jameskleeh** 2019-07-23 17:48 UTC
Labels: closed: duplicate
