### ISSUE TITLE
Class which implements ApplicationEventListener<ServerStartupEvent> runs twice

### ISSUE THREAD

**Issue by witek1902** [micronaut-projects/micronaut-core#492] opened 2018-08-13 12:22 UTC
### Steps to Reproduce

Create class, which ```implements ApplicationEventListener<ServerStartupEvent>```
Example (with Lombok):
```
@Slf4j
@Singleton
public class DataLoader implements ApplicationEventListener<ServerStartupEvent> {

    @Override
    public void onApplicationEvent(ServerStartupEvent event) {
        log.info("Demo data added");
    }
}

```

### Expected Behaviour

Event runs only once.

### Actual Behaviour

Event runs twice.

### Environment Information

- **Operating System**: Windows 10 Version 1803 (OS Build 17134.165)
- **Micronaut Version:** 1.0.0.M4
- **JDK Version:** 1.8.0_152

**Comment by witek1902** [comment] 2018-08-14 06:32
In this example PoC we have problem:
https://github.com/asc-lab/micronaut-microservices-poc/tree/master/payment-service

Start log:
https://gist.github.com/witek1902/4965393c561b4339974b08e704098860

```
08:28:34.046 [main] INFO  p.a.a.l.m.p.payment.init.DataLoader - Demo data added
08:28:34.067 [main] INFO  p.a.a.l.m.p.payment.init.DataLoader - Demo data added
```

I suspect that it may be related to Consul.

**Comment by jeffbrown** [comment] 2018-08-15 19:18
See the project at https://github.com/jeffbrown/issue492.  That project contains 3 listeners...

https://github.com/jeffbrown/issue492/blob/master/src/main/groovy/listeners/Second.groovy:

```groovy
// src/main/groovy/issue492/First.groovy
package listeners

import groovy.util.logging.Slf4j
import io.micronaut.context.event.ApplicationEventListener
import io.micronaut.runtime.server.event.ServerStartupEvent

import javax.inject.Singleton

@Slf4j
@Singleton
class First implements ApplicationEventListener<ServerStartupEvent> {

    @Override
    void onApplicationEvent(ServerStartupEvent event) {
        log.debug 'From First implements ApplicationEventListener<ServerStartupEvent>'
    }
}
```

https://github.com/jeffbrown/issue492/blob/master/src/main/groovy/listeners/Second.groovy:

```groovy
// src/main/groovy/issue492/Second.groovy
package listeners

import groovy.util.logging.Slf4j
import io.micronaut.context.event.ApplicationEventListener
import io.micronaut.context.event.StartupEvent
import io.micronaut.aop.Adapter
import javax.inject.Singleton

@Slf4j
@Singleton
class Second {

    @Adapter(ApplicationEventListener)
    void onStartup(StartupEvent event) {
        log.debug 'From @Adapter(ApplicationEventListener)'
    }
}
```

https://github.com/jeffbrown/issue492/blob/master/src/main/groovy/listeners/Third.groovy:

```groovy
// src/main/groovy/issue492/Third.groovy
package listeners

import groovy.util.logging.Slf4j
import io.micronaut.context.event.StartupEvent
import io.micronaut.runtime.event.annotation.EventListener

import javax.inject.Singleton

@Slf4j
@Singleton
class Third {

    @EventListener
    void onStartup(StartupEvent se) {
        log.debug 'From @EventListener'
    }
}
```

At application startup time each of the listeners appears to be invoked once:

```
> Task :run
14:16:48.012 [main] DEBUG listeners.Second - From @Adapter(ApplicationEventListener)
14:16:48.015 [main] DEBUG listeners.Third - From @EventListener
14:16:48.197 [main] DEBUG listeners.First - From First implements ApplicationEventListener<ServerStartupEvent>
14:16:48.463 [main] INFO  io.micronaut.runtime.Micronaut - Startup completed in 1338ms. Server Running: http://localhost:26008
14:16:48.583 [nioEventLoopGroup-1-3] INFO  i.m.d.registration.AutoRegistration - Registered service [issue492] with Consul
```

@witek1902 If you could use that as a starting point and see if you can make that project exhibit the problematic behavior, that would be helpful.

Thanks for your help!

**Comment by witek1902** [comment] 2018-08-17 06:49
Hi @jeffbrown,
However, the problem is not related to Consul.
It's related to @Transactional.

I created own example because it was easier for me to do it with Java and Maven:
https://github.com/witek1902/micronaut-apllication-event-listener-problem

https://github.com/witek1902/micronaut-apllication-event-listener-problem/blob/master/src/main/java/pl/altkom/asc/micronaut/poc/ExampleListener.java
```
package pl.altkom.asc.micronaut.poc;

import io.micronaut.context.event.ApplicationEventListener;
import io.micronaut.runtime.server.event.ServerStartupEvent;
import io.micronaut.spring.tx.annotation.Transactional;
import lombok.extern.slf4j.Slf4j;
import pl.altkom.asc.micronaut.poc.domain.ExampleRepository;

import javax.inject.Singleton;

@Slf4j
@Singleton
public class ExampleListener implements ApplicationEventListener<ServerStartupEvent> {

    private final ExampleRepository exampleRepository;

    public ExampleListener(ExampleRepository exampleRepository) {
        this.exampleRepository = exampleRepository;
    }

    @Override
    @Transactional
    public void onApplicationEvent(ServerStartupEvent event) {
        exampleRepository.exampleMethodWithTransactional();
        log.info("Example listener");
    }
}
```

After I configured DataSource and EntityManager and add @Transactional to method in Listener, Listener is scanned twice.



```
08:43:51.379 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
08:43:51.633 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
08:43:51.664 [main] INFO  org.hibernate.Version - HHH000412: Hibernate Core {5.3.4.Final}
08:43:51.666 [main] INFO  org.hibernate.cfg.Environment - HHH000206: hibernate.properties not found
08:43:51.774 [main] INFO  o.h.validator.internal.util.Version - HV000001: Hibernate Validator 6.0.2.Final
08:43:51.794 [main] INFO  o.h.v.i.engine.ConfigurationImpl - HV000002: Ignoring XML configuration.
08:43:51.998 [main] INFO  o.h.annotations.common.Version - HCANN000001: Hibernate Commons Annotations {5.0.4.Final}
08:43:52.377 [main] INFO  org.hibernate.dialect.Dialect - HHH000400: Using dialect: org.hibernate.dialect.H2Dialect
08:43:56.440 [main] INFO  o.s.o.h.HibernateTransactionManager - Using DataSource [HikariDataSource (HikariPool-1)] of Hibernate SessionFactory for HibernateTransactionManager
08:43:56.548 [main] INFO  o.h.h.i.QueryTranslatorFactoryInitiator - HHH000397: Using ASTQueryTranslatorFactory
08:43:56.684 [main] INFO  p.a.a.micronaut.poc.ExampleListener - Example listener
08:43:56.686 [main] INFO  p.a.a.micronaut.poc.ExampleListener - Example listener
08:43:56.694 [main] INFO  io.micronaut.runtime.Micronaut - Startup completed in 7231ms. Server Running: http://localhost:24415
```

Screens from Debbuger:
https://imgur.com/a/lIRoeHE

I hope that everything is clear now :)

**Comment by jameskleeh** [comment] 2018-08-17 19:57
I see the behavior you're describing in your sample app. I can't reproduce the issue in a test in the spring project. Unfortunately I can't get IDEA to stop at breakpoints so I'll have to convert this to a Gradle project to debug it.

**Comment by jameskleeh** [comment] 2018-08-17 21:09
@witek1902 I was able to reproduce the problem in a test. As a workaround, the following should work for you:

```
@Slf4j
@Singleton
public class ExampleListener  {

    private final ExampleRepository exampleRepository;

    public ExampleListener(ExampleRepository exampleRepository) {
        this.exampleRepository = exampleRepository;
    }

    @Override
    @Transactional
    @EventListener
    public void onApplicationEvent(ServerStartupEvent event) {
        exampleRepository.exampleMethodWithTransactional();
        log.info("Example listener");
    }
}
```

Remove the interface and add `@EventListener`

**Comment by graemerocher** [comment] 2018-08-30 13:51
Fixed by https://github.com/micronaut-projects/micronaut-core/commit/57c91077b474836efa94cd5465fa1468b9e3319c

**Comment by jameskleeh** [comment] 2018-08-30 13:51
This was fixed with https://github.com/micronaut-projects/micronaut-core/pull/520/files

**Closed by graemerocher** 2018-08-30 13:51 UTC
Labels: status: acknowledged, status: in progress

**Comment by hrpath** [comment] 2020-09-09 08:04
Hi !

We're using micronaut 1.3.7 and we can reproduce the double startup

```
@Singleton
public class Application implements ApplicationEventListener<ApplicationStartupEvent>  {

    public static void main(String[] args) {
        Micronaut.run(Application.class);
    }

    @Override
    public void onApplicationEvent(ApplicationStartupEvent event) {
        System.out.println("Application Startup");
    }
}
```

```
10:01:25.532 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
10:01:26.188 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
Application Startup
Application Startup
10:01:26.797 [main] INFO  i.m.g.s.GrpcEmbeddedServerListener - GRPC started on port 50052
10:01:26.799 [main] INFO  io.micronaut.runtime.Micronaut - Startup completed in 2354ms. Server Running: http://localhost:8052
```
